# -*- coding: utf-8 -*-
"""Các thuật ngữ hệ cơ (bao gồm mạc, bao gân, túi hoạt dịch). Định dạng: Tên tiếng Anh: (Tên tiếng Việt, Giới thiệu, Chức năng)

Phần "Giới thiệu" của cơ nêu vị trí và điểm bám, "Chức năng" nêu động tác chính.
"""

TERMS = {
    # ================= Cơ mặt và đầu =================
    'Frontalis muscle': ('Cơ trán', 'Bụng trước của cơ chẩm-trán, nằm dưới da vùng trán, nối xuống da lông mày.',
                         'Nâng lông mày, tạo nếp nhăn ngang trên trán, biểu hiện sự ngạc nhiên và chú ý.'),
    'Occipitalis muscle': ('Cơ chẩm', 'Bụng sau của cơ chẩm-trán, khởi phát từ đường gáy trên của xương chẩm, bám vào mạc mũ.',
                           'Kéo mạc mũ ra sau, phối hợp với cơ trán để cử động da đầu.'),
    'Epicranial aponeurosis': ('Mạc mũ', 'Mạc gân chắc chắn phủ đỉnh sọ, phía trước nối cơ trán, phía sau nối cơ chẩm.',
                               'Nối cơ trán và cơ chẩm để hai cơ phối hợp, kết hợp chặt với da đầu tạo lớp da đầu có thể di chuyển nguyên khối.'),
    'Temporoparietalis muscle': ('Cơ thái dương-đỉnh', 'Cơ mỏng dẹt nằm ở vùng thái dương, phía trên vành tai.',
                                 'Kéo vành tai lên trên và căng da đầu bên; phần lớn người cơ này đã thoái hóa.'),
    'Orbital part of orbicularis oculi': ('Phần ổ mắt của cơ vòng mi', 'Phần vòng ngoài của cơ vòng mi nằm quanh bờ ổ mắt, bao quanh lỗ ổ mắt.',
                                          'Đóng mạnh mi mắt (như che ánh sáng mạnh, hắt hơi), kéo da xung quanh tạo nếp chân chim.'),
    'Palpebral part of orbicularis oculi': ('Phần mi của cơ vòng mi', 'Phần vòng trong mỏng yếu của cơ vòng mi nằm trong mi mắt.',
                                            'Thực hiện chớp mắt không tự chủ và đóng nhẹ mi, phân bố đều nước mắt trên bề mặt giác mạc.'),
    'Corrugator supercilii': ('Cơ nhăn mày', 'Cơ hình nón nhỏ nằm sâu phía trong đầu trong lông mày, khởi phát từ phần mũi xương trán, bám vào da lông mày.',
                              'Kéo lông mày vào trong và xuống dưới, tạo rãnh dọc giữa hai lông mày, biểu hiện cau mày và không hài lòng.'),
    'Procerus muscle': ('Cơ hạ gian mày', 'Cơ hình tam giác nhỏ nằm ở phần trên sống mũi và gian mày.',
                        'Kéo da gian mày xuống, tạo nếp ngang ở gốc mũi, biểu hiện sự chán ghét hoặc sợ ánh sáng.'),
    'Nasalis muscle': ('Cơ mũi', 'Cơ nhỏ phủ mặt ngoài sống mũi, gồm phần ngang và phần cánh.',
                       'Phần ngang thu nhỏ lỗ mũi, phần cánh mở rộng lỗ mũi, làm cánh mũi phập phồng khi hít mạnh.'),
    'Depressor septi nasi': ('Cơ hạ vách mũi', 'Cơ nhỏ nằm giữa môi trên và vách mũi.',
                             'Kéo vách mũi xuống, thu nhỏ lỗ mũi, làm đầu mũi hơi hạ xuống khi cười.'),
    'Levator labii superioris': ('Cơ nâng môi trên', 'Cơ dẹt dạng dải khởi phát từ bờ dưới ổ mắt, bám xuống môi trên.',
                                 'Nâng môi trên, làm sâu rãnh mũi-môi, tham gia biểu cảm lộ răng và chán ghét.'),
    'Levator nasolabialis': ('Cơ nâng môi trên cánh mũi', 'Cơ nâng trong cùng của mặt, khởi phát từ mỏm trán xương hàm trên, chia hai bó bám vào cánh mũi và môi trên.',
                             'Nâng cánh mũi mở rộng lỗ mũi và nâng môi trên, là cơ chính của biểu cảm “hếch mũi”.'),
    'Levator anguli oris': ('Cơ nâng góc miệng', 'Nằm sâu dưới cơ nâng môi trên, khởi phát từ hố răng nanh, bám vào góc miệng.',
                            'Nâng góc miệng, cùng cơ gò má lớn tạo động tác cười.'),
    'Zygomaticus major muscle': ('Cơ gò má lớn', 'Cơ dạng dải chạy chéo từ xương gò má vào trong và xuống dưới, bám vào góc miệng.',
                                 'Kéo góc miệng ra ngoài và lên trên, là cơ chính tạo nụ cười và tiếng cười.'),
    'Zygomaticus minor muscle': ('Cơ gò má nhỏ', 'Nằm phía trong cơ gò má lớn, khởi phát từ xương gò má, bám vào môi trên.',
                                 'Nâng phần ngoài môi trên, làm sâu rãnh mũi-môi, tham gia biểu cảm buồn và khinh miệt.'),
    'Risorius muscle': ('Cơ cười', 'Cơ dạng bó mỏng từ mạc tuyến mang tai chạy ngang ra trước bám vào góc miệng.',
                        'Kéo ngang góc miệng ra ngoài, tạo biểu cảm “lúm đồng tiền” khi cười.'),
    'Depressor anguli oris': ('Cơ hạ góc miệng', 'Cơ hình tam giác khởi phát từ đường chéo xương hàm dưới, bám lên góc miệng.',
                              'Kéo góc miệng xuống, biểu hiện buồn và không hài lòng.'),
    'Depressor labii inferioris': ('Cơ hạ môi dưới', 'Nằm sâu dưới cơ hạ góc miệng, khởi phát từ xương hàm dưới, bám vào môi dưới.',
                                   'Kéo và lật môi dưới ra ngoài, biểu hiện chế giễu hoặc chu môi.'),
    'Mentalis muscle': ('Cơ cằm', 'Cơ hình nón nhỏ nằm hai bên đường giữa vùng cằm.',
                        'Nâng da cằm, đưa môi dưới ra trước, tạo nếp nhăn “vỏ cam” trên cằm, là cơ chính của động tác chu môi.'),
    'Orbicularis oris muscle': ('Cơ vòng miệng', 'Cơ thắt bao quanh khe miệng, do nhiều bó cơ từ nhiều hướng đan xen tạo thành.',
                                'Đóng môi, chu môi, huýt sáo và hút, là then chốt của phát âm và ăn uống.'),
    'Bucinator': ('Cơ má', 'Cơ dẹt sâu tạo nên phần chính của má, nằm giữa cơ vòng miệng và cơ cắn.',
                  'Ép má vào cung răng để ngăn thức ăn đọng ở tiền đình miệng, và thổi phồng má khi thổi nhạc cụ.'),
    'Platysma': ('Cơ bám da cổ', 'Cơ mỏng rộng nằm dưới da mặt trước bên cổ, từ ngực kéo dài đến hàm dưới.',
                 'Căng da cổ, kéo góc miệng và hàm dưới xuống, biểu hiện sợ hãi hoặc căng thẳng.'),

    # ================= Cơ nhai =================
    'Superficial part of masseter': ('Phần nông của cơ cắn', 'Phần cơ cắn khởi phát từ 2/3 trước cung gò má, chạy chéo ra sau và xuống dưới bám vào góc hàm dưới.',
                                     'Nâng mạnh xương hàm dưới đóng miệng và đưa hàm ra trước, là nguồn lực chính của lực nhai.'),
    'Deep part of masseter': ('Phần sâu của cơ cắn', 'Phần cơ cắn khởi phát từ 1/3 sau cung gò má, chạy thẳng xuống bám vào cành hàm dưới.',
                              'Nâng xương hàm dưới đóng miệng và ổn định lồi cầu trong hố khớp.'),
    'Masseteric fascia': ('Mạc cơ cắn', 'Mạc dày bao phủ mặt ngoài cơ cắn, bám lên trên vào cung gò má.',
                          'Giữ cơ cắn, duy trì hướng co, và liên tục với bao tuyến mang tai.'),
    'Temporalis muscle': ('Cơ thái dương', 'Cơ dẹt rộng khởi phát hình quạt từ hố thái dương, đi qua dưới cung gò má bám vào mỏm vẹt xương hàm dưới.',
                          'Sợi trước nâng hàm dưới đóng miệng, sợi sau ngang kéo hàm dưới ra sau, tham gia điều chỉnh tinh tế của nhai.'),
    'Superficial layer of temporal fascia': ('Lớp nông của mạc thái dương', 'Mạc chắc phủ mặt ngoài cơ thái dương, ở trên cung gò má chia thành hai lớp nông sâu.',
                                             'Cung cấp điểm khởi phát một phần cho cơ thái dương và hạn chế phình ra ngoài.'),
    'Medial pterygoid muscle': ('Cơ chân bướm trong', 'Nằm mặt trong cành hàm dưới, khởi phát từ hố chân bướm, bám vào mặt trong góc hàm dưới.',
                                'Nâng hàm dưới đóng miệng; co luân phiên hai bên làm hàm dưới chuyển động nghiền sang bên.'),
    'Superior head of lateral pterygoid muscle': ('Bụng trên của cơ chân bướm ngoài', 'Khởi phát từ mặt dưới cánh lớn xương bướm, bám vào đĩa khớp và bao khớp thái dương-hàm.',
                                                  'Kéo đĩa khớp ở giai đoạn cuối đóng miệng, duy trì phối hợp đĩa khớp với lồi cầu, ngăn tiếng kêu khớp.'),
    'Inferior head of lateral pterygoid muscle': ('Bụng dưới của cơ chân bướm ngoài', 'Khởi phát từ mặt ngoài mảnh ngoài mỏm chân bướm, bám vào hố chân bướm của cổ hàm dưới.',
                                                  'Kéo lồi cầu ra trước và xuống dưới, là cơ chính của há miệng và đưa hàm ra trước.'),

    # ================= Cơ ngoài nhãn cầu và mi =================
    'Superior rectus muscle': ('Cơ thẳng trên', 'Khởi phát từ vòng gân chung, chạy dọc phần trên ổ mắt ra trước bám vào củng mạc phía trên nhãn cầu.',
                               'Làm nhãn cầu quay lên, đồng thời phối hợp quay vào trong và xoay trong.'),
    'Inferior rectus muscle': ('Cơ thẳng dưới', 'Khởi phát từ vòng gân chung, chạy dọc phần dưới ổ mắt ra trước bám vào củng mạc phía dưới nhãn cầu.',
                               'Làm nhãn cầu quay xuống, đồng thời phối hợp quay vào trong và xoay ngoài.'),
    'Medial rectus muscle': ('Cơ thẳng trong', 'Cơ ngoài nhãn cầu mạnh nhất, bám vào củng mạc phía trong nhãn cầu.',
                             'Làm nhãn cầu quay vào trong (về phía mũi), là cơ chính của động tác hội tụ hai mắt.'),
    'Lateral rectus muscle': ('Cơ thẳng ngoài', 'Bám vào củng mạc phía ngoài nhãn cầu, chỉ được thần kinh vận nhãn ngoài chi phối.',
                              'Làm nhãn cầu quay ra ngoài; liệt thần kinh vận nhãn ngoài làm cơ này mất chức năng gây lé trong.'),
    'Superior oblique muscle': ('Cơ chéo trên', 'Khởi phát từ phía trên trong vòng gân chung, gân đi qua ròng rọc rồi gập ra sau ngoài bám vào phía sau trên nhãn cầu.',
                                'Làm nhãn cầu xoay trong, đồng thời phối hợp quay xuống và ra ngoài, được thần kinh ròng rọc chi phối.'),
    'Inferior oblique muscle': ('Cơ chéo dưới', 'Cơ ngoài nhãn cầu duy nhất khởi phát từ phần trước ổ mắt (mặt ổ mắt xương hàm trên), bám vào phía sau ngoài nhãn cầu.',
                                'Làm nhãn cầu xoay ngoài, đồng thời phối hợp quay lên và ra ngoài.'),
    'Common tendinous ring': ('Vòng gân chung', 'Vòng sợi quanh ống thị giác và phần trong khe ổ mắt trên ở đỉnh ổ mắt.',
                              'Điểm khởi phát chung của bốn cơ thẳng và cơ chéo trên; thần kinh thị giác, thần kinh vận nhãn... đi qua đó.'),
    'Trochlea of superior oblique muscle': ('Ròng rọc của cơ chéo trên', 'Vòng sụn sợi hình chữ U nằm ở góc trong trên ổ mắt.',
                                            'Làm ròng rọc cho gân cơ chéo trên, thay đổi hướng kéo, khiến co cơ tạo xoay trong nhãn cầu.'),
    'Levator palpebrae superioris': ('Cơ nâng mi trên', 'Cơ dẹt khởi phát từ phía trên ống thị giác, chạy ra trước bám vào sụn mi trên và da.',
                                     'Nâng mi trên mở khe mi; liệt cơ này biểu hiện sụp mi.'),
    'Superior tarsus': ('Sụn mi trên', 'Tấm mô liên kết đặc hình lưỡi liềm trong mi trên, chứa tuyến sụn mi.',
                        'Tạo khung của mi trên duy trì hình dạng bờ mi, tuyến sụn mi tiết lipid ổn định màng nước mắt.'),
    'Inferior tarsus': ('Sụn mi dưới', 'Tấm mô liên kết đặc hẹp hơn trong mi dưới.',
                        'Nâng đỡ hình dạng mi dưới và giữ bờ mi sát nhãn cầu.'),

    # ================= Nhóm cơ trên dưới xương móng và cơ lưỡi =================
    'Genioglossus muscle': ('Cơ cằm-lưỡi', 'Cơ lưỡi lớn nhất, khởi phát từ gai cằm xương hàm dưới, tỏa hình quạt vào thân lưỡi.',
                            'Đưa lưỡi ra trước và xuống dưới; liệt hai bên khiến gốc lưỡi tụt ra sau có thể tắc đường thở.'),
    'Hyoglossus muscle': ('Cơ móng-lưỡi', 'Cơ hình vuông khởi phát từ thân và sừng lớn xương móng, chạy thẳng lên vào bên lưỡi.',
                          'Hạ và kéo lưỡi về sau, làm lưng lưỡi lõm.'),
    'Geniohyoid muscle': ('Cơ cằm-móng', 'Cơ hẹp nhỏ nằm ở sàn miệng, dưới cơ cằm-lưỡi, nối xương hàm dưới với xương móng.',
                          'Nâng và kéo xương móng ra trước mở rộng họng; khi hàm dưới cố định hỗ trợ há miệng.'),
    'Mylohyoid muscle': ('Cơ hàm-móng', 'Cơ dẹt nối mặt trong hai thân xương hàm dưới, hai bên hợp thành sàn miệng.',
                         'Tạo vách miệng nâng đỡ thân lưỡi, khi nuốt nâng xương móng và sàn miệng đẩy viên thức ăn vào họng.'),
    'Anterior belly of digastric muscle': ('Bụng trước cơ hai bụng', 'Bụng cơ khởi phát từ hố cơ hai bụng xương hàm dưới, chạy chéo ra sau và xuống dưới.',
                                           'Nâng xương móng; khi hàm dưới cố định phối hợp với bụng sau há miệng.'),
    'Posterior belly of digastric muscle': ('Bụng sau cơ hai bụng', 'Bụng cơ khởi phát từ khuyết chũm xương thái dương, chạy chéo ra trước và xuống dưới.',
                                            'Kéo xương móng ra sau và lên trên, là cơ quan trọng nâng xương móng khi nuốt.'),
    'Intermediate tendon of digastric muscle': ('Gân trung gian cơ hai bụng', 'Gân tròn nối hai bụng trước sau của cơ hai bụng, được vòng sợi giữ vào xương móng.',
                                                'Làm ròng rọc hoạt động của cơ hai bụng, cho phép hai bụng kéo xương móng và hàm dưới riêng biệt.'),
    'Stylohyoid muscle': ('Cơ trâm-móng', 'Cơ dài mảnh khởi phát từ mỏm trâm xương thái dương, chạy dọc bờ trên bụng sau cơ hai bụng bám vào xương móng.',
                          'Kéo xương móng ra sau và lên trên, kéo dài sàn miệng, hỗ trợ nuốt.'),
    'Sternohyoid muscle': ('Cơ ức-móng', 'Một trong các cơ dạng dải phía trước cổ, nối mặt sau cán xương ức với bờ dưới thân xương móng.',
                           'Hạ xương móng, đưa xương móng và thanh quản về vị trí sau khi nuốt.'),
    'Sternothyroid muscle': ('Cơ ức-giáp', 'Nằm sâu dưới cơ ức-móng, nối cán xương ức với sụn giáp.',
                             'Hạ thanh quản, là cơ chính hạ thanh quản khi phát âm thấp.'),
    'Thyrohyoid muscle': ('Cơ giáp-móng', 'Phần kéo dài lên trên của cơ ức-giáp, nối sụn giáp với xương móng.',
                          'Làm xương móng và sụn giáp tiến lại gần nhau; khi xương móng cố định nâng thanh quản.'),
    'Omohyoid muscle': ('Cơ vai-móng', 'Gồm hai bụng trên dưới nối bằng gân trung gian, từ bờ trên xương vai chạy chéo đến xương móng.',
                        'Hạ xương móng, gân trung gian bám vào mạc cổ có thể căng thành tĩnh mạch cảnh trong giúp giữ nó mở.'),

    # ================= Cơ họng thanh quản =================
    'Superior pharyngeal constrictor': ('Cơ thắt họng trên', 'Cơ hình quạt tạo nên thành trên họng, khởi phát từ móc chân bướm, đường hàm-móng...',
                                        'Co thắt làm hẹp khoang họng, đẩy viên thức ăn xuống dưới và đóng vòm họng.'),
    'Middle pharyngeal constrictor': ('Cơ thắt họng giữa', 'Cơ thành họng khởi phát từ sừng lớn nhỏ xương móng, tỏa hình quạt ra sau.',
                                      'Làm hẹp phần giữa khoang họng, tiếp nối đẩy viên thức ăn về phía thực quản.'),
    'Inferior pharyngeal constrictor': ('Cơ thắt họng dưới', 'Cơ thắt họng dày nhất, khởi phát từ sụn giáp và sụn nhẫn.',
                                        'Làm hẹp phần dưới khoang họng; phần nhẫn-họng tạo cơ thắt trên thực quản, bình thường đóng ngăn khí vào thực quản.'),
    'Stylopharyngeus muscle': ('Cơ trâm-họng', 'Cơ dài mảnh khởi phát từ gốc mỏm trâm xương thái dương, chạy xuống vào thành họng.',
                               'Nâng và mở rộng họng, nâng họng thanh quản khi nuốt; được thần kinh lưỡi-họng chi phối.'),
    'Palatopharyngeus muscle': ('Cơ khẩu cái-họng', 'Cơ dọc khởi phát từ khẩu cái mềm, chạy xuống trong cung khẩu cái-họng.',
                                'Nâng họng và thanh quản, kéo khẩu cái mềm xuống, ngăn cách vòm họng và hầu miệng ở giai đoạn cuối nuốt.'),
    'Posterior crico-arytenoid muscle': ('Cơ nhẫn-phễu sau', 'Cơ hình tam giác khởi phát từ mặt sau mảnh sụn nhẫn, bám vào mỏm cơ sụn phễu.',
                                         'Cơ thanh quản duy nhất mở rộng khe thanh môn; liệt hai bên gây khó thở thì hít vào nghiêm trọng.'),
    'Lateral crico-arytenoid muscle': ('Cơ nhẫn-phễu bên', 'Khởi phát từ bờ trên cung sụn nhẫn, bám vào mỏm cơ sụn phễu.',
                                       'Làm mỏm thanh âm xoay vào trong, đóng phần màng của khe thanh môn để phát âm.'),
    'Transverse arytenoid muscle': ('Cơ phễu ngang', 'Bó cơ đơn độc chạy ngang nối mặt sau hai sụn phễu.',
                                    'Kéo hai sụn phễu lại gần, đóng phần sụn của khe thanh môn.'),
    'Ary-epiglottic part of oblique arytenoid muscle': ('Cơ phễu-thanh thiệt', 'Phần của cơ phễu chéo kéo dài lên trên vào nếp phễu-thanh thiệt.',
                                                        'Làm hẹp lỗ thanh quản, hỗ trợ nắp thanh thiệt gập ra sau đóng lỗ vào thanh quản khi nuốt.'),
    'Straight part of cricothyroid muscle': ('Phần thẳng của cơ nhẫn-giáp', 'Khởi phát từ mặt trước ngoài cung sụn nhẫn, gần như chạy thẳng lên bám vào bờ dưới sụn giáp.',
                                             'Làm sụn giáp nghiêng trước kéo dài và căng dây thanh, nâng cao cao độ; được nhánh ngoài thần kinh thanh quản trên chi phối.'),
    'Oblique part of cricothyroid muscle': ('Phần chéo của cơ nhẫn-giáp', 'Phần cơ nhẫn-giáp chạy chéo ra sau lên bám vào sừng dưới sụn giáp.',
                                            'Phối hợp với phần thẳng làm sụn giáp nghiêng trước, tăng sức căng dây thanh.'),
    'External part of thyro-arytenoid muscle': ('Phần ngoài của cơ giáp-phễu', 'Lớp ngoài cơ dẹt rộng khởi phát từ mặt trong sụn giáp, chạy ra sau bám vào sụn phễu.',
                                                'Rút ngắn và làm giãn dây thanh, hạ thấp cao độ, đồng thời làm hẹp khe tiền đình.'),
    'Thyro-epiglottic part of thyro-arytenoid muscle': ('Cơ giáp-thanh thiệt', 'Phần cơ giáp-phễu kéo dài lên trên đến bờ ngoài sụn thanh thiệt.',
                                                        'Mở rộng lỗ thanh quản, giúp nắp thanh thiệt trở về vị trí sau khi nuốt.'),

    # ================= Cổ =================
    'Sternocleidomastoid muscle': ('Cơ ức-đòn-chũm', 'Cơ dài to chạy chéo bên cổ, khởi phát từ cán xương ức và đầu trong xương đòn, bám vào mỏm chũm.',
                                   'Co một bên làm đầu quay sang bên đối diện và nghiêng về cùng bên; co hai bên làm đầu ngửa ra sau, nâng lồng ngực khi hít mạnh.'),
    'Scalenus anterior muscle': ('Cơ bậc thang trước', 'Khởi phát từ củ trước mỏm ngang đốt sống cổ 3–6, bám vào củ cơ bậc thang của xương sườn 1.',
                                 'Nâng xương sườn 1 hỗ trợ hít sâu, nghiêng cổ sang bên; cùng cơ bậc thang giữa và xương sườn 1 tạo khoảng cơ bậc thang, đám rối cánh tay và động mạch dưới đòn đi qua đó.'),
    'Scalenus medius muscle': ('Cơ bậc thang giữa', 'Cơ bậc thang dài và lớn nhất, khởi phát từ củ sau mỏm ngang tất cả đốt sống cổ, bám vào xương sườn 1.',
                               'Nâng xương sườn 1 và nghiêng cột sống cổ, tạo thành bờ sau của khoảng cơ bậc thang.'),
    'Scalenus posterior muscle': ('Cơ bậc thang sau', 'Cơ bậc thang nhỏ và sâu nhất, khởi phát từ mỏm ngang đốt sống cổ dưới, bám vào xương sườn 2.',
                                  'Nâng xương sườn 2 và nghiêng cổ sang bên.'),
    'Longus colli muscle': ('Cơ dài cổ', 'Cơ dài sâu nằm sát mặt trước thân đốt sống cổ.',
                            'Gập trước và xoay nhẹ cột sống cổ, là cơ lõi sâu duy trì ưỡn trước cột sống cổ.'),
    'Longus capitis muscle': ('Cơ dài đầu', 'Khởi phát từ mỏm ngang đốt sống cổ 3–6, chạy lên bám vào phần đáy xương chẩm.',
                              'Gập trước đầu và ổn định khớp chẩm-đốt sống cổ.'),
    'Rectus anterior capitis muscle': ('Cơ thẳng trước đầu', 'Cơ ngắn sâu nhỏ nằm giữa đốt sống cổ 1 và xương chẩm.',
                                       'Làm đầu gập trước ở khớp chẩm-đốt sống cổ, điều chỉnh tinh tế tư thế đầu.'),
    'Rectus lateralis capitis muscle': ('Cơ thẳng bên đầu', 'Cơ ngắn nối mỏm ngang đốt sống cổ 1 với mỏm tĩnh mạch cảnh xương chẩm.',
                                        'Làm đầu nghiêng sang cùng bên, ổn định khớp chẩm-đốt sống cổ.'),
    'Superficial investing cervical fascia': ('Mạc cổ bao bọc nông', 'Mạc bao quanh toàn cổ, phân lớp bao cơ ức-đòn-chũm và cơ thang.',
                                              'Bao bọc và ngăn cách các cấu trúc cổ, tạo ranh giới các khoảng mạc cổ, là hàng rào tự nhiên chống lan nhiễm trùng.'),

    # ================= Dưới chẩm và lớp sâu lưng =================
    'Rectus posterior major capitis muscle': ('Cơ thẳng sau lớn đầu', 'Cơ dưới chẩm hình tam giác khởi phát từ mỏm gai đốt sống cổ 2, bám vào phần ngoài đường gáy dưới xương chẩm.',
                                              'Ngửa đầu ra sau và quay đầu về cùng bên, tạo bờ trong trên của tam giác dưới chẩm.'),
    'Rectus posterior minor capitis muscle': ('Cơ thẳng sau nhỏ đầu', 'Cơ nhỏ khởi phát từ củ sau đốt sống cổ 1, bám vào phần trong đường gáy dưới xương chẩm.',
                                              'Ngửa đầu ra sau; cầu cơ-màng cứng giữa cơ này và màng cứng tủy sống được cho là liên quan đến đau đầu có nguồn gốc cổ.'),
    'Obliquus superior capitis muscle': ('Cơ chéo trên đầu', 'Cơ dưới chẩm khởi phát từ mỏm ngang đốt sống cổ 1, bám vào xương chẩm, tạo bờ ngoài trên của tam giác dưới chẩm.',
                                         'Ngửa và nghiêng đầu sang bên, kiểm soát tinh tế khớp chẩm-đốt sống cổ.'),
    'Obliquus inferior capitis muscle': ('Cơ chéo dưới đầu', 'Nối mỏm gai đốt sống cổ 2 với mỏm ngang đốt sống cổ 1, tạo bờ dưới của tam giác dưới chẩm.',
                                         'Làm đốt sống cổ 1 cùng đầu xoay quanh mấu răng về cùng bên.'),
    'Splenius capitis muscle': ('Cơ gối đầu', 'Khởi phát từ dây chằng gáy và mỏm gai đốt sống ngực trên, chạy chéo ra ngoài lên bám vào mỏm chũm và đường gáy trên.',
                                'Co một bên làm đầu quay về cùng bên, co hai bên làm đầu cổ ngửa ra sau.'),
    'Splenius colli muscle': ('Cơ gối cổ', 'Nằm phía dưới ngoài cơ gối đầu, khởi phát từ mỏm gai đốt sống ngực 3–6, bám vào mỏm ngang đốt sống cổ trên.',
                              'Co một bên làm cổ quay về cùng bên, co hai bên duỗi sau cổ.'),
    'Iliocostalis colli muscle': ('Cơ chậu-sườn cổ', 'Đoạn cổ của cột ngoài cùng của cơ dựng sống, khởi phát từ xương sườn 3–6, bám vào mỏm ngang đốt sống cổ.',
                                  'Duỗi sau và nghiêng sang bên cột sống cổ, duy trì tư thế thẳng của đoạn cổ.'),
    'Iliocostalis thoracis muscle': ('Cơ chậu-sườn ngực', 'Đoạn ngực của cột ngoài cơ dựng sống, nối các xương sườn dưới với xương sườn trên.',
                                     'Duỗi sau cột sống ngực và hạ xương sườn, tham gia thở ra mạnh.'),
    'Iliocostalis lumborum muscle': ('Cơ chậu-sườn thắt lưng', 'Đoạn dưới cùng của cột ngoài cơ dựng sống, khởi phát từ xương cùng và mào chậu, bám vào góc xương sườn dưới.',
                                     'Duỗi sau và nghiêng sang bên cột sống thắt lưng, là cơ duỗi chính khi đứng dậy từ tư thế cúi.'),
    'Longissimus capitis muscle': ('Cơ dài nhất đầu', 'Đoạn trên cùng của cột giữa cơ dựng sống, bám vào bờ sau mỏm chũm.',
                                   'Ngửa đầu ra sau và quay đầu về cùng bên.'),
    'Longissimus colli muscle': ('Cơ dài nhất cổ', 'Đoạn cổ của cột giữa cơ dựng sống, nối đốt sống ngực trên với mỏm ngang đốt sống cổ.',
                                 'Duỗi sau và nghiêng sang bên cột sống cổ.'),
    'Longissimus thoracis muscle': ('Cơ dài nhất ngực', 'Cột dài nhất của cơ dựng sống, chạy dọc đoạn thắt lưng-ngực bám vào các xương sườn và mỏm ngang.',
                                    'Duỗi sau cột sống, kiểm soát tốc độ ly tâm khi thân gập trước, là cơ lõi duy trì tư thế thẳng.'),
    'Spinalis capitis muscle': ('Cơ gai đầu', 'Đoạn trên cùng của cột trong cùng cơ dựng sống, thường hòa vào cơ bán gai.',
                                'Duỗi sau đầu, ổn định chỗ nối sọ-cột sống cổ.'),
    'Spinalis colli muscle': ('Cơ gai cổ', 'Đoạn cổ của cột trong cơ dựng sống, nối dây chằng gáy với mỏm gai đốt sống cổ.',
                              'Duỗi sau cột sống cổ, thường có biến đổi phát triển.'),
    'Spinalis thoracis muscle': ('Cơ gai ngực', 'Cột trong cùng của cơ dựng sống, nối mỏm gai các đốt sống ngực trên dưới.',
                                 'Duỗi sau cột sống ngực, duy trì tư thế thẳng của đoạn ngực.'),
    'Semispinalis colli muscle': ('Cơ bán gai cổ', 'Một trong nhóm cơ ngang-gai, bắt chéo 4–6 đốt sống bám vào mỏm gai đốt sống cổ.',
                                  'Duỗi sau cột sống cổ và quay về bên đối diện.'),
    'Semispinalis thoracis muscle': ('Cơ bán gai ngực', 'Một trong nhóm cơ ngang-gai, nằm ở lớp sâu đoạn ngực.',
                                     'Duỗi sau cột sống ngực và quay thân về bên đối diện.'),
    'Multifidus colli muscle': ('Cơ đa chẻ cổ', 'Cơ ngắn sâu sát bản sống, bắt chéo 2–4 đốt sống.',
                                'Ổn định từng đốt sống cổ, là một trong các cơ giàu cảm thụ bản thể nhất ở cổ.'),
    'Multifidus thoracis muscle': ('Cơ đa chẻ ngực', 'Phần đoạn ngực của lớp sâu nhất nhóm cơ ngang-gai.',
                                   'Ổn định từng đốt sống ngực, kiểm soát dịch chuyển nhỏ khi xoay.'),
    'Multifidus lumborum muscle': ('Cơ đa chẻ thắt lưng', 'Cơ ổn định sâu dày nhất đoạn thắt lưng, sát hai bên mỏm gai.',
                                   'Duy trì ổn định đoạn cột sống thắt lưng, là cơ trọng điểm trong phục hồi đau lưng.'),
    'Rotatores': ('Cơ xoay', 'Lớp sâu nhất của nhóm cơ ngang-gai, cơ hình vuông nhỏ chỉ bắt chéo 1–2 đốt sống.',
                  'Làm đốt sống xoay nhẹ; giàu thoi cơ, chủ yếu cung cấp cảm thụ bản thể về vị trí cột sống.'),
    'Interspinales colli muscles': ('Cơ gian gai cổ', 'Cặp cơ ngắn nối giữa mỏm gai các đốt sống cổ liền kề.',
                                    'Duỗi sau cột sống cổ và cảm nhận vị trí đoạn.'),
    'Interspinales thoracis muscles': ('Cơ gian gai ngực', 'Cơ ngắn nhỏ nối giữa mỏm gai các đốt sống ngực liền kề.',
                                       'Hỗ trợ duỗi sau cột sống ngực, cung cấp cảm thụ bản thể.'),
    'Interspinales lumborum muscles': ('Cơ gian gai thắt lưng', 'Cặp cơ ngắn nối giữa mỏm gai các đốt sống thắt lưng liền kề.',
                                       'Duỗi sau cột sống thắt lưng và ổn định các đoạn liền kề.'),
    'Dorsal parts of lateral intertransversarii lumborum muscles':
        ('Phần lưng của cơ gian mỏm ngang ngoài thắt lưng', 'Cơ nhỏ sâu nối giữa mỏm phụ và mỏm ngang các đốt sống thắt lưng liền kề.',
         'Nghiêng sang bên cột sống thắt lưng và ổn định các đốt sống liền kề.'),
    'Ventral parts of lateral intertransversarii lumborum muscles':
        ('Phần bụng của cơ gian mỏm ngang ngoài thắt lưng', 'Cơ nhỏ nối giữa phần trước mỏm ngang các đốt sống thắt lưng liền kề.',
         'Nghiêng sang bên cột sống thắt lưng, cùng phần lưng kiểm soát ổn định bên đoạn thắt lưng.'),
    'Levatores breves costarum': ('Cơ nâng sườn ngắn', 'Cơ hình tam giác nhỏ khởi phát từ mỏm ngang đốt sống ngực, chạy chéo xuống ngoài bám vào xương sườn dưới.',
                                  'Nâng xương sườn hỗ trợ hít vào, và hỗ trợ xoay cột sống.'),
    'Levatores longi costarum': ('Cơ nâng sườn dài', 'Cơ nâng sườn bắt chéo hai đoạn bám vào xương sườn dưới hai bậc.',
                                 'Nâng xương sườn mở rộng lồng ngực, tham gia hít sâu.'),
    'Serratus posterior superior muscle': ('Cơ răng cưa sau trên', 'Nằm sâu dưới cơ trám, khởi phát từ phần dưới dây chằng gáy và mỏm gai đốt sống ngực trên, bám vào xương sườn 2–5.',
                                           'Nâng xương sườn hỗ trợ hít vào.'),
    'Serratus posterior inferior muscle': ('Cơ răng cưa sau dưới', 'Nằm sâu dưới cơ lưng rộng, khởi phát từ mạc ngực-thắt lưng, bám vào xương sườn 9–12.',
                                           'Kéo xương sườn xuống và ngăn chúng bị kéo lên khi cơ hoành co.'),

    # ================= Lớp nông lưng và đai vai =================
    'Descending part of trapezius muscle': ('Phần xuống của cơ thang', 'Sợi trên của cơ thang khởi phát từ xương chẩm và dây chằng gáy, chạy chéo xuống ngoài bám vào 1/3 ngoài xương đòn.',
                                            'Nâng xương vai (nhún vai) và hỗ trợ xoay lên trên.'),
    'Transverse part of trapezius muscle': ('Phần ngang của cơ thang', 'Sợi giữa của cơ thang khởi phát từ mỏm gai đốt sống cổ dưới và ngực trên, chạy ngang bám vào mỏm cùng vai.',
                                            'Khép (kéo về sau) xương vai, làm hai vai mở rộng ra sau ưỡn ngực.'),
    'Ascending part of trapezius muscle': ('Phần lên của cơ thang', 'Sợi dưới của cơ thang khởi phát từ mỏm gai đốt sống ngực dưới, chạy chéo lên ngoài bám vào gai vai.',
                                           'Hạ xương vai, và cùng sợi trên tạo cặp lực hoàn thành động tác đưa tay lên trên đầu.'),
    'Latissimus dorsi muscle': ('Cơ lưng rộng', 'Cơ dẹt hình tam giác rộng ở phần dưới lưng, khởi phát từ đốt sống ngực dưới, mạc ngực-thắt lưng và mào chậu, bám vào rãnh gian củ xương cánh tay.',
                                'Khép, duỗi sau và xoay trong xương cánh tay, là cơ động lực chính của kéo xà và bơi.'),
    'Rhomboid major muscle': ('Cơ trám lớn', 'Nằm sâu dưới cơ thang, khởi phát từ mỏm gai đốt sống ngực 2–5, bám vào bờ trong xương vai.',
                              'Khép và xoay xuống dưới xương vai, cố định xương vai vào lồng ngực.'),
    'Rhomboid minor muscle': ('Cơ trám nhỏ', 'Nằm phía trên cơ trám lớn, khởi phát từ mỏm gai đốt sống cổ 7 và ngực 1.',
                              'Phối hợp với cơ trám lớn khép và hơi nâng xương vai.'),
    'Levator scapulae': ('Cơ nâng vai', 'Cơ dạng dải khởi phát từ mỏm ngang 4 đốt sống cổ trên, bám vào góc trên xương vai.',
                         'Nâng xương vai và xoay xuống dưới; khi cổ cố định nghiêng cột sống cổ sang bên, là cơ thường bị ảnh hưởng khi vẹo cổ.'),
    'Serratus anterior muscle': ('Cơ răng cưa trước', 'Cơ dạng răng cưa khởi phát từ mặt ngoài 8–9 xương sườn trên, vòng quanh thành bên lồng ngực bám vào mặt trước bờ trong xương vai.',
                                 'Kéo xương vai ra trước sát thành ngực và xoay lên trên; liệt gây “vai cánh”.'),
    'Subclavius muscle': ('Cơ dưới đòn', 'Cơ hình trụ nhỏ nằm giữa mặt dưới xương đòn và xương sườn 1.',
                          'Kéo xuống và ổn định xương đòn, khi gãy xương đòn đệm bớt tổn thương mạch dưới đòn bên dưới.'),
    'Pectoralis minor muscle': ('Cơ ngực nhỏ', 'Nằm sâu dưới cơ ngực lớn, khởi phát từ xương sườn 3–5, bám vào mỏm quạ xương vai.',
                                'Kéo xuống và đưa ra trước xương vai; khi xương vai cố định nâng xương sườn hỗ trợ hít vào.'),
    'Clavicular head of pectoralis major muscle': ('Phần đòn của cơ ngực lớn', 'Sợi trên của cơ ngực lớn khởi phát từ nửa trong xương đòn.',
                                                   'Gập trước và khép cánh tay trên, là cơ chính của động tác đẩy lên chéo.'),
    'Sternocostal head of pectoralis major muscle': ('Phần ức-sườn của cơ ngực lớn', 'Phần chính của cơ ngực lớn khởi phát từ xương ức và sụn sườn 6 trên.',
                                                     'Khép, xoay trong và gập trước cánh tay trên, là cơ chính của đẩy tạ nằm và động tác chắp tay.'),
    '(Abdominal part of pectoralis major muscle)': ('Phần bụng của cơ ngực lớn', 'Sợi dưới cùng của cơ ngực lớn khởi phát từ lớp trước bao cơ thẳng bụng, thường có biến đổi.',
                                                    'Kéo xuống cánh tay trên và đai vai, khi leo trèo kéo thân về phía chi trên cố định.'),
    'Pectoral fascia': ('Mạc ngực', 'Mạc mỏng phủ mặt ngoài cơ ngực lớn.',
                        'Bao cơ ngực lớn và tiếp tục xuống mạc thành bụng, cung cấp mặt trượt phía sau cho tuyến vú.'),
    'Clavipectoral fascia': ('Mạc đòn-ngực', 'Nằm sâu dưới cơ ngực lớn, mạc căng giữa xương đòn, mỏm quạ và cơ ngực nhỏ.',
                             'Treo và bao cơ ngực nhỏ với cơ dưới đòn; tĩnh mạch đầu, mạch ngực-mỏm cùng vai và thần kinh ngực ngoài xuyên qua mạc này.'),
    'Clavicular part of deltoid muscle': ('Phần đòn của cơ delta', 'Sợi trước của cơ delta khởi phát từ 1/3 ngoài xương đòn.',
                                          'Gập trước và xoay trong cánh tay trên, là cơ chính của đẩy ra trước và vung tay.'),
    'Acromial part of deltoid muscle': ('Phần cùng vai của cơ delta', 'Sợi giữa đa lông chim của cơ delta khởi phát từ mỏm cùng vai, là phần mạnh nhất của cơ delta.',
                                        'Dạng cánh tay trên từ 15° trở lên đến vị trí ngang, đảm nhận lực chính của dạng vai.'),
    'Scapular spinal part of deltoid muscle': ('Phần gai vai của cơ delta', 'Sợi sau của cơ delta khởi phát từ bờ dưới gai vai.',
                                               'Duỗi sau và xoay ngoài cánh tay trên, phối hợp với cơ lưng rộng hoàn thành động tác kéo ra sau.'),
    'Deltoid fascia': ('Mạc cơ delta', 'Mạc dày bao cơ delta, tiếp tục xuống mạc cánh tay.',
                       'Giữ cơ delta và cung cấp điểm bám cho sợi sâu.'),

    # ================= Chóp xoay và cánh tay trên =================
    'Supraspinatus muscle': ('Cơ trên gai', 'Nằm trong hố trên gai xương vai, gân đi qua khoảng dưới mỏm cùng vai bám vào củ lớn xương cánh tay.',
                             'Khởi động 15° đầu tiên của dạng cánh tay trên và ổn định chỏm xương cánh tay trong ổ chảo; là gân thường bị rách nhất trong tổn thương chóp xoay.'),
    'Infraspinatus muscle': ('Cơ dưới gai', 'Cơ hình tam giác chiếm hố dưới gai xương vai, bám vào phần giữa củ lớn xương cánh tay.',
                             'Xoay ngoài cánh tay trên và ép chỏm xương cánh tay vào ổ chảo duy trì ổn định khớp vai.'),
    'Teres minor muscle': ('Cơ tròn nhỏ', 'Cơ dài hẹp nằm dưới cơ dưới gai, khởi phát từ phần trên bờ ngoài xương vai.',
                           'Xoay ngoài và khép cánh tay trên, là cấu trúc ổn định phía sau chóp xoay.'),
    'Teres major muscle': ('Cơ tròn lớn', 'Cơ dày khởi phát từ góc dưới xương vai, bám vào mào củ nhỏ xương cánh tay, không thuộc chóp xoay.',
                           'Khép, xoay trong và duỗi sau cánh tay trên, phối hợp với cơ lưng rộng phát lực.'),
    'Subscapularis muscle': ('Cơ dưới vai', 'Cơ hình tam giác chiếm hố dưới vai, bám vào củ nhỏ xương cánh tay.',
                             'Xoay trong cánh tay trên, và ổn định khớp vai từ phía trước ngăn trật chỏm xương cánh tay ra trước.'),
    'Coracobrachialis muscle': ('Cơ quạ-cánh tay', 'Cơ dài mảnh khởi phát từ mỏm quạ xương vai, bám vào phần giữa mặt trong xương cánh tay.',
                                'Gập trước và khép cánh tay trên; thần kinh cơ-da xuyên qua bụng cơ.'),
    'Long head of biceps brachii': ('Bụng dài cơ nhị đầu cánh tay', 'Khởi phát từ củ trên ổ chảo xương vai, gân xuyên qua bao khớp vai đi xuống rãnh gian củ.',
                                    'Gập khuỷu và xoay sau cẳng tay; gân trong rãnh gian củ có vai trò ổn định chỏm xương cánh tay.'),
    'Short head of biceps brachii': ('Bụng ngắn cơ nhị đầu cánh tay', 'Khởi phát từ mỏm quạ xương vai, hợp với bụng dài thành một bụng cơ bám vào ụ xương quay.',
                                     'Gập khuỷu, xoay sau cẳng tay và hỗ trợ gập trước cánh tay trên.'),
    'Brachialis muscle': ('Cơ cánh tay', 'Nằm sâu dưới cơ nhị đầu cánh tay, khởi phát từ mặt trước nửa dưới xương cánh tay, bám vào ụ xương trụ.',
                          'Cơ gập khuỷu chính nhất; vì bám vào xương trụ nên tác dụng không phụ thuộc vị trí xoay cẳng tay.'),
    'Long head of triceps brachii': ('Bụng dài cơ tam đầu cánh tay', 'Bụng duy nhất bắt chéo khớp vai, khởi phát từ củ dưới ổ chảo xương vai.',
                                     'Duỗi khuỷu và duỗi sau, khép cánh tay trên, là then chốt phát lực phối hợp vai-khuỷu.'),
    'Lateral head of triceps brachii': ('Bụng ngoài cơ tam đầu cánh tay', 'Khởi phát từ mặt sau xương cánh tay phía trên ngoài rãnh thần kinh quay.',
                                        'Duỗi mạnh khuỷu, là cơ chính của động tác đẩy nhanh.'),
    'Medial head of triceps brachii': ('Bụng trong cơ tam đầu cánh tay', 'Nằm sâu nhất, khởi phát từ mặt sau xương cánh tay phía dưới trong rãnh thần kinh quay.',
                                       'Duỗi khuỷu; tham gia ở mọi góc độ, là “cơ lao động” của duỗi khuỷu.'),
    'Anconeus muscle': ('Cơ khuỷu', 'Cơ hình tam giác nhỏ phía sau ngoài khuỷu, khởi phát từ mỏm trên lồi cầu ngoài xương cánh tay, bám vào mặt ngoài mỏm khuỷu xương trụ.',
                        'Hỗ trợ duỗi khuỷu và ổn định khớp khuỷu khi cẳng tay xoay trước, là mốc đường vào thường dùng trong phẫu thuật khớp khuỷu.'),
    'Brachial fascia': ('Mạc cánh tay', 'Mạc sâu bao nhóm cơ cánh tay trên, tiếp tục xuống mạc cẳng tay.',
                        'Giữ nhóm cơ cánh tay trên, và phát ra vách gian cơ trong ngoài chia cánh tay thành hai bao xương-mạc trước sau.'),
    'Medial intermuscular septum of arm': ('Vách gian cơ trong cánh tay', 'Tấm sợi từ mặt sâu mạc cánh tay bám vào bờ trong xương cánh tay.',
                                           'Ngăn cách nhóm cơ trước sau cánh tay trên và cung cấp điểm bám; thần kinh trụ xuyên qua vách này từ trước vào sau.'),
    'Lateral intermuscular septum of arm': ('Vách gian cơ ngoài cánh tay', 'Tấm sợi bám vào bờ ngoài xương cánh tay.',
                                            'Ngăn cách nhóm cơ trước sau cánh tay trên; thần kinh quay xuyên qua vách này từ sau vào trước.'),

    # ================= Cẳng tay =================
    'Brachioradialis muscle': ('Cơ cánh tay-quay', 'Cơ dài hình thoi nông nhất mặt ngoài cẳng tay, khởi phát từ phía trên mỏm trên lồi cầu ngoài xương cánh tay, bám vào mỏm trâm xương quay.',
                               'Gập mạnh khuỷu ở tư thế nửa xoay trước cẳng tay, là “cơ nâng cốc bia”; được thần kinh quay chi phối nhưng thực hiện chức năng gập khuỷu.'),
    'Superficial head of pronator teres': ('Bụng nông của cơ sấp tròn', 'Bụng nông khởi phát từ mỏm trên lồi cầu trong xương cánh tay.',
                                           'Làm cẳng tay xoay trước và hỗ trợ gập khuỷu; khoảng giữa hai bụng là đường đi của thần kinh giữa.'),
    'Deep head of pronator teres': ('Bụng sâu của cơ sấp tròn', 'Bụng nhỏ sâu khởi phát từ mỏm vẹt xương trụ.',
                                    'Cùng bụng nông làm cẳng tay xoay trước; thần kinh giữa đi giữa hai bụng, dễ bị chèn ép tại đây.'),
    'Pronator quadratus': ('Cơ sấp vuông', 'Cơ hình vuông nằm sâu mặt trước cẳng tay xa, chạy ngang nối xương trụ và xương quay.',
                           'Là cơ khởi động của xoay trước cẳng tay, và kéo chặt đầu xa xương trụ-quay để ổn định khớp trụ-quay dưới.'),
    'Supinator': ('Cơ ngửa', 'Cơ dẹt rộng bao quanh đầu trên xương quay, khởi phát từ mỏm trên lồi cầu ngoài xương cánh tay và mào cơ ngửa xương trụ.',
                  'Làm cẳng tay xoay sau; nhánh sâu thần kinh quay đi giữa hai lớp (cung Frohse), dễ bị chèn ép tại đây.'),
    'Flexor carpi radialis': ('Cơ gập cổ tay quay', 'Cơ dài hình thoi khởi phát từ mỏm trên lồi cầu trong xương cánh tay, bám vào nền xương bàn tay 2, gân là mốc trong sờ động mạch quay ở cổ tay.',
                              'Gập cổ tay và dạng cổ tay (lệch quay).'),
    'Palmaris longus muscle': ('Cơ gan tay dài', 'Cơ dài mảnh ở giữa mặt trước cẳng tay, bụng cơ nhỏ gân dài mảnh, khoảng 15% người thiếu bẩm sinh.',
                               'Gập cổ tay và căng mạc gan tay; vì chức năng có thể được thay thế, thường được lấy làm vật liệu ghép gân.'),
    'Humeral head of flexor carpi ulnaris': ('Bụng cánh tay của cơ gập cổ tay trụ', 'Bụng khởi phát từ mỏm trên lồi cầu trong xương cánh tay.',
                                             'Gập cổ tay và khép cổ tay (lệch trụ).'),
    'Ulnar head of flexor carpi ulnaris': ('Bụng trụ của cơ gập cổ tay trụ', 'Bụng khởi phát từ mỏm khuỷu và 2/3 trên bờ sau xương trụ.',
                                           'Cùng bụng cánh tay gập cổ tay, lệch trụ; cung gân giữa hai bụng (ống khuỷu) là nơi thần kinh trụ thường bị chèn ép nhất.'),
    'Humero-ulnar head of flexor digitorum superficialis': ('Bụng cánh tay-trụ của cơ gập các ngón nông', 'Bụng khởi phát từ mỏm trên lồi cầu trong xương cánh tay và mỏm vẹt xương trụ.',
                                                            'Gập đốt giữa ngón 2–5, và hỗ trợ gập cổ tay.'),
    'Radial head of flexor digitorum superficialis': ('Bụng quay của cơ gập các ngón nông', 'Bụng khởi phát từ mặt trước nửa trên xương quay.',
                                                      'Cùng bụng cánh tay-trụ gập đốt giữa; dưới cung gân giữa hai bụng có thần kinh giữa đi qua.'),
    'Flexor digitorum profundus': ('Cơ gập các ngón sâu', 'Cơ rộng dày ở lớp sâu mặt trước cẳng tay, khởi phát từ 2/3 trên xương trụ và màng gian xương, bám vào đốt xa ngón 2–5.',
                                   'Cơ duy nhất gập đốt xa ngón, là động lực cốt lõi của nắm chặt tay; nửa quay do thần kinh giữa, nửa trụ do thần kinh trụ chi phối.'),
    'Flexor pollicis longus': ('Cơ gập ngón cái dài', 'Khởi phát từ mặt trước phần giữa xương quay và màng gian xương, bám vào nền đốt xa ngón cái.',
                               'Gập khớp gian đốt ngón cái, là cơ then chốt của động tác kẹp.'),
    'Extensor carpi radialis longus': ('Cơ duỗi cổ tay quay dài', 'Khởi phát từ mào mỏm trên lồi cầu ngoài xương cánh tay, bám vào nền xương bàn tay 2.',
                                       'Duỗi cổ tay và dạng cổ tay (lệch quay); co đồng bộ khi nắm tay để ổn định khớp cổ tay.'),
    'Extensor carpi radialis brevis': ('Cơ duỗi cổ tay quay ngắn', 'Nằm sâu dưới cơ dài, khởi phát từ mỏm trên lồi cầu ngoài xương cánh tay, bám vào nền xương bàn tay 3.',
                                       'Duỗi cổ tay; điểm khởi phát là vị trí tổn thương thường gặp nhất của “khuỷu tay người chơi tennis” (viêm mỏm trên lồi cầu ngoài).'),
    'Extensor digitorum': ('Cơ duỗi các ngón', 'Cơ duỗi chính mặt sau cẳng tay, khởi phát từ mỏm trên lồi cầu ngoài xương cánh tay, bằng bốn gân bám vào mạc gân mu ngón 2–5.',
                           'Duỗi khớp bàn-ngón của ngón 2–5 và hỗ trợ duỗi cổ tay.'),
    'Extensor digiti minimi': ('Cơ duỗi ngón út', 'Cơ dài mảnh tách từ phía trụ của cơ duỗi các ngón, bám vào mạc gân mu ngón út.',
                               'Duỗi riêng ngón út, cho phép ngón út hoạt động độc lập với các ngón khác.'),
    'Humeral head of extensor carpi ulnaris': ('Bụng cánh tay của cơ duỗi cổ tay trụ', 'Bụng khởi phát từ mỏm trên lồi cầu ngoài xương cánh tay.',
                                               'Duỗi cổ tay và khép cổ tay (lệch trụ).'),
    'Ulnar head of extensor carpi ulnaris': ('Bụng trụ của cơ duỗi cổ tay trụ', 'Bụng khởi phát từ bờ sau xương trụ, gân đi trong rãnh lưng đầu xương trụ.',
                                             'Duỗi cổ tay, lệch trụ, và ổn định phía trụ khớp cổ tay.'),
    'Abductor pollicis longus': ('Cơ dạng ngón cái dài', 'Khởi phát từ mặt lưng xương trụ-quay và màng gian xương, bám vào nền xương bàn tay 1.',
                                 'Dạng ngón cái và cổ tay; gân tạo bờ quay của “hố thuốc lá”.'),
    'Extensor pollicis brevis': ('Cơ duỗi ngón cái ngắn', 'Nằm sát cơ dạng ngón cái dài, bám vào nền đốt gần ngón cái.',
                                 'Duỗi khớp bàn-ngón ngón cái; cùng gân cơ dạng ngón cái dài nằm trong một bao, là gân bị ảnh hưởng trong viêm bao gân hẹp mỏm trâm quay.'),
    'Extensor pollicis longus': ('Cơ duỗi ngón cái dài', 'Khởi phát từ mặt lưng đoạn giữa xương trụ, gân vòng quanh củ lưng xương quay chuyển hướng đến đốt xa ngón cái.',
                                 'Duỗi khớp gian đốt ngón cái và đưa ngón cái ra sau; gân tạo bờ trụ của “hố thuốc lá”.'),
    'Extensor indicis': ('Cơ duỗi ngón trỏ', 'Cơ sâu nhất mặt sau cẳng tay phía dưới, bám vào mạc gân mu ngón trỏ.',
                         'Duỗi độc lập ngón trỏ, cho phép ngón trỏ thực hiện riêng động tác chỉ.'),
    'Antebrachial fascia': ('Mạc cẳng tay', 'Mạc sâu bao nhóm cơ cẳng tay, phần xa dày lên tạo dây giữ cổ tay.',
                            'Giữ nhóm cơ cẳng tay, cung cấp điểm khởi phát cho một số sợi cơ, và ngăn cách các bao xương-mạc cẳng tay.'),
    'Extensor retinaculum of wrist': ('Dây giữ gân duỗi cổ tay', 'Dải mạc ngang dày ở mu cổ tay, phát ra vách sợi sâu tạo 6 ống xương-sợi.',
                                      'Giữ các gân duỗi ngăn chúng vồng lên như dây cung khi duỗi cổ tay, và ngăn cách các gân giảm ma sát.'),
    'Flexor retinaculum of wrist': ('Dây giữ gân gập cổ tay', 'Tức dây chằng ngang cổ tay, căng ngang hai bên rãnh xương cổ tay tạo nóc ống cổ tay.',
                                    'Giữ các gân gập và tạo ống cổ tay; tăng áp lực trong ống chèn ép thần kinh giữa gây hội chứng ống cổ tay.'),

    # ================= Cơ nội tại bàn tay =================
    'Abductor pollicis brevis': ('Cơ dạng ngón cái ngắn', 'Cơ nông nhất của ô mô cái, khởi phát từ dây chằng ngang cổ tay và xương thuyền, bám vào đốt gần ngón cái.',
                                 'Dạng ngón cái vuông góc với mặt lòng bàn tay, là cơ then chốt đánh giá chức năng thần kinh giữa.'),
    'Superficial head of flexor pollicis brevis': ('Bụng nông của cơ gập ngón cái ngắn', 'Bụng nông khởi phát từ dây chằng ngang cổ tay, được thần kinh giữa chi phối.',
                                                   'Gập khớp bàn-ngón ngón cái và tham gia đối chiếu.'),
    'Deep head of flexor pollicis brevis': ('Bụng sâu của cơ gập ngón cái ngắn', 'Bụng sâu khởi phát từ xương thang và xương cả, được thần kinh trụ chi phối.',
                                            'Gập khớp bàn-ngón ngón cái, cùng bụng nông ổn định gốc ngón cái.'),
    'Opponens pollicis muscle': ('Cơ đối chiếu ngón cái', 'Nằm sâu ở ô mô cái, khởi phát từ dây chằng ngang cổ tay và xương thang, bám vào mặt quay xương bàn tay 1.',
                                 'Làm ngón cái xoay và ngang qua lòng bàn tay đối chiếu với các ngón còn lại, là cơ sở giải phẫu của khả năng nắm của bàn tay người.'),
    'Oblique head of adductor pollicis': ('Bụng chéo của cơ khép ngón cái', 'Bụng khởi phát từ xương cả và nền xương bàn tay 2, 3.',
                                          'Khép ngón cái sát mặt lòng bàn tay, tham gia phát lực kẹp.'),
    'Transverse head of adductor pollicis': ('Bụng ngang của cơ khép ngón cái', 'Bụng hình quạt khởi phát từ mặt lòng xương bàn tay 3.',
                                             'Khép mạnh ngón cái; liệt thần kinh trụ làm cơ này mất chức năng xuất hiện dấu hiệu Froment.'),
    'Abductor digiti minimi of hand': ('Cơ dạng ngón út bàn tay', 'Cơ trong nhất của ô mô út, khởi phát từ xương đậu, bám vào đốt gần ngón út.',
                                       'Dạng ngón út và gập khớp bàn-ngón của nó.'),
    'Flexor digiti minimi of hand': ('Cơ gập ngón út ngắn bàn tay', 'Nằm phía quay của cơ dạng ngón út, khởi phát từ móc xương móc và dây chằng ngang cổ tay.',
                                     'Gập khớp bàn-ngón ngón út.'),
    'Opponens digiti minimi muscle of hand': ('Cơ đối chiếu ngón út bàn tay', 'Cơ sâu của ô mô út, bám vào bờ trụ xương bàn tay 5.',
                                              'Làm xương bàn tay 5 xoay ra trước làm sâu lòng bàn tay, phối hợp đối chiếu với ngón cái hoàn thành động tác cầm cốc.'),
    'Lumbrical muscles of hand': ('Cơ giun bàn tay', 'Bốn cơ hình giun nhỏ khởi phát từ gân cơ gập các ngón sâu, bám vào phía quay mạc gân mu ngón.',
                                  'Gập khớp bàn-ngón đồng thời duỗi khớp gian đốt, làm ngón tay tạo tư thế “tay viết chữ”.'),
    'Palmar interossei muscles': ('Cơ gian xương lòng bàn tay', 'Ba cơ đơn lông chim nằm phía lòng ở khe gian xương bàn tay.',
                                  'Làm ngón 2, 4, 5 khép về phía ngón giữa, và hỗ trợ gập khớp bàn-ngón, duỗi khớp gian đốt.'),
    'Dorsal interossei muscles of hand': ('Cơ gian xương mu bàn tay', 'Bốn cơ kép lông chim lấp đầy phía mu khe gian xương bàn tay.',
                                          'Làm các ngón dạng ra hai bên lấy ngón giữa làm trục; liệt thần kinh trụ teo cơ tạo “bàn tay móng vuốt”.'),
    'Palmar aponeurosis': ('Mạc gan tay', 'Mạc gân dày hình tam giác ở giữa lòng bàn tay, liên tục với gân cơ gan tay dài.',
                           'Bảo vệ cung động mạch nông lòng bàn tay và các gân gập, cố định da lòng bàn tay để thuận lợi nắm; co rút mạc này gây bệnh Dupuytren.'),
    'Dorsal fascia of hand': ('Mạc mu bàn tay', 'Mạc mỏng phủ các gân duỗi mu bàn tay.',
                              'Giữ các gân duỗi và duy trì khả năng trượt của da mu bàn tay.'),
    'Superficial transverse metacarpal ligament': ('Dây chằng ngang nông xương bàn tay', 'Bó sợi nằm ở phần xa mạc gan tay, chạy ngang phía gần kẽ ngón.',
                                                   'Nối phần xa đầu xương bàn tay, ngăn các ngón tách quá mức, bảo vệ bó mạch thần kinh ngón.'),
    'Cruciform part of fibrous sheath of digit of hand': ('Phần chữ thập của bao sợi ngón bàn tay', 'Phần mỏng yếu sắp xếp chữ thập trong bao sợi gân gập ngón (ròng rọc C1–C3).',
                                                          'Nằm ở khớp, cho phép bao sợi gấp lại khi gập ngón mà không cản trở cử động.'),
    'Synovial sheaths of digits of hand': ('Bao hoạt dịch gân ngón bàn tay', 'Ống hoạt dịch hai lớp bao quanh gân gập ngón.',
                                           'Tiết dịch hoạt dịch giảm ma sát khi gân trượt, và qua mạc gân cung cấp máu cho gân.'),

    # ================= Thành ngực bụng =================
    'External intercostal muscles': ('Cơ gian sườn ngoài', 'Nằm lớp nông khe gian sườn, sợi từ trên sau chạy chéo xuống trước.',
                                     'Nâng xương sườn mở rộng lồng ngực, là cơ phụ chính của hít vào yên tĩnh.'),
    'Internal intercostal muscles': ('Cơ gian sườn trong', 'Nằm sâu dưới cơ gian sườn ngoài, hướng sợi vuông góc (từ trên trước chạy chéo xuống sau).',
                                     'Hạ xương sườn thu nhỏ lồng ngực, tham gia thở ra mạnh.'),
    'Innermost intercostal muscles': ('Cơ gian sườn trong cùng', 'Lớp cơ không hoàn chỉnh sâu nhất của khe gian sườn, ngăn cách với cơ gian sườn trong bởi bó mạch thần kinh gian sườn.',
                                      'Phối hợp với cơ gian sườn trong hạ xương sườn; khoảng giữa hai cơ là lớp đích của phong bế thần kinh gian sườn.'),
    'Transversus thoracis muscle': ('Cơ ngang ngực', 'Cơ mỏng tỏa hình quạt ở mặt trong thành trước ngực, khởi phát từ phần dưới xương ức, bám vào sụn sườn 2–6.',
                                    'Kéo sụn sườn xuống hỗ trợ thở ra; phía sau có động mạch ngực trong chạy.'),
    'Diaphragm': ('Cơ hoành', 'Cơ dẹt hình vòm ngăn cách khoang ngực và bụng, phần giữa là gân trung tâm.',
                  'Cơ hô hấp chính nhất, co hạ xuống làm tăng thể tích lồng ngực tạo hít vào; và nhờ tăng áp lực ổ bụng tham gia đại tiện, sinh đẻ và ho.'),
    'Diaphragmatic fascia': ('Mạc cơ hoành', 'Mạc mỏng phủ mặt trên dưới cơ hoành, trên là mạc màng phổi cơ hoành, dưới là mạc dưới cơ hoành.',
                             'Ngăn cách cơ hoành với màng phổi, phúc mạc, là hàng rào lan nhiễm trùng khoang ngực bụng.'),
    'External abdominal oblique muscle': ('Cơ chéo bụng ngoài', 'Cơ dẹt rộng nông nhất thành bụng, sợi từ trên ngoài chạy chéo xuống trong như hướng “bỏ túi”.',
                                          'Co một bên làm thân quay về bên đối diện và nghiêng sang bên, co hai bên gập thân, tăng áp lực ổ bụng; bờ dưới cuộn thành dây chằng bẹn.'),
    'Internal abdominal oblique muscle': ('Cơ chéo bụng trong', 'Nằm sâu dưới cơ chéo bụng ngoài, hướng sợi ngược lại (từ dưới ngoài chạy chéo lên trong).',
                                          'Co một bên làm thân quay về cùng bên, co hai bên gập thân và tăng áp lực ổ bụng.'),
    'Transversus abdominis muscle': ('Cơ ngang bụng', 'Cơ dẹt sâu nhất thành bụng, sợi chạy ngang bao quanh khoang bụng.',
                                     'Như thắt lưng siết chặt thành bụng, tăng áp lực ổ bụng, là cơ then chốt ổn định lõi và thở ra mạnh.'),
    'Rectus abdominis muscle': ('Cơ thẳng bụng', 'Cơ dạng dải chạy dọc hai bên đường giữa thành trước bụng, được 3–4 gân chia thành “sáu múi”.',
                                'Gập trước thân, hạ xương sườn và tăng áp lực ổ bụng, là cơ động lực chính của ngồi dậy.'),
    'Pyramidalis muscle': ('Cơ tháp', 'Cơ hình tam giác nhỏ nằm phía trước đầu dưới cơ thẳng bụng, khoảng 20% người thiếu.',
                           'Căng đường trắng, chức năng yếu.'),
    'Linea alba': ('Đường trắng', 'Dải gân màu trắng chạy dọc đường giữa thành trước bụng do sợi mạc gân hai bên đan xen tạo thành.',
                   'Nối cơ thành bụng hai bên, truyền lực căng; là đường vào của rạch giữa bụng, sau thai kỳ có thể xảy ra tách cơ thẳng bụng.'),
    'Investing abdominal fascia': ('Mạc bao thành bụng', 'Mạc mỏng bao mặt ngoài các lớp cơ dẹt thành bụng.',
                                   'Ngăn cách và giữ các lớp cơ thành bụng, cho phép các lớp trượt tương đối.'),
    'Transversalis fascia': ('Mạc ngang', 'Lớp mạc mỏng dai lót mặt sâu cơ ngang bụng, thuộc một phần mạc trong bụng.',
                             'Tạo vòng sâu ống bẹn, là hàng rào sợi cuối cùng của thành bụng; yếu chỗ này có thể gây thoát vị bẹn thẳng.'),
    'Inguinal ligament': ('Dây chằng bẹn', 'Bờ dưới mạc gân cơ chéo bụng ngoài cuộn ra sau dày lên tạo thành, căng giữa gai chậu trước trên và củ mu.',
                          'Tạo bờ dưới ống bẹn và bờ dưới thành bụng, khoảng mạch và khoảng cơ sâu dưới nó là đường đi của mạch thần kinh chi dưới.'),
    'Iliopectineal arch': ('Cung chậu-mu', 'Bó sợi từ mặt sâu dây chằng bẹn nối đến ụ chậu-mu.',
                           'Chia khoảng sâu dưới dây chằng bẹn thành khoảng cơ phía ngoài và khoảng mạch phía trong.'),
    'Anterior layer of thoracolumbar fascia': ('Lớp trước của mạc ngực-thắt lưng', 'Lớp mạc nằm phía trước cơ vuông thắt lưng.',
                                               'Cùng lớp giữa, sau bao nhóm cơ sâu thắt lưng, lên trên dày tạo dây chằng cung ngoài.'),
    'Middle layer of thoracolumbar fascia': ('Lớp giữa của mạc ngực-thắt lưng', 'Lớp mạc nằm giữa cơ dựng sống và cơ vuông thắt lưng.',
                                             'Ngăn cách cơ dựng sống với cơ vuông thắt lưng, và cung cấp điểm khởi phát cho cơ ngang bụng.'),
    'Posterior layer of thoracolumbar fascia': ('Lớp sau của mạc ngực-thắt lưng', 'Mạc chắc phủ mặt sau cơ dựng sống, hòa vào mạc gân cơ lưng rộng.',
                                                'Bao cơ dựng sống tạo bao xương-mạc, truyền lực căng của cơ lưng rộng và cơ mông lớn qua thân.'),

    # ================= Đáy chậu =================
    'Coccygeus muscle': ('Cơ cụt', 'Cơ hình tam giác nằm phía sau cơ nâng hậu môn, phủ mặt trên dây chằng cùng-gai.',
                         'Nâng đỡ tạng khoang chậu, và kéo xương cụt ra trước về vị trí.'),
    'Iliococcygeus muscle': ('Cơ chậu-cụt', 'Phần sau ngoài của cơ nâng hậu môn, khởi phát từ cung gân cơ nâng hậu môn, bám vào xương cụt và dây chằng hậu môn-cụt.',
                             'Tạo phần chính của cơ hoành chậu, nâng đỡ tạng khoang chậu và chống lại tăng áp lực ổ bụng.'),
    'Pubococcygeus muscle': ('Cơ mu-cụt', 'Phần trong của cơ nâng hậu môn, khởi phát từ mặt sau xương mu, vòng quanh tạng khoang chậu bám vào xương cụt.',
                             'Khi co nâng và siết chặt đáy chậu, kiểm soát tiểu tiện đại tiện; là cơ đích của bài tập Kegel.'),
    'Pubo-analis muscle': ('Cơ mu-hậu môn', 'Phần của cơ mu-cụt bám vào thành ống hậu môn và da hậu môn.',
                           'Nâng ống hậu môn, duy trì góc trực tràng-hậu môn, là mắt xích quan trọng của kiểm soát đại tiện.'),
    'External anal sphincter': ('Cơ thắt ngoài hậu môn', 'Cơ vân bao quanh đoạn dưới ống hậu môn, chia phần dưới da, nông và sâu.',
                                'Được ý thức kiểm soát đóng chặt hậu môn tùy ý, là then chốt duy trì tự chủ đại tiện.'),
    'Tendinous arch of levator ani': ('Cung gân cơ nâng hậu môn', 'Dải dày dạng đường trên mặt mạc bịt từ xương mu đến gai ngồi.',
                                      'Cung cấp điểm khởi phát cho cơ nâng hậu môn, neo lực căng của cơ đáy chậu vào thành bên khung chậu.'),

    # ================= Hông =================
    'Psoas major': ('Cơ thắt lưng lớn', 'Cơ dài hình thoi khởi phát từ mặt bên thân và mỏm ngang đốt sống thắt lưng, đi dưới dây chằng bẹn bám vào mấu chuyển nhỏ xương đùi.',
                    'Cơ gập háng mạnh nhất; khi chi dưới cố định làm thân gập trước, cùng cơ chậu gọi là cơ chậu-thắt lưng.'),
    'Iliacus muscle': ('Cơ chậu', 'Cơ hình quạt lấp đầy hố chậu, cùng gân cơ thắt lưng lớn bám vào mấu chuyển nhỏ xương đùi.',
                       'Gập và xoay ngoài đùi, khi bước đi nâng đùi ra trước.'),
    'Iliopsoas fascia': ('Mạc chậu-thắt lưng', 'Mạc bao cơ thắt lưng lớn và cơ chậu, tiếp tục xuống thành sau bao đùi.',
                         'Bao cơ chậu-thắt lưng tạo bao; mủ lao cột sống thắt lưng có thể theo bao này chảy xuống gốc đùi.'),
    'Quadratus lumborum muscle': ('Cơ vuông thắt lưng', 'Cơ sâu hình vuông thành sau bụng, nối mào chậu, xương sườn 12 và mỏm ngang đốt sống thắt lưng.',
                                  'Nghiêng sang bên cột sống thắt lưng, cố định xương sườn 12 ổn định điểm bám cơ hoành, là cơ quan trọng duy trì khung chậu ngang khi đứng.'),
    'Gluteus maximus muscle': ('Cơ mông lớn', 'Một trong các cơ lớn và nông nhất cơ thể, khởi phát từ đường mông sau xương chậu, xương cùng cụt, bám vào dải chậu-chày và ụ cơ mông.',
                               'Duỗi mạnh háng và xoay ngoài đùi; phát lực khi lên cầu thang, đứng dậy và chạy nhảy, cũng là cơ then chốt duy trì tư thế thẳng.'),
    'Gluteus medius muscle': ('Cơ mông giữa', 'Nằm sâu dưới cơ mông lớn, khởi phát từ mặt ngoài cánh xương chậu, bám vào mấu chuyển lớn xương đùi.',
                              'Dạng đùi; khi đứng một chân giữ khung chậu ở vị trí ngang, yếu cơ biểu hiện dáng đi Trendelenburg.'),
    'Gluteus minimus muscle': ('Cơ mông nhỏ', 'Cơ hình quạt sâu dưới cơ mông giữa, bám vào bờ trước mấu chuyển lớn xương đùi.',
                               'Phối hợp với cơ mông giữa dạng và xoay trong đùi, ổn định khung chậu khi đi.'),
    'Tensor fasciae latae': ('Cơ căng mạc đùi', 'Cơ ngắn nằm ở phía trên ngoài đùi, bao giữa hai lớp mạc đùi.',
                             'Căng dải chậu-chày, hỗ trợ gập háng và dạng, ổn định khớp gối duỗi.'),
    'Piriformis muscle': ('Cơ hình lê', 'Cơ hình lê khởi phát từ mặt trước xương cùng, xuyên lỗ ngồi lớn bám vào mấu chuyển lớn xương đùi.',
                          'Xoay ngoài và dạng đùi ở tư thế gập; thần kinh ngồi thường đi ra dưới cơ này, co thắt cơ có thể gây hội chứng cơ hình lê.'),
    'Piriformis fascia': ('Mạc cơ hình lê', 'Mạc bao mặt ngoài cơ hình lê.',
                          'Giữ cơ hình lê, liên tục với bao thần kinh đám rối cùng.'),
    'Superior gemellus muscle': ('Cơ sinh đôi trên', 'Cơ nhỏ khởi phát từ gai ngồi, hợp với gân cơ bịt trong bám vào hố mấu chuyển xương đùi.',
                                 'Xoay ngoài đùi và ổn định phía sau khớp háng.'),
    'Inferior gemellus muscle': ('Cơ sinh đôi dưới', 'Khởi phát từ phần trên ụ ngồi, hợp với gân cơ bịt trong.',
                                 'Xoay ngoài đùi, cùng cơ sinh đôi trên mở rộng cánh tay đòn của cơ bịt trong.'),
    'Obturator internus': ('Cơ bịt trong', 'Khởi phát từ mặt trong màng bịt, gân gập góc vuông quanh khuyết ngồi nhỏ rồi bám vào hố mấu chuyển.',
                           'Xoay ngoài đùi; mặt xương ở khuyết ngồi nhỏ đóng vai trò ròng rọc thay đổi hướng lực.'),
    'Obturator externus': ('Cơ bịt ngoài', 'Cơ sâu khởi phát từ mặt ngoài màng bịt, vòng quanh phía sau cổ xương đùi bám vào hố mấu chuyển.',
                           'Xoay ngoài đùi và ổn định chỏm xương đùi trong ổ cối từ phía dưới.'),
    'Quadratus femoris muscle': ('Cơ vuông đùi', 'Cơ hình vuông nối ụ ngồi với mào gian mấu chuyển xương đùi.',
                                 'Xoay ngoài mạnh đùi và ổn định khớp háng.'),

    # ================= Đùi =================
    'Sartorius muscle': ('Cơ may', 'Cơ dài nhất cơ thể, từ gai chậu trước trên chạy chéo qua mặt trước đùi bám vào mặt trong đầu trên xương chày.',
                         'Gập háng, gập gối và xoay ngoài đùi, tức tổ hợp động tác ngồi xếp bằng.'),
    'Rectus femoris muscle': ('Cơ thẳng đùi', 'Bụng duy nhất của cơ tứ đầu đùi bắt chéo khớp háng, khởi phát từ gai chậu trước dưới.',
                              'Duỗi gối và gập háng; dễ bị căng nhất trong động tác duỗi háng gập gối như đá bóng.'),
    'Vastus lateralis muscle': ('Cơ rộng ngoài', 'Bụng lớn nhất của cơ tứ đầu đùi, khởi phát từ môi ngoài đường ráp xương đùi và mấu chuyển lớn.',
                                'Duỗi gối; vì bụng cơ dày lớn và xa mạch thần kinh chính, là vị trí tiêm bắp thường dùng.'),
    'Vastus medialis muscle': ('Cơ rộng trong', 'Khởi phát từ môi trong đường ráp xương đùi, sợi dưới chạy chéo bám vào bờ trên trong xương bánh chè.',
                               'Duỗi gối và kéo xương bánh chè vào trong, ngăn trật ra ngoài.'),
    'Vastus intermedius muscle': ('Cơ rộng giữa', 'Cơ dẹt nằm sâu dưới cơ thẳng đùi, bám trực tiếp mặt trước thân xương đùi.',
                                  'Duỗi gối; một số sợi sâu tạo cơ khớp gối, khi duỗi gối nâng bao khớp ngăn bị kẹp.'),
    'Pectineus muscle': ('Cơ lược', 'Cơ dẹt hình vuông ở phần trên trong đùi, khởi phát từ mào mu, bám vào đường cơ lược xương đùi.',
                         'Khép và gập đùi, tạo đáy của tam giác đùi.'),
    'Adductor longus': ('Cơ khép dài', 'Cơ khép nông nhất mặt trong đùi, khởi phát từ mặt trước thân xương mu, bám vào 1/3 giữa đường ráp xương đùi.',
                        'Khép và gập đùi; là cơ thường bị ảnh hưởng nhất trong “căng cơ khép”.'),
    'Adductor brevis': ('Cơ khép ngắn', 'Cơ hình tam giác nằm sâu dưới cơ khép dài, khởi phát từ ngành dưới xương mu.',
                        'Khép và hơi gập, xoay ngoài đùi; nhánh trước sau thần kinh bịt lần lượt đi xuống mặt trước sau cơ này.'),
    'Adductor magnus': ('Cơ khép lớn', 'Cơ lớn nhất nhóm khép, khởi phát từ ngành ngồi và ụ ngồi, bám rộng vào đường ráp và củ khép xương đùi.',
                        'Khép mạnh đùi; phần ngồi có thêm tác dụng duỗi háng, lỗ gân dưới (lỗ gân khép) là đường mạch đùi vào hố khoeo.'),
    '(Adductor minimus)': ('Cơ khép nhỏ', 'Bó thường tách riêng từ phần trên cơ khép lớn, có tính biến đổi.',
                           'Khép và xoay ngoài đùi.'),
    'Gracilis muscle': ('Cơ thon', 'Cơ dài dạng dải trong nhất đùi, khởi phát từ ngành dưới xương mu, bám vào mặt trong đầu trên xương chày.',
                        'Khép đùi, gập gối và xoay trong cẳng chân; vì chức năng có thể được thay thế, thường được lấy làm gân hoặc vạt cơ có cuống để ghép.'),
    'Long head of biceps femoris': ('Bụng dài cơ nhị đầu đùi', 'Một trong các cơ gân kheo, khởi phát từ ụ ngồi, cùng cơ bán gân khởi phát chung.',
                                    'Duỗi háng, gập gối và xoay ngoài cẳng chân, là cơ dễ bị căng nhất giai giai giai đoạn tăng tốc chạy.'),
    'Short head of biceps femoris': ('Bụng ngắn cơ nhị đầu đùi', 'Khởi phát từ môi ngoài đường ráp xương đùi, là cơ gân kheo duy nhất không bắt chéo khớp háng.',
                                     'Gập gối và xoay ngoài cẳng chân; được thần kinh mác chung chi phối, khác với các cơ gân kheo khác (thần kinh chày).'),
    'Semitendinosus muscle': ('Cơ bán gân', 'Một trong các cơ gân kheo, bụng cơ ngắn nửa dưới là gân dài, bám vào mặt trong đầu trên xương chày (chân ngỗng).',
                              'Duỗi háng, gập gối và xoay trong cẳng chân; gân của nó là vật liệu ghép thường dùng nhất để tái tạo dây chằng chéo trước.'),
    'Semimembranosus muscle': ('Cơ bán mạc', 'Nằm sâu dưới cơ bán gân, nửa trên là mạc gân rộng dẹt, bám vào mặt sau lồi cầu trong xương chày.',
                               'Duỗi háng, gập gối và xoay trong cẳng chân, đồng thời tăng cường ổn định phía sau trong khớp gối.'),
    'Fascia lata': ('Mạc đùi', 'Mạc sâu chắc bao toàn bộ nhóm cơ đùi, là mạc sâu dày nhất cơ thể.',
                    'Giữ nhóm cơ đùi, hỗ trợ hồi lưu tĩnh mạch; phần ngoài dày tạo dải chậu-chày, lỗ tĩnh mạch hiển phía trước trên là lối vào của tĩnh mạch hiển lớn.'),
    'Iliotibial tract': ('Dải chậu-chày', 'Dải sợi dọc dày rõ ở phía ngoài mạc đùi, trên nối cơ mông lớn và cơ căng mạc đùi, dưới bám vào lồi cầu ngoài xương chày.',
                         'Ổn định phía ngoài khớp gối duỗi, truyền lực cơ mông; ma sát với mỏm trên lồi cầu ngoài xương đùi khi chạy có thể gây hội chứng dải chậu-chày.'),
    'Medial patellar retinaculum': ('Dây giữ trong xương bánh chè', 'Dải sợi mạc gân cơ rộng trong kéo dài xuống, vượt bờ trong xương bánh chè bám vào xương chày.',
                                    'Truyền lực duỗi gối vòng qua xương bánh chè trực tiếp đến xương chày, và ngăn xương bánh chè trật ra ngoài.'),
    'Lateral patellar retinaculum': ('Dây giữ ngoài xương bánh chè', 'Dải sợi mạc gân cơ rộng ngoài và dải chậu-chày kéo dài xuống bám vào phía ngoài xương chày.',
                                     'Hỗ trợ truyền lực duỗi gối và ổn định xương bánh chè; quá căng là nguyên nhân của hội chứng tăng áp lực ngoài xương bánh chè.'),
    'Popliteal fascia': ('Mạc khoeo', 'Mạc dày chắc do mạc đùi tiếp tục dày lên ở phía sau hố khoeo.',
                         'Phủ và bảo vệ mạch thần kinh trong hố khoeo, thiếu đàn hồi khiến nang hố khoeo dễ phình xuống dưới.'),
    'Medial femoral intermuscular septum': ('Vách gian cơ trong đùi', 'Tấm sợi từ mặt sâu mạc đùi bám vào môi trong đường ráp xương đùi.',
                                            'Ngăn cách nhóm cơ trước đùi với nhóm khép, tạo thành trước của ống khép.'),
    'Lateral femoral intermuscular septum': ('Vách gian cơ ngoài đùi', 'Tấm sợi chắc bám vào môi ngoài đường ráp xương đùi.',
                                             'Ngăn cách nhóm cơ trước và sau đùi, là vách gian cơ dày nhất.'),

    # ================= Cẳng chân =================
    'Tibialis anterior muscle': ('Cơ chày trước', 'Cơ mạnh nhất nhóm trước cẳng chân phía trong, khởi phát từ mặt ngoài xương chày, bám vào xương chêm trong và nền xương bàn chân 1.',
                                 'Gập mu cổ chân và lật trong bàn chân; nâng đầu ngón chân ở giai đoạn vung chân khi đi, liệt biểu hiện bàn chân rũ.'),
    'Extensor hallucis longus': ('Cơ duỗi ngón cái dài', 'Nằm giữa cơ chày trước và cơ duỗi các ngón dài, bám vào nền đốt xa ngón cái.',
                                 'Duỗi ngón cái và hỗ trợ gập mu cổ chân với lật trong bàn chân.'),
    'Extensor digitorum longus': ('Cơ duỗi các ngón dài', 'Cơ lông chim phía ngoài nhóm trước cẳng chân, bằng bốn gân bám vào mạc gân mu ngón 2–5.',
                                  'Duỗi ngón 2–5 và gập mu cổ chân.'),
    'Tendon of extensor digitorum longus': ('Gân cơ duỗi các ngón dài', 'Bốn gân dẹt do cơ duỗi các ngón dài tách ra ở mu bàn chân.',
                                            'Truyền lực duỗi ngón đến mạc gân mu từng ngón, nhìn rõ dưới da mu bàn chân.'),
    'Fibularis tertius muscle': ('Cơ mác thứ ba', 'Cơ nhỏ tách từ phần dưới ngoài cơ duỗi các ngón dài, bám vào nền xương bàn chân 5, khoảng 10% người thiếu.',
                                 'Gập mu cổ chân và lật ngoài bàn chân.'),
    'Fibularis longus muscle': ('Cơ mác dài', 'Cơ dài nông nhất mặt ngoài cẳng chân, gân vòng quanh phía sau mắt cá ngoài và ngang qua lòng bàn chân bám vào xương chêm trong và nền xương bàn chân 1.',
                                'Lật ngoài và gập lòng bàn chân; đường đi ngang lòng bàn chân duy trì vòm ngang và vòm dọc trong bàn chân.'),
    'Fibularis brevis muscle': ('Cơ mác ngắn', 'Nằm sâu dưới cơ mác dài, bám vào ụ xương bàn chân 5.',
                                'Lật ngoài bàn chân và hỗ trợ gập lòng; khi bàn chân lật trong quá mức lực kéo của cơ có thể gây gãy bong điểm bám nền xương bàn chân 5.'),
    'Lateral head of gastrocnemius': ('Bụng ngoài cơ sinh đôi', 'Bụng cơ khởi phát từ phía trên lồi cầu ngoài xương đùi.',
                                      'Gập lòng cổ chân và gập gối, là nguồn lực bùng nổ của đi và nhảy.'),
    'Medial head of gastrocnemius': ('Bụng trong cơ sinh đôi', 'Khởi phát từ phía trên lồi cầu trong xương đùi, to hơn bụng ngoài.',
                                     'Gập lòng cổ chân và gập gối, tạo chỗ lồi phía trong bụng chân.'),
    'Soleus muscle': ('Cơ dép', 'Cơ dẹt rộng nằm sâu dưới cơ sinh đôi, khởi phát từ mặt sau xương chày-mác, không bắt chéo khớp gối.',
                      'Gập lòng cổ chân; giàu sợi chậm, là cơ chính duy trì tư thế khi đứng, co cơ còn có tác dụng “bơm cơ cẳng chân” hỗ trợ hồi lưu tĩnh mạch.'),
    'Calcaneal tendon': ('Gân gót', 'Do gân cơ sinh đôi và cơ dép hợp thành, bám vào củ xương gót, là gân thô và mạnh nhất cơ thể.',
                         'Truyền lực cơ ba đầu cẳng chân đến xương gót hoàn thành động tác đẩy đất; cũng là gân thường xảy ra đứt tự phát nhất toàn thân.'),
    'Plantaris muscle': ('Cơ gan chân', 'Cơ thoái hóa bụng nhỏ gân cực dài mảnh, khởi phát từ mỏm trên lồi cầu ngoài xương đùi, bám vào xương gót.',
                         'Hỗ trợ yếu gập gối và gập lòng; thường được lấy làm vật liệu ghép gân.'),
    'Popliteus muscle': ('Cơ khoeo', 'Cơ hình tam giác nhỏ sâu phía sau khớp gối, khởi phát từ lồi cầu ngoài xương đùi, bám vào phần trên mặt sau xương chày.',
                         'Mở khóa khớp gối duỗi hoàn toàn (làm xương chày xoay trong) để khởi động gập gối, và kéo sụn chêm ngoài tránh bị kẹp.'),
    'Tibialis posterior muscle': ('Cơ chày sau', 'Cơ sâu nhất nhóm sau cẳng chân, gân đi phía sau mắt cá trong bám vào xương thuyền và xương chêm.',
                                  'Lật trong và gập lòng bàn chân; là cơ quan trọng nhất duy trì vòm dọc trong bàn chân, suy chức năng có thể gây bàn chân bẹt mắc phải ở người lớn.'),
    'Flexor digitorum longus': ('Cơ gập các ngón dài', 'Cơ phía trong lớp sâu nhóm sau cẳng chân, gân ở lòng bàn chân chia bốn bám vào đốt xa ngón 2–5.',
                                'Gập ngón 2–5 và gập lòng cổ chân, hỗ trợ lật trong bàn chân, bám chặt mặt đất ở giai đẩy khi đi.'),
    'Flexor hallucis longus': ('Cơ gập ngón cái dài', 'Cơ mạnh nhất lớp sâu nhóm sau cẳng chân, gân đi dưới mấu chống đỡ phía sau xương gót bám vào đốt xa ngón cái.',
                               'Gập ngón cái và gập lòng cổ chân; cung cấp lực đẩy cuối cùng ở giai đẩy khi đi.'),
    'Crural fascia': ('Mạc cẳng chân', 'Mạc sâu chắc bao nhóm cơ cẳng chân, liên kết chặt với màng xương chày.',
                      'Giữ nhóm cơ cẳng chân, hỗ trợ hồi lưu tĩnh mạch; đặc và thiếu đàn hồi khiến cẳng chân là vị trí cao của hội chứng khoang xương-mạc.'),
    'Anterior intermuscular septum of leg': ('Vách gian cơ trước cẳng chân', 'Vách sợi từ mặt sâu mạc cẳng chân nối đến bờ trước xương mác.',
                                             'Ngăn cách nhóm trước với nhóm ngoài cẳng chân, tạo bờ ngoài của bao xương-mạc trước.'),
    'Posterior intermuscular septum of leg': ('Vách gian cơ sau cẳng chân', 'Vách sợi nối đến bờ sau xương mác.',
                                              'Ngăn cách nhóm ngoài với nhóm sau cẳng chân.'),
    'Transverse intermuscular septum of leg': ('Vách gian cơ ngang cẳng chân', 'Tấm mạc chạy ngang vùng sau cẳng chân, ngăn cách lớp gập nông sâu.',
                                               'Chia bao xương-mạc sau cẳng chân thành hai khoang nông sâu, tăng áp lực trong khoang sâu triệu chứng nguy hiểm nhất.'),
    'Superior extensor retinaculum of ankle': ('Dây chằng ngang cẳng chân', 'Dây giữ gân duỗi chạy ngang phía trên trước cổ chân.',
                                               'Giữ các gân nhóm trước cẳng chân ngăn chúng vồng lên khi gập mu.'),
    'Inferior extensor retinaculum of ankle': ('Dây chằng chữ thập cẳng chân', 'Dây giữ gân duỗi hình chữ Y ở phía trước cổ chân.',
                                               'Cố định các gân duỗi mu bàn chân và ngăn cách đường trượt của chúng.'),
    'Superior fibular retinaculum': ('Dây giữ cơ mác trên', 'Dải sợi phía dưới sau mắt cá ngoài.',
                                     'Giữ gân cơ mác dài ngắn trong rãnh sau mắt cá ngoài, ngăn trật ra trước.'),
    'Inferior fibular retinaculum': ('Dây giữ cơ mác dưới', 'Dải sợi mặt ngoài xương gót, liên tục với dây chằng chữ thập cẳng chân.',
                                     'Ngăn cách và cố định gân cơ mác dài ngắn ở mặt ngoài xương gót.'),
    'Flexor retinaculum of ankle': ('Dây giữ gân gập cổ chân', 'Dải sợi chắc giữa mắt cá trong và xương gót, tức dây chằng chẻ.',
                                    'Cùng mặt trong xương gót tạo ống cổ chân; thần kinh chày bị chèn ép tại đây gây hội chứng ống cổ chân.'),

    # ================= Cơ nội tại bàn chân =================
    'Abductor hallucis': ('Cơ dạng ngón cái', 'Cơ nông nhất phía trong lòng bàn chân, khởi phát từ mấu trong củ xương gót, bám vào đốt gần ngón cái.',
                          'Dạng và gập ngón cái, là cấu trúc động lực quan trọng duy trì vòm dọc trong bàn chân.'),
    'Flexor digitorum brevis': ('Cơ gập các ngón ngắn', 'Cơ lớp giữa lòng bàn chân, khởi phát từ củ xương gót, bằng bốn gân chẻ bám vào đốt giữa ngón 2–5.',
                                'Gập khớp gian đốt gần ngón 2–5, khi đi nắm ngón vào mặt đất.'),
    'Abductor digiti minimi of foot': ('Cơ dạng ngón út bàn chân', 'Cơ dài ở bờ ngoài lòng bàn chân, khởi phát từ củ xương gót, bám vào đốt gần ngón út.',
                                       'Dạng và gập ngón út, ổn định bờ ngoài bàn chân.'),
    'Quadratus plantae muscle': ('Cơ vuông lòng bàn chân', 'Cơ hình vuông lớp hai lòng bàn chân, khởi phát từ xương gót, bám vào gân cơ gập các ngón dài.',
                                 'Hiệu chỉnh hướng kéo chéo của gân cơ gập các ngón dài, cho phép các ngón gập thẳng.'),
    'Lumbrical muscles of foot': ('Cơ giun bàn chân', 'Bốn cơ nhỏ khởi phát từ gân cơ gập các ngón dài, bám vào mạc gân mu ngón 2–5.',
                                  'Gập khớp bàn-ngón đồng thời duỗi khớp gian đốt, làm ngón chân sát mặt đất tăng diện tích chống đỡ.'),
    'Flexor digiti minimi of foot': ('Cơ gập ngón út ngắn bàn chân', 'Cơ nhỏ khởi phát từ nền xương bàn chân 5, bám vào đốt gần ngón út.',
                                     'Gập khớp bàn-ngón ngón út.'),
    '(Opponens digiti minimi muscle of foot)': ('Cơ đối chiếu ngón út bàn chân', 'Bó cơ biến đổi thường tách từ phần sâu cơ gập ngón út ngắn, bám vào xương bàn chân 5.',
                                                'Làm xương bàn chân 5 hơi khép, làm sâu vòm ngang lòng bàn chân.'),
    'Oblique head of adductor hallucis': ('Bụng chéo của cơ khép ngón cái', 'Bụng chạy chéo khởi phát từ nền xương bàn chân 2–4.',
                                          'Khép ngón cái và duy trì vòm ngang bàn chân.'),
    'Transverse head of adductor hallucis': ('Bụng ngang của cơ khép ngón cái', 'Bó hẹp chạy ngang nối bao khớp bàn-ngón 3–5.',
                                             'Kéo các đầu xương bàn chân lại gần, là then chốt duy trì vòm ngang bàn chân; yếu cơ liên quan đến sự xuất hiện của ngón cái vẹo ngoài.'),
    'Lateral head of flexor hallucis brevis': ('Bụng ngoài của cơ gập ngón cái ngắn', 'Bụng bám vào mặt ngoài nền đốt gần ngón cái, chứa xương vừng.',
                                               'Gập khớp bàn-ngón ngón cái, xương vừng bên trong chịu áp lực ở giai đoạn đẩy.'),
    'Medial head of flexor hallucis brevis': ('Bụng trong của cơ gập ngón cái ngắn', 'Bụng bám vào mặt trong nền đốt gần ngón cái, chứa xương vừng.',
                                              'Gập khớp bàn-ngón ngón cái và ổn định phía dưới đầu xương bàn chân 1.'),
    'Extensor digitorum brevis': ('Cơ duỗi các ngón ngắn', 'Cơ duy nhất ở mu bàn chân, khởi phát từ phía trước ngoài xương gót, bám vào ngón 2–4.',
                                  'Hỗ trợ duỗi ngón 2–4, tạo chỗ lồi mô mềm có thể sờ thấy ở phía trước ngoài cổ chân.'),
    'Extensor hallucis brevis': ('Cơ duỗi ngón cái ngắn', 'Phần độc lập trong cùng của cơ duỗi các ngón ngắn, bám vào đốt gần ngón cái.',
                                 'Duỗi khớp bàn-ngón ngón cái.'),
    'Dorsal interossei muscles of foot': ('Cơ gian xương mu bàn chân', 'Bốn cơ kép lông chim lấp đầy phía mu khe gian xương bàn chân.',
                                          'Dạng các ngón lấy ngón 2 làm trục, và gập khớp bàn-ngón, duỗi khớp gian đốt.'),
    'Plantar interossei muscles': ('Cơ gian xương lòng bàn chân', 'Ba cơ đơn lông chim nằm phía lòng khe gian xương bàn chân 3–5.',
                                   'Làm ngón 3–5 khép về phía ngón 2, ổn định bàn chân trước.'),
    'Plantar aponeurosis': ('Mạc gan chân', 'Mạc gân chắc ở giữa lòng bàn chân từ củ xương gót tỏa hình quạt đến các ngón.',
                            'Như dây cung duy trì vòm dọc bàn chân, ở giai đoạn đẩy căng vòm bàn chân qua “cơ chế tời”; tổn thương chỗ bám xương gót gây viêm mạc gan chân.'),
    'Superficial transverse metatarsal ligament': ('Dây chằng ngang nông xương bàn chân', 'Bó sợi chạy ngang phía gần kẽ ngón, nối các đầu xương bàn chân.',
                                                   'Ngăn các ngón tách quá mức, bảo vệ bó mạch thần kinh ngón.'),

    # ================= Bao gân =================
    'Common flexor tendon sheath': ('Bao gân gập chung', 'Túi hoạt dịch lớn trong ống cổ tay bao quanh gân cơ gập các ngón nông sâu, tức túi trụ.',
                                    'Bôi trơn sự trượt của chín gân trong ống cổ tay; nhiễm trùng có thể lan theo bao này giữa lòng bàn tay và cẳng tay.'),
    'Intertubercular tendon sheath': ('Bao gân gian củ', 'Bao hoạt dịch bao quanh gân bụng dài cơ nhị đầu cánh tay, nằm trong rãnh gian củ xương cánh tay.',
                                      'Giảm ma sát khi gân dài trượt trong rãnh; viêm là nguyên nhân thường gặp của đau trước vai.'),
    'Tendon sheath - abd. pollicis longus - ext. pollicis brevis':
        ('Bao gân cơ dạng ngón cái dài và cơ duỗi ngón cái ngắn', 'Bao hoạt dịch chung bao quanh gân cơ dạng ngón cái dài và cơ duỗi ngón cái ngắn trong ống xương-sợi thứ nhất mu cổ tay.',
         'Bôi trơn sự trượt của hai gân; bao này hẹp dày gây viêm bao gân hẹp mỏm trâm quay (bệnh de Quervain).'),
    'Tendon sheath of extensors carpi radialis': ('Bao gân cơ duỗi cổ tay quay', 'Bao hoạt dịch trong ống thứ hai mu cổ tay bao quanh gân cơ duỗi cổ tay quay dài ngắn.',
                                                  'Giảm ma sát của hai gân với mặt lưng xương quay khi duỗi cổ tay.'),
    'Tendon sheath of extensor pollicis longus': ('Bao gân cơ duỗi ngón cái dài', 'Bao hoạt dịch trong ống thứ ba mu cổ tay, vòng quanh củ lưng xương quay.',
                                                  'Bôi trơn sự trượt chuyển hướng của gân cơ duỗi ngón cái dài; sau gãy đầu xa xương quay dễ xảy ra đứt gân muộn tại đây.'),
    'Tendon sheath of extensor digitorum and extensor indicis':
        ('Bao gân cơ duỗi các ngón và cơ duỗi ngón trỏ', 'Bao hoạt dịch chung trong ống thứ tư mu cổ tay bao quanh gân cơ duỗi các ngón và cơ duỗi ngón trỏ.',
         'Giảm ma sát khi nhiều gân trượt song song khi duỗi ngón.'),
    'Tendon sheath of extensor digiti minimi manus': ('Bao gân cơ duỗi ngón út bàn tay', 'Bao hoạt dịch trong ống thứ năm mu cổ tay bao quanh gân cơ duỗi ngón út.',
                                                      'Bôi trơn sự trượt của gân cơ duỗi ngón út khi vượt qua khớp trụ-quay dưới.'),
    'Tendon sheath of extensor carpi ulnaris': ('Bao gân cơ duỗi cổ tay trụ', 'Bao hoạt dịch trong ống thứ sáu mu cổ tay, nằm trong rãnh lưng đầu xương trụ.',
                                                'Cố định và bôi trơn gân cơ duỗi cổ tay trụ, là nguồn thường gặp của đau phía trụ cổ tay.'),
    'Tendon sheath of flexor carpi radialis': ('Bao gân cơ gập cổ tay quay', 'Bao hoạt dịch bao quanh đoạn gân cơ gập cổ tay quay đi qua rãnh xương thang.',
                                               'Bôi trơn sự trượt của gân này trong rãnh xương ở cổ tay.'),
    'Tendon sheath of flexor pollicis longus': ('Bao gân cơ gập ngón cái dài', 'Bao hoạt dịch bao quanh gân cơ gập ngón cái dài từ ống cổ tay đến đốt xa ngón cái, tức túi quay.',
                                                'Bôi trơn sự trượt toàn bộ của gân gập ngón cái; nhiễm trùng có thể lan theo bao này ra cẳng tay.'),
    'Tendon sheath of tibialis anterior': ('Bao gân cơ chày trước', 'Bao hoạt dịch bao quanh gân cơ chày trước ở phía trước cổ chân.',
                                           'Giảm ma sát khi gân trượt dưới dây giữ gân duỗi.'),
    'Tendon sheath of extensor hallucis longus': ('Bao gân cơ duỗi ngón cái dài', 'Bao hoạt dịch bao quanh gân cơ duỗi ngón cái dài ở phía trước cổ chân.',
                                                  'Bôi trơn sự trượt của gân khi đi qua dây giữ gân duỗi.'),
    'Tendon sheath of extensor digitorum longus': ('Bao gân cơ duỗi các ngón dài', 'Bao hoạt dịch bao quanh gân cơ duỗi các ngón dài ở phía trước ngoài cổ chân.',
                                                   'Giảm ma sát khi bốn gân duỗi ngón trượt song song.'),
    'Tendon sheath of tibialis posterior muscle': ('Bao gân cơ chày sau', 'Bao hoạt dịch bao quanh gân cơ chày sau ở phía sau mắt cá trong.',
                                                   'Bôi trơn sự trượt chuyển hướng của gân quanh mắt cá trong; viêm bao gân tại đây là biểu hiện sớm của bàn chân bẹt.'),
    'Tendon sheath of flexor digitorum longus': ('Bao gân cơ gập các ngón dài', 'Bao hoạt dịch bao quanh gân cơ gập các ngón dài trong ống cổ chân.',
                                                 'Giảm ma sát khi gân chuyển hướng qua phía sau mắt cá trong.'),
    'Tendon sheath of flexor hallucis longus': ('Bao gân cơ gập ngón cái dài', 'Bao hoạt dịch bao quanh gân cơ gập ngón cái dài đi qua phía sau xương gót và dưới mấu chống đỡ.',
                                                'Bôi trơn sự trượt khoảng cách dài của gân trong ống xương-sợi.'),
    'Common tendon sheath of fibularis muscles': ('Bao gân chung cơ mác', 'Bao hoạt dịch chung bao quanh gân cơ mác dài ngắn ở phía sau mắt cá ngoài.',
                                                  'Bôi trơn sự trượt chuyển hướng của hai gân quanh mắt cá ngoài, và giữ chúng trong rãnh xương.'),
    'Plantar tendon sheath of fibularis longus muscle': ('Bao gân lòng bàn chân của cơ mác dài', 'Bao hoạt dịch bao quanh đoạn gân cơ mác dài ngang qua lòng bàn chân.',
                                                         'Giảm ma sát khi gân trượt trong rãnh xương hộp.'),
}


# ---------- Túi hoạt dịch: vị trí khác nhau, tác dụng tương tự, thống nhất tạo theo "vị trí + tác dụng" ----------
_BURSAE = {
    'Subacromial bursa': ('Túi dưới mỏm cùng vai', 'giữa mỏm cùng vai và gân cơ trên gai'),
    'Subdeltoid bursa': ('Túi dưới cơ delta', 'giữa mặt sâu cơ delta và củ lớn xương cánh tay, thường thông với túi dưới mỏm cùng vai'),
    'Subcutaneous acromial bursa': ('Túi dưới da mỏm cùng vai', 'dưới da mặt ngoài mỏm cùng vai'),
    'Coracobrachial bursa': ('Túi quạ-cánh tay', 'giữa mỏm quạ và gân cơ dưới vai'),
    'Subtendinous bursa of infraspinatus muscle': ('Túi dưới gân cơ dưới gai', 'giữa gân cơ dưới gai và bao khớp vai'),
    'Subtendinous bursa of teres major muscle': ('Túi dưới gân cơ tròn lớn', 'giữa gân cơ tròn lớn và xương cánh tay'),
    'Subtendinous bursa of trapezius muscle': ('Túi dưới gân cơ thang', 'giữa gân cơ thang và gai vai'),
    'Subtendinous bursa of triceps brachii muscle': ('Túi dưới gân cơ tam đầu cánh tay', 'giữa gân cơ tam đầu cánh tay và mỏm khuỷu xương trụ'),
    'Bicipitoradial bursa': ('Túi nhị đầu-quay', 'giữa điểm bám gân cơ nhị đầu cánh tay và ụ xương quay'),
    '(Iliopectineal bursa)': ('Túi chậu-mu', 'giữa gân cơ chậu-thắt lưng với bao khớp háng và xương mu'),
    'Subtendinous bursa of iliacus muscle': ('Túi dưới gân cơ chậu', 'giữa gân cơ chậu-thắt lưng và mấu chuyển nhỏ'),
    'Trochanteric bursa of gluteus maximus muscle': ('Túi mấu chuyển của cơ mông lớn', 'giữa gân cơ mông lớn và mấu chuyển lớn xương đùi'),
    'Trochanteric bursa of gluteus medius muscle': ('Túi mấu chuyển của cơ mông giữa', 'giữa gân cơ mông giữa và mấu chuyển lớn'),
    'Trochanteric bursa of gluteus minimus muscle': ('Túi mấu chuyển của cơ mông nhỏ', 'giữa gân cơ mông nhỏ và mấu chuyển lớn'),
    'Subcutaneous trochanteric bursa': ('Túi dưới da mấu chuyển', 'dưới da mặt ngoài mấu chuyển lớn'),
    'Intermuscular gluteal bursae': ('Túi gian cơ mông', 'giữa cơ mông lớn và cơ mông giữa'),
    'Sciatic bursa of gluteus maximus muscle': ('Túi ngồi của cơ mông lớn', 'giữa cơ mông lớn và ụ ngồi'),
    'Sciatic bursa of obturator internus': ('Túi ngồi của cơ bịt trong', 'giữa gân cơ bịt trong và khuyết ngồi nhỏ'),
    'Subtendinous bursa of obturator internus': ('Túi dưới gân cơ bịt trong', 'giữa gân cơ bịt trong và hố mấu chuyển xương đùi'),
    'Bursa of piriformis muscle': ('Túi cơ hình lê', 'giữa gân cơ hình lê và mấu chuyển lớn'),
    'Subtendinous bursa of sartorius muscle': ('Túi dưới gân cơ may', 'giữa gân cơ may và mặt trong xương chày'),
    'Anserine bursa': ('Túi chân ngỗng', 'giữa gân chân ngỗng (cơ may, cơ thon, cơ bán gân) và lồi cầu trong xương chày'),
    'Semimembranosus bursa': ('Túi cơ bán mạc', 'giữa gân cơ bán mạc và bụng trong cơ sinh đôi'),
    'Superior bursa of biceps femoris muscle': ('Túi trên của cơ nhị đầu đùi', 'giữa gân cơ nhị đầu đùi và lồi cầu ngoài xương đùi'),
    'Inferior subtendinous bursa of biceps femoris muscle': ('Túi dưới gân dưới của cơ nhị đầu đùi', 'giữa điểm bám gân cơ nhị đầu đùi và đầu xương mác'),
    'Suprapatellar bursa': ('Túi trên xương bánh chè', 'giữa mặt sâu gân cơ tứ đầu đùi và xương đùi, thông với khoang khớp gối'),
    'Subcutaneous prepatellar bursa': ('Túi dưới da trước xương bánh chè', 'dưới da mặt trước xương bánh chè'),
    'Subfacial prepatellar bursa': ('Túi dưới mạc trước xương bánh chè', 'sâu dưới mạc mặt trước xương bánh chè'),
    'Subtendinous prepatellar bursa': ('Túi dưới gân trước xương bánh chè', 'giữa xương bánh chè và gân cơ tứ đầu đùi'),
    'Deep infrapatellar bursa': ('Túi sâu dưới xương bánh chè', 'giữa mặt sâu dây chằng bánh chè và xương chày'),
    'Subcutaneous infrapatellar bursa': ('Túi dưới da dưới xương bánh chè', 'dưới da mặt trước dây chằng bánh chè'),
    'Subcutaneous bursa of tuberosity of tibia': ('Túi dưới da ụ xương chày', 'dưới da mặt ngoài ụ xương chày'),
    'Lateral subtendinous bursa of gastrocnemius muscle': ('Túi dưới gân bụng ngoài cơ sinh đôi', 'giữa bụng ngoài cơ sinh đôi và lồi cầu ngoài xương đùi'),
    'Medial subtendinous bursa of gastrocnemius muscle': ('Túi dưới gân bụng trong cơ sinh đôi', 'giữa bụng trong cơ sinh đôi và lồi cầu trong xương đùi'),
    'Subtendinous bursa of tibialis anterior': ('Túi dưới gân cơ chày trước', 'giữa điểm bám gân cơ chày trước và xương chêm trong'),
    'Subtendinous calcaneal bursa': ('Túi gân gót', 'giữa gân gót và phía sau trên xương gót'),
    'Subcutaneous calcaneal bursa': ('Túi dưới da gót', 'dưới da tại điểm bám gân gót'),
    'Subcutaneous bursa of medial malleolus': ('Túi dưới da mắt cá trong', 'dưới da mặt ngoài mắt cá trong'),
    'Subcutaneous bursa of lateral malleolus': ('Túi dưới da mắt cá ngoài', 'dưới da mặt ngoài mắt cá ngoài'),
}
for _en, (_zh, _pos) in _BURSAE.items():
    TERMS[_en] = (
        _zh,
        f'Là túi hoạt dịch nằm {_pos}, chứa một lượng nhỏ dịch hoạt dịch.',
        'Giảm ma sát giữa gân, cơ với mặt xương và đệm áp lực; ma sát hoặc chịu áp lực lặp lại có thể gây viêm túi hoạt dịch dẫn đến sưng đau.')


TERMS['Muscular system'] = (
    'Hệ cơ', 'Gồm hơn 600 khối cơ xương cùng mạc, bao gân, túi hoạt dịch của chúng, chiếm khoảng 40% trọng lượng cơ thể người trưởng thành.',
    'Co kéo xương tạo chuyển động và duy trì tư thế, đồng thời sinh nhiệt duy trì thân nhiệt, bảo vệ nội tạng và hỗ trợ hồi lưu tĩnh mạch cùng bạch huyết.')