# -*- coding: utf-8 -*-
"""Các mục từ hệ thần kinh và cơ quan cảm giác. Định dạng: Tên tiếng Anh: (Tên tiếng Việt, Giới thiệu, Chức năng)"""

TERMS = {
    # ================= Thân não và Gian não =================
    'Medulla oblongata': ('Hành não', 'Đoạn dưới cùng của thân não, phía trên nối cầu não, phía dưới liên tục với tủy sống, dài khoảng 3cm.',
                          'Chứa trung khu tim mạch và trung khu hô hấp, là vùng quan trọng duy trì sự sống, đồng thời quản lý các phản xạ nôn, ho, nuốt.'),
    'Pyramid of medulla oblongata': ('Tháp hành não', 'Gờ dọc hai bên khe giữa mặt bụng hành não, cấu tạo bởi các sợi bó vỏ-tủy.',
                                     'Dẫn truyền lệnh vận động tùy ý từ vỏ não; các sợi bắt chéo trái-phải ở đầu dưới hành não, tạo nên sự chi phối vận động đối bên.'),
    'Olive': ('Quả ôliu', 'Gờ hình trứng mặt bụng-ngoài hành não, chứa nhân ôliu dưới.',
              'Truyền tín hiệu sai số vận động đến tiểu não qua cuống tiểu não dưới, là trung gian quan trọng trong học tập vận động và điều chỉnh động tác.'),
    'Pons': ('Cầu não', 'Phần phình to đoạn giữa thân não, các sợi ngang mặt bụng nối hai bán cầu tiểu não.',
             'Trung chuyển thông tin giữa đại não và tiểu não, chứa các nhân dây thần kinh mặt, dây tam thoa, đồng thời tham gia điều hòa nhịp hô hấp và giấc ngủ.'),
    'Midbrain': ('Não giữa', 'Đoạn trên cùng thân não, nối cầu não với gian não, ở giữa có ống não giữa.',
                 'Chứa trung khu phản xạ thị-thính (đồi thị trên, dưới), chất đen và nhân đỏ, tham gia vận động nhãn cầu, điều chỉnh tư thế và kiểm soát vận động.'),
    'Aqueduct of midbrain': ('Ống não giữa', 'Ống hẹp chạy xuyên não giữa, nối não thất ba với não thất bốn.',
                             'Vận chuyển dịch não tủy; do hẹp nhất nên tắc nghẽn là nguyên nhân thường gặp của não úng thủy tắc nghẽn.'),
    'Base of peduncle': ('Đáy cuống não', 'Bó sợi to thành đôi ở mặt bụng não giữa.',
                         'Chứa bó vỏ-tủy, bó vỏ-cầu và bó vỏ-nhân, là đường bắt buộc của lệnh vận động xuống từ đại não.'),
    'Interpeduncular fossa': ('Hố giữa cuống', 'Hố sâu giữa hai cuống đại não ở mặt bụng não giữa.',
                              'Dây thần kinh vận nhãn đi ra từ đây; chất thủng sau ở đáy hố có nhiều mạch máu nhỏ đi vào thân não.'),
    'Superior colliculus': ('Đồi thị trên', 'Một cặp gờ tròn phía trên mặt lưng não giữa.',
                            'Trung khu phản xạ thị giác, tích hợp thông tin thị và thính để điều khiển vận động định hướng đầu-mắt.'),
    'Inferior colliculus': ('Đồi thị dưới', 'Một cặp gờ phía dưới mặt lưng não giữa, là trung gian bắt buộc của đường thính giác.',
                            'Trung khu phản xạ thính giác, xử lý định vị nguồn âm và kích hoạt phản ứng giật mình với tiếng đột ngột.'),
    'Red nucleus': ('Nhân đỏ', 'Nhân hình trứng trong nắp não giữa, có màu hơi đỏ do chứa sắt.',
                    'Phát ra bó đỏ-tủy điều hòa trương lực cơ gấp, tham gia phối hợp vận động chi trên.'),
    'Reticular formation': ('Cấu trúc lưới', 'Vùng phân bố lan tỏa ở trung tâm thân não, do neuron và sợi đan xen thành lưới.',
                            'Duy trì tỉnh thức và ý thức qua hệ thống kích hoạt hướng lên, đồng thời điều hòa trương lực cơ, hoạt động tim mạch và hô hấp.'),
    'Thalamus': ('Đồi thị', 'Khối chất xám hình trứng lớn nhất gian não, gồm nhiều nhân.',
                 'Trạm trung chuyển của mọi thông tin cảm giác (trừ khứu giác) đến vỏ đại não, đồng thời tham gia điều khiển vận động, ý thức và cảm xúc.'),
    'Hypothalamus': ('Hạ đồi', 'Vùng nhỏ nằm dưới đồi thị, tạo thành thành dưới não thất ba, chỉ nặng khoảng 4g.',
                     'Trung khu cao nhất dưới vỏ của thần kinh tự chủ và nội tiết, điều hòa thân nhiệt, ăn uống, sinh sản, nhịp ngày-đêm và cảm xúc.'),
    'Mamillary body': ('Thể vú', 'Một cặp gờ hình hạt đậu ở phần sau hạ đồi, là nơi tận cùng chính của vòm.',
                       'Tham gia xử lý trí nhớ trong vòng Papez; tổn thương gặp trong hội chứng quên Wernicke–Korsakoff.'),
    'Habenula': ('Nhân cương', 'Nhân nhỏ nằm phía trên sau não thất ba, phía trước tuyến tùng.',
                 'Nối hệ thống limbic với não giữa, tham gia xử lý tín hiệu tiêu cực khi kỳ vọng thưởng thất bại, liên quan chặt chẽ đến trầm cảm.'),
    'Stria medullaris thalami': ('Dải tủy đồi thị', 'Bó sợi chạy dọc bờ lưng-trong đồi thị, tận cùng ở nhân cương.',
                                 'Truyền thông tin từ vùng vách và trước não limbic đến nhân cương.'),
    'Lateral geniculate body': ('Thể gối ngoài', 'Gờ nhỏ phía dưới sau đồi thị, là nhân trung chuyển đường thị giác.',
                                'Nhận sợi dải thị và chiếu đến vỏ thị sơ cấp thùy chẩm, xử lý thông tin thị giác theo lớp.'),
    'Medial geniculate body': ('Thể gối trong', 'Gờ nhỏ phía trong thể gối ngoài, là nhân trung chuyển đường thính giác.',
                               'Nhận sợi thính giác từ đồi thị dưới và chiếu đến vỏ thính sơ cấp ở hồi ngang thái dương.'),

    # ================= Tiểu não =================
    'Superior cerebellar peduncle': ('Cuống tiểu não trên', 'Bó sợi nối tiểu não với não giữa, còn gọi là cánh tay kết hợp.',
                                     'Đường chính của sợi ly tâm tiểu não, truyền thông tin điều chỉnh vận động qua nhân đỏ và đồi thị đến vỏ đại não.'),
    'Lingula of cerebellum': ('Lưỡi tiểu não', 'Lá nhỏ nhất phía trước cùng của giun tiểu não.',
                              'Thuộc tiểu não tiền đình và tiểu não tủy, tham gia điều hòa tư thế và trương lực cơ.'),
    'Central lobule': ('Tiểu thùy trung tâm', 'Tiểu thùy của thùy trước giun tiểu não, nằm sau lưỡi.',
                       'Nhận cảm giác từ tủy sống, tham gia phối hợp vận động thân và chi gần.'),
    'Wing of central lobule': ('Cánh tiểu thùy trung tâm', 'Phần tiểu thùy trung tâm kéo dài sang hai bán cầu.',
                               'Cùng tiểu thùy trung tâm tham gia phối hợp tư thế thân.'),
    'Culmen': ('Đỉnh núi', 'Tiểu thùy cao nhất của thùy trước giun tiểu não.',
               'Nhận cảm giác bản thể từ tủy sống, tham gia kiểm soát trình tự vận động chi.'),
    'Declive': ('Sườn núi', 'Tiểu thùy của thùy sau giun tiểu não ngay sau khe nguyên phát.',
                'Thuộc thùy sau, tham gia vòng lập kế hoạch vận động đại não–tiểu não qua trung gian cầu não.'),
    'Folium of vermis': ('Lá giun', 'Lá nhỏ hẹp trong thùy sau giun tiểu não.',
                         'Tham gia phối hợp vận động, hai bên tương ứng với tiểu thùy bán nguyệt trên của bán cầu.'),
    'Tuber of vermis': ('Củ giun', 'Tiểu thùy phía dưới thùy sau giun tiểu não.',
                        'Tham gia phối hợp vận động, hai bên nối với tiểu thùy bán nguyệt dưới và tháp giun.'),
    'Pyramis of vermis': ('Tháp giun', 'Tiểu thùy hình nón ở mặt dưới giun tiểu não.',
                          'Tham gia điều hòa tư thế và dáng đi.'),
    'Uvula of vermis': ('Lưỡi gà giun', 'Tiểu thùy mặt dưới giun tiểu não, nằm giữa tháp giun và nốt giun.',
                        'Liên hệ chặt chẽ với hệ thống tiền đình, tham gia điều hòa thăng bằng.'),
    'Nodule of vermis': ('Nốt giun', 'Tiểu thùy thấp nhất phía trước dưới của giun tiểu não, thuộc thùy nốt-cầu.',
                         'Phần lõi của tiểu não tiền đình, duy trì thăng bằng thân và ức chế rung giật nhãn cầu.'),
    'Flocculus': ('Cầu', 'Nốt nhỏ phía trước dưới bán cầu tiểu não, cùng nốt giun tạo thành thùy nốt-cầu.',
                  'Phần cổ xưa nhất của tiểu não, điều hòa phản xạ tiền đình-mắt, duy trì ổn định vị trí mắt khi nhìn.'),
    'Peduncle of flocculus': ('Cuống cầu', 'Cuống mỏng nối cầu với nốt giun.',
                              'Kênh sợi nối hai phần của thùy nốt-cầu.'),
    'Anterior quadrangular lobule': ('Tiểu thùy vuông trước', 'Tiểu thùy thùy trước bán cầu tiểu não, tương ứng đỉnh núi của giun.',
                                     'Tham gia phối hợp vận động và điều hòa trương lực cơ chi cùng bên.'),
    'Posterior quadrangular lobule': ('Tiểu thùy vuông sau', 'Tiểu thùy phần trước thùy sau bán cầu tiểu não, tương ứng sườn núi của giun.',
                                      'Tham gia lập kế hoạch và điều chỉnh tinh tế vận động.'),
    'Superior semilunar lobule': ('Tiểu thùy bán nguyệt trên', 'Tiểu thùy lớn phần trên thùy sau bán cầu tiểu não, tương ứng lá giun.',
                                  'Tạo vòng với vỏ đại não, tham gia kiểm soát trình tự và cường độ vận động tinh tế.'),
    'Inferior semilunar lobule': ('Tiểu thùy bán nguyệt dưới', 'Tiểu thùy lớn phần dưới thùy sau bán cầu tiểu não, tương ứng củ giun.',
                                  'Tham gia phối hợp động tác tinh tế của chi.'),
    'Gracile lobule': ('Tiểu thùy mảnh', 'Tiểu thùy mặt dưới bán cầu tiểu não, nằm giữa tiểu thùy bán nguyệt dưới và tiểu thùy hai bụng.',
                       'Tham gia phối hợp vận động.'),
    'Biventral lobule': ('Tiểu thùy hai bụng', 'Tiểu thùy mặt dưới bán cầu tiểu não, tương ứng tháp giun.',
                         'Tham gia duy trì tư thế và điều hòa dáng đi.'),
    'Tonsil of cerebellum': ('Hạnh nhân tiểu não', 'Gờ tròn mặt dưới bán cầu tiểu não gần đường giữa, sát lỗ chẩm lớn.',
                             'Tham gia phối hợp vận động; khi tăng áp lực nội sọ có thể thoát vị vào lỗ chẩm lớn chèn ép hành não, gây thoát vị lỗ chẩm lớn nguy hiểm đến tính mạng.'),

    # ================= Tân não: Thùy và Hồi não =================
    'Precentral gyrus': ('Hồi trước trung tâm', 'Hồi não phần sau thùy trán, phía trước rãnh trung tâm, là vỏ vận động sơ cấp (vùng 4).',
                         'Phát ra bó vỏ-tủy điều khiển vận động tùy ý của thân đối bên, "người vận động nhỏ" sắp xếp theo vị trí cơ thể.'),
    'Postcentral gyrus': ('Hồi sau trung tâm', 'Hồi não phần trước thùy đỉnh, phía sau rãnh trung tâm, là vỏ cảm giác thân thể sơ cấp.',
                          'Nhận cảm giác đau, nhiệt, xúc, áp và bản thể của thân đối bên, sắp xếp theo vị trí cơ thể thành "người cảm giác nhỏ".'),
    'Superior frontal gyrus': ('Hồi trán trên', 'Hồi dọc phía trên cùng của thùy trán.',
                               'Tham gia lập kế hoạch vận động, trí nhớ làm việc; phần sau là vùng vận động bổ trợ, mặt trong tham gia xử lý ý thức bản thân.'),
    'Middle frontal gyrus': ('Hồi trán giữa', 'Hồi nằm giữa rãnh trán trên và rãnh trán dưới.',
                             'Liên quan đến trí nhớ làm việc và chú ý; đầu sau là vùng vận động mắt thùy trán, điều khiển vận động cộng hợp tùy ý của hai mắt.'),
    'Opercular part of inferior frontal gyrus': ('Phần nắp của hồi trán dưới', 'Phần sau hồi trán dưới, nằm giữa rãnh trước trung tâm và nhánh lên.',
                                                 'Cùng phần tam giác tạo thành trung khu ngôn ngữ vận động Broca ở bán cầu ưu thế, chịu trách nhiệm sản sinh lời nói.'),
    'Triangular part of inferior frontal gyrus': ('Phần tam giác của hồi trán dưới', 'Phần giữa hồi trán dưới, nằm giữa nhánh lên và nhánh ngang.',
                                                  'Thuộc vùng Broca, tham gia xử lý ngữ pháp và tổ chức ngôn ngữ.'),
    'Orbital part of inferior frontal gyrus': ('Phần ổ mắt của hồi trán dưới', 'Phần trước dưới cùng của hồi trán dưới, tiếp tục ra mặt ổ mắt.',
                                               'Tham gia xử lý ngữ nghĩa, điều hòa cảm xúc và ức chế phản ứng.'),
    'Orbital gyri': ('Các hồi ổ mắt', 'Nhóm hồi ở mặt dưới (mặt ổ mắt) của thùy trán.',
                     'Tham gia đánh giá phần thưởng, ra quyết định và kiểm soát xung động; tổn thương có thể gây thay đổi nhân cách và hành vi xã hội không phù hợp.'),
    'Straight gyrus (Gyrus rectus)': ('Hồi thẳng', 'Hồi dài hẹp ở mặt ổ mắt thùy trán, phía trong rãnh khứu.',
                                      'Liên hệ chặt chẽ với khứu giác và hệ thống limbic, tham gia tích hợp thông tin cảm xúc và khứu giác.'),
    'Superior parietal lobule': ('Tiểu thùy đỉnh trên', 'Vùng thùy đỉnh phía trên rãnh trong đỉnh.',
                                 'Tích hợp thông tin cảm giác thân thể và không gian thị giác, tham gia phối hợp tay-mắt và chú ý không gian.'),
    'Supramarginal gyrus': ('Hồi trên bờ', 'Hồi của tiểu thùy đỉnh dưới bao quanh đầu tận của rãnh bên.',
                            'Tham gia xử lý âm vị và lập kế hoạch động tác sử dụng công cụ; tổn thương bên ưu thế có thể gây thất ngôn dẫn truyền và thất dụng.'),
    'Angular gyrus': ('Hồi góc', 'Hồi của tiểu thùy đỉnh dưới bao quanh đầu tận của rãnh thái dương trên.',
                      'Tích hợp thông tin thị, thính, cảm giác thân thể, tham gia đọc, viết và tính toán số; tổn thương có thể gây hội chứng Gerstmann.'),
    'Precuneus': ('Tiểu thùy chêm trước', 'Vùng mặt trong thùy đỉnh, nằm giữa nhánh bờ của rãnh đai và rãnh đỉnh-chẩm.',
                  'Nút lõi của mạng chế độ mặc định, tham gia tư duy tham chiếu bản thân, truy xuất trí nhớ tình huống và tưởng tượng không gian thị giác.'),
    'Cuneus': ('Tiểu thùy chêm', 'Vùng hình chêm mặt trong thùy chẩm, nằm giữa rãnh đỉnh-chẩm và rãnh cựa.',
               'Nhận thông tin thị giác của thị trường dưới, thuộc vỏ thị sơ cấp và thứ cấp.'),
    'Lingual gyrus': ('Hồi lưỡi', 'Hồi mặt trong thùy chẩm, phía dưới rãnh cựa.',
                      'Xử lý thông tin thị giác của thị trường trên, tham gia nhận diện chữ và hình phức tạp.'),
    'Superior temporal gyrus (Lateral part)': ('Phần ngoài của hồi thái dương trên', 'Hồi trên cùng của thùy thái dương, nằm dưới rãnh bên.',
                                               'Chứa vỏ liên hợp thính giác; phần sau bán cầu ưu thế là trung khu ngôn ngữ cảm giác Wernicke, chịu trách nhiệm hiểu lời nói.'),
    'Middle temporal gyrus': ('Hồi thái dương giữa', 'Hồi nằm giữa rãnh thái dương trên và rãnh thái dương dưới.',
                              'Tham gia trí nhớ ngữ nghĩa, truy xuất nghĩa từ và xử lý thông tin vận động thị giác.'),
    'Inferior temporal gyrus': ('Hồi thái dương dưới', 'Hồi ngoài dưới cùng của thùy thái dương.',
                                'Vùng cao cấp của đường thị giác bụng, chịu trách nhiệm nhận diện vật thể và khuôn mặt.'),
    'Transverse temporal gyri': ('Các hồi thái dương ngang', 'Các hồi ngang ngắn trên mặt trên hồi thái dương trên, nằm ở thành dưới rãnh bên, còn gọi là hồi Heschl.',
                                 'Vị trí của vỏ thính sơ cấp, sắp xếp theo cao độ âm thanh (định vị tần số).'),
    'Temporal plane': ('Mặt phẳng thái dương', 'Vùng hình tam giác phía sau các hồi thái dương ngang, trên mặt trên hồi thái dương trên.',
                       'Thuộc vỏ liên hợp thính giác, bên trái thường lớn hơn bên phải rõ rệt, liên quan đến bán cầu ưu thế ngôn ngữ.'),
    'Temporal pole': ('Cực thái dương', 'Vùng tận cùng phía trước của thùy thái dương.',
                      'Tích hợp thông tin cảm giác với cảm xúc, tham gia nhận thức xã hội và trí nhớ ngữ nghĩa như tên người; là vị trí hay gặp của sa sút trí tuệ ngữ nghĩa.'),
    'Occipital pole': ('Cực chẩm', 'Đầu tận cùng phía sau của thùy chẩm.',
                       'Tương ứng với chiếu xạ thị giác vùng hoàng điểm, là vùng vỏ có độ phân giải thị giác tinh tế nhất.'),
    'Superior occipital gyri': ('Hồi chẩm trên', 'Các hồi phần trên mặt ngoài thùy chẩm.',
                                'Thuộc vỏ liên hợp thị giác, tham gia xử lý thông tin không gian thị giác của đường lưng.'),
    'Lateral occipital gyrus (Middle occipital gyrus*)': ('Hồi chẩm ngoài (Hồi chẩm giữa)', 'Hồi phần giữa mặt ngoài thùy chẩm.',
                                                          'Tham gia nhận diện hình dạng vật thể, là vị trí của phức hợp chẩm ngoài.'),
    'Lateral occipitotemporal gyrus': ('Hồi chẩm-thái dương ngoài', 'Hồi nằm giữa rãnh chẩm-thái dương và rãnh phụ bên, còn gọi là hồi thoi.',
                                       'Chịu trách nhiệm nhận diện khuôn mặt (vùng mặt hồi thoi) và xử lý hình thức thị giác của chữ.'),
    'Medial occipitotemporal gyrus (Parahippocampal*)': ('Hồi chẩm-thái dương trong (Hồi cận hải mã)', 'Hồi phía trong rãnh phụ bên, bao quanh hải mã.',
                                                         'Vùng then chốt mã hóa trí nhớ và nhận diện cảnh, là cổng thông tin giữa hải mã và tân vỏ.'),
    'Cingulate gyrus (Posteroventral part*)': ('Phần sau-bụng của hồi đai', 'Phần hồi đai phía dưới sau thể chai, tiếp tục với hồi cận hải mã.',
                                               'Thuộc hệ thống limbic, tham gia truy xuất trí nhớ và xử lý cảm xúc.'),
    'Cingulate gyrus and sulcus (Middle anterior part)': ('Hồi đai và rãnh đai phần giữa trước', 'Đoạn giữa trước của hồi đai phía trên thể chai.',
                                                          'Tham gia giám sát xung đột, thành phần cảm xúc của đau và điều hòa chức năng tự chủ.'),
    'Cingulate gyrus and sulcus (Middle posterior part)': ('Hồi đai và rãnh đai phần giữa sau', 'Đoạn giữa sau của hồi đai phía trên thể chai.',
                                                           'Tham gia lựa chọn động tác và giám sát phản ứng.'),
    'Cingulate gyrus and sulcus (Posterior dorsal part)': ('Hồi đai và rãnh đai phần sau lưng', 'Phần trên sau của hồi đai, gần tiểu thùy chêm trước.',
                                                           'Thành phần của mạng chế độ mặc định, tham gia xử lý tham chiếu bản thân và trí nhớ.'),
    'Paracentral gyrus and sulcus*': ('Hồi cận trung tâm và rãnh cận trung tâm', 'Hồi mặt trong bán cầu đại não, tại chỗ kéo dài của rãnh trung tâm.',
                                      'Quản lý vận động và cảm giác chi dưới cùng vùng đáy chậu, đồng thời tham gia kiểm soát vỏ của tiểu tiện và đại tiện.'),
    'Insula (Subcentral gyrus and ant. and post. sulci*)': ('Đảo (Hồi dưới trung tâm và các rãnh trước, sau)',
                                                            'Vùng vỏ nằm sâu ở đáy rãnh bên, bị nắp trán-đỉnh-thái dương che phủ.',
                                                            'Tích hợp cảm giác nội tạng với cảm xúc, tham gia vị giác, cảm nhận đau, đồng cảm và ý thức cảm giác nội thân.'),

    # ================= Tân não: Rãnh não =================
    'Central sulcus': ('Rãnh trung tâm', 'Rãnh sâu chạy chéo từ bờ trên bán cầu ra trước dưới, ngăn cách thùy trán với thùy đỉnh.',
                       'Là ranh giới giữa vỏ vận động và vỏ cảm giác, đồng thời là mốc giải phẫu quan trọng nhất của định vị chức năng não.'),
    'Precentral sulcus (Superior part)*': ('Rãnh trước trung tâm phần trên', 'Đoạn trên của rãnh phía trước hồi trước trung tâm.',
                                           'Ngăn cách hồi trước trung tâm với hồi trán trên và giữa, là mốc định vị vùng tiền vận động.'),
    'Precentral sulcus (inferior part)*': ('Rãnh trước trung tâm phần dưới', 'Đoạn dưới của rãnh trước trung tâm.',
                                           'Ngăn cách hồi trước trung tâm với hồi trán dưới, gần vùng vận động mắt thùy trán.'),
    'Postcentral sulcus': ('Rãnh sau trung tâm', 'Rãnh phía sau hồi sau trung tâm.',
                           'Ngăn cách hồi sau trung tâm với tiểu thùy đỉnh trên và dưới.'),
    'Superior frontal sulcus': ('Rãnh trán trên', 'Rãnh dọc mặt lưng-ngoài thùy trán.',
                                'Ngăn cách hồi trán trên với hồi trán giữa, đầu sau gần vùng vận động mắt thùy trán.'),
    'Inferior frontal sulcus': ('Rãnh trán dưới', 'Rãnh giữa hồi trán giữa và hồi trán dưới.',
                                'Ngăn cách hồi trán giữa với hồi trán dưới, là mốc định vị vùng Broca.'),
    'Intraparietal sulcus': ('Rãnh trong đỉnh', 'Rãnh sâu ngang mặt ngoài thùy đỉnh.',
                             'Ngăn cách tiểu thùy đỉnh trên với tiểu thùy đỉnh dưới; vỏ xung quanh tham gia chú ý không gian, xử lý số lượng và phối hợp tay-mắt.'),
    'Subparietal sulcus': ('Rãnh dưới đỉnh', 'Rãnh mặt trong bán cầu, phía sau rãnh đai.',
                           'Ngăn cách tiểu thùy chêm trước với phần sau hồi đai.'),
    'Superior temporal sulcus': ('Rãnh thái dương trên', 'Rãnh dài giữa hồi thái dương trên và hồi thái dương giữa.',
                                 'Vỏ xung quanh tham gia nhận thức vận động sinh học, nhận diện hướng nhìn và nhận thức xã hội.'),
    'Inferior temporal sulcus': ('Rãnh thái dương dưới', 'Rãnh giữa hồi thái dương giữa và hồi thái dương dưới.',
                                 'Ngăn cách hồi thái dương giữa với hồi thái dương dưới.'),
    'Calcarine sulcus': ('Rãnh cựa', 'Rãnh sâu mặt trong thùy chẩm chạy từ cực chẩm ra trước.',
                         'Vỏ thị sơ cấp (vùng 17) phân bố dọc môi trên và dưới của rãnh, là mốc lõi định vị vỏ thị giác.'),
    'Parieto-occipital sulcus': ('Rãnh đỉnh-chẩm', 'Rãnh sâu mặt trong bán cầu chạy chéo từ bờ trên đỉnh xuống trước đến rãnh cựa.',
                                 'Là ranh giới giữa thùy đỉnh và thùy chẩm ở mặt trong.'),
    'Collateral sulcus': ('Rãnh phụ bên', 'Rãnh dài mặt dưới bán cầu chạy từ cực chẩm ra trước.',
                          'Ngăn cách hồi cận hải mã với hồi chẩm-thái dương ngoài (hồi thoi).'),
    'Posterior transverse collateral sulcus': ('Nhánh ngang sau của rãnh phụ bên', 'Nhánh ngang hướng ra ngoài ở đầu sau rãnh phụ bên.',
                                               'Đánh dấu ranh giới giữa hồi lưỡi và phần sau hồi thoi.'),
    'Occipitotemporal sulcus (Lateral part*)': ('Phần ngoài của rãnh chẩm-thái dương', 'Rãnh dọc mặt dưới bán cầu, phía ngoài rãnh phụ bên.',
                                                'Ngăn cách hồi chẩm-thái dương ngoài với hồi thái dương dưới.'),
    'Olfactory sulcus': ('Rãnh khứu', 'Rãnh dọc mặt ổ mắt thùy trán phía trong, chứa bó khứu.',
                         'Ngăn cách hồi thẳng với các hồi ổ mắt, là vị trí của hành khứu và bó khứu.'),
    'Orbital sulci (H-shaped orbital sulci*)': ('Các rãnh ổ mắt (Rãnh ổ mắt hình H)', 'Các rãnh sắp xếp hình H ở mặt ổ mắt thùy trán.',
                                                'Chia mặt ổ mắt thành bốn hồi ổ mắt trước, sau, trong, ngoài.'),
    'Orbital sulci (Lateral Orbital sulcus*)': ('Rãnh ổ mắt ngoài', 'Nhánh ngoài của rãnh ổ mắt hình H.',
                                                'Ngăn cách hồi ổ mắt ngoài với hồi ổ mắt sau.'),
    'Orbital gyri (Frontomarginal gyrus and sulcus*)': ('Hồi và rãnh bờ trán', 'Hồi và rãnh ở bờ trước cùng của mặt ổ mắt thùy trán.',
                                                        'Thuộc vùng bụng-trong trước trán, tham gia đánh giá cảm xúc và ra quyết định.'),
    'Transverse frontopolar gyrus and sulcus*': ('Hồi và rãnh ngang cực trán', 'Hồi và rãnh ngang trên bề mặt cực trán.',
                                                 'Thuộc vỏ cực trán, tham gia quản lý đa nhiệm và duy trì mục tiêu dài hạn.'),
    'Paracentral sulcus': ('Rãnh cận trung tâm', 'Nhánh hướng lên từ rãnh đai ở mặt trong bán cầu.',
                           'Đánh dấu bờ trước của tiểu thùy cận trung tâm.'),
    'Cingulate sulcus (Marginal part*)': ('Nhánh bờ của rãnh đai', 'Phần đầu tận của rãnh đai quay lên bờ trên bán cầu.',
                                          'Là mốc phân biệt tiểu thùy cận trung tâm với tiểu thùy chêm trước ở mặt trong.'),
    'Circular sulcus of insula': ('Rãnh vòng quanh đảo', 'Rãnh bao quanh chu vi đảo.',
                                  'Xác định ranh giới giữa đảo với nắp trán, đỉnh, thái dương.'),
    'Anterior occipital sulcus*': ('Rãnh trước chẩm', 'Rãnh phần trước mặt ngoài thùy chẩm.',
                                   'Là một trong các mốc ranh giới giữa thùy chẩm và thùy thái dương ở mặt ngoài.'),
    'Transverse occipital sulcus': ('Rãnh ngang chẩm', 'Rãnh ngang phần trên mặt ngoài thùy chẩm.',
                                    'Đánh dấu vùng chuyển tiếp giữa hồi chẩm trên và thùy đỉnh.'),
    'Lunate sulcus': ('Rãnh lưỡi liềm', 'Rãnh hình bán nguyệt ở mặt ngoài thùy chẩm, biến đổi nhiều ở người.',
                      'Đại thể đánh dấu bờ ngoài của vỏ thị sơ cấp; ổn định hơn ở loài vượn.'),
    'Inferior occipital gyrus and sulcus*': ('Hồi và rãnh chẩm dưới', 'Hồi và rãnh phần dưới mặt ngoài thùy chẩm.',
                                             'Thuộc vỏ liên hợp thị giác, tham gia nhận diện vật thể của đường bụng.'),
    'Sulcus interm_prim-Jensen': ('Rãnh trung gian Jensen', 'Rãnh ngắn trong tiểu thùy đỉnh dưới, nằm giữa hồi trên bờ và hồi góc, còn gọi là rãnh sơ cấp trung gian.',
                                  'Làm mốc giải phẫu phân biệt hồi trên bờ với hồi góc.'),
    'Lat_Fis-ant-Horizont': ('Nhánh ngang trước của rãnh bên', 'Nhánh ngắn hướng ngang ra trước từ rãnh bên.',
                             'Cùng nhánh lên trước đánh dấu ranh giới phần tam giác của hồi trán dưới.'),
    'Lat_Fis-ant-Vertical': ('Nhánh lên trước của rãnh bên', 'Nhánh ngắn hướng lên từ rãnh bên.',
                             'Ngăn cách phần tam giác với phần nắp của hồi trán dưới.'),
    'Lat_Fis-post': ('Nhánh sau của rãnh bên', 'Đoạn thân chính phía sau của rãnh bên, tận cùng ở hồi trên bờ.',
                     'Ngăn cách thùy trán-đỉnh với thùy thái dương, đầu tận bị hồi trên bờ bao quanh.'),

    # ================= Nhân nền và Chất trắng =================
    'Caudate nucleus': ('Nhân đuôi', 'Nhân chất xám hình chữ C cong theo não thất bên, chia đầu, thân, đuôi.',
                        'Thuộc thể vân, tham gia khởi động và ức chế vận động, học thói quen và hành vi hướng mục tiêu.'),
    'Putamen': ('Vỏ nhân', 'Phần ngoài của nhân đậu, cùng nhân đuôi gọi là thể vân mới.',
                'Nhận chiếu rộng từ vỏ đại não, tham gia thực hiện tự động vận động và học kỹ năng.'),
    'Globus pallidus': ('Nhân nhạt', 'Phần trong của nhân đậu, màu nhạt do giàu sợi myelin.',
                        'Nhân xuất chính của vòng nhân nền, điều hòa biên độ vận động bằng cách ức chế đồi thị; là đích kích thích não sâu trong bệnh Parkinson.'),
    'Lentiform nucleus': ('Nhân đậu', 'Nhân hình thấu kính hai mặt lồi do vỏ nhân và nhân nhạt tạo thành.',
                          'Phần lõi của nhân nền, tham gia điều hòa vận động tùy ý và kiểm soát trương lực cơ.'),
    'Amygdaloid body': ('Thể hạnh nhân', 'Nhóm nhân hình hạnh nhân nằm phía trước trong thùy thái dương, phía trước đầu hải mã.',
                        'Trung khu xử lý sợ hãi và đe dọa, gắn màu cảm xúc cho trí nhớ và kích hoạt phản ứng stress tự chủ.'),
    'Hippocampus': ('Hải mã', 'Gờ hình cung ở thành đáy sừng dưới não thất bên, thuộc cổ vỏ.',
                    'Chuyển trí nhớ ngắn hạn thành dài hạn và tham gia định hướng không gian; là vị trí sớm nhất bị ảnh hưởng trong bệnh Alzheimer.'),
    'Septal nuclei': ('Nhân vách', 'Nhân chất xám nằm dưới vách trong suốt, phía trước mép trước.',
                      'Trung tâm then chốt của hệ thống limbic, tham gia phần thưởng, động lực và điều hòa nhịp theta của hải mã.'),
    'Septum pellucidum': ('Vách trong suốt', 'Màng mỏng ngăn hai sừng trước não thất bên, gồm hai lớp.',
                          'Ngăn cách hai não thất bên; bất thường phát triển liên quan đến dị tật cấu trúc đường giữa.'),
    'Corpus callosum': ('Thể chai', 'Bó sợi lớn nhất nối hai bán cầu đại não, chứa khoảng 200 triệu sợi trục.',
                        'Truyền và tích hợp thông tin giữa hai bán cầu; cắt đứt gây hiện tượng "não tách đôi".'),
    'Anterior commissure': ('Mép trước', 'Bó sợi nhỏ xuyên qua phía trên bản tận cùng, nối hai thùy thái dương.',
                            'Giao tiếp thông tin giữa hai vùng khứu, thể hạnh nhân và phần trước thùy thái dương.'),
    'Posterior commissure': ('Mép sau', 'Bó sợi ngang nằm phía lưng miệng trên của ống não giữa.',
                             'Tham gia đồng bộ hai bên phản xạ đồng tử với ánh sáng và phối hợp vận động dọc nhãn cầu.'),
    'Hippocampal commissure': ('Mép hải mã', 'Sợi ngang giữa hai chân vòm, còn gọi là mép vòm.',
                               'Nối cấu trúc hải mã hai bên, thực hiện chia sẻ thông tin trí nhớ hai bên.'),
    'Fornix': ('Vòm', 'Bó sợi hình cung khởi từ hải mã, vòng trên đồi thị tận cùng ở thể vú.',
               'Đường ly tâm chính của hải mã, là một mắt xích then chốt của vòng trí nhớ Papez.'),
    'Stria terminalis': ('Dải tận', 'Bó sợi dài mảnh chạy trong rãnh giữa nhân đuôi và đồi thị.',
                         'Một trong các đường ly tâm chính của thể hạnh nhân, chiếu đến vùng vách và hạ đồi điều hòa phản ứng stress.'),
    'White matter of telencephalon': ('Chất trắng tân não', 'Vùng dưới vỏ đại não cấu tạo bởi sợi thần kinh có myelin, tức tủy chất.',
                                      'Nối các vùng vỏ và cấu trúc dưới vỏ qua sợi liên hợp, sợi mép và sợi chiếu.'),
    'White matter of spinal cord': ('Chất trắng tủy sống', 'Vùng sợi có myelin bao quanh chất xám tủy sống, chia thành cột trước, cột bên và cột sau.',
                                    'Chứa các bó dẫn truyền lên và xuống, là đường thông tin qua lại giữa não và thân thể.'),

    # ================= Não thất và Màng não =================
    'Lateral ventricle': ('Não thất bên', 'Khoang hình chữ C trong hai bán cầu đại não, chia sừng trước, phần trung tâm, sừng sau và sừng dưới.',
                          'Sản sinh và chứa dịch não tủy, thông với não thất ba qua lỗ gian não thất.'),
    'Third ventricle': ('Não thất ba', 'Khe hẹp giữa hai bên gian não.',
                        'Dịch não tủy từ đây chảy qua ống não giữa đến não thất bốn; xung quanh là hạ đồi và đồi thị.'),
    'Fourth ventricle': ('Não thất bốn', 'Khoang hình thoi nằm giữa cầu não, hành não và tiểu não.',
                         'Dịch não tủy từ đây chảy qua lỗ giữa và lỗ bên vào khoang dưới nhện; đáy là hố thoi, chứa nhiều nhân dây thần kinh sọ.'),
    'Central canal': ('Ống trung tâm', 'Ống hẹp chạy suốt chiều dài tủy sống, phía trên thông với não thất bốn.',
                      'Chứa dịch não tủy; ở người lớn thường tắc một phần, giãn bất thường gây bệnh syringomyelia.'),
    "Central canal'": ('Ống trung tâm', 'Ống nhỏ chạy giữa tủy sống, phía trên thông với não thất bốn.',
                       'Đoạn cuối cùng của dịch não tủy trong hệ thần kinh trung ương.'),
    'Choroid plexus': ('Đám rối mạch mạc', 'Cấu trúc dạng nhung mao nhô vào các não thất, cấu tạo bởi màng mềm giàu mao mạch và biểu mô ống não thất.',
                       'Bài tiết dịch não tủy (khoảng 500ml/ngày), đồng thời tạo thành hàng rào máu–dịch não tủy.'),
    'Falx cerebri': ('Lưỡi liềm đại não', 'Nếp gấp hình lưỡi liềm của màng cứng từ đỉnh sọ đi vào giữa hai bán cầu đại não.',
                     'Hạn chế sự dịch chuyển trái-phải của bán cầu đại não; khi tăng áp lực nội sọ, mô não có thể thoát vị dưới bờ tự do tạo thành thoát vị dưới lưỡi liềm.'),
    'Tentorium cerebelli': ('Lều tiểu não', 'Nếp gấp hình lều của màng cứng đi vào giữa đại não và tiểu não.',
                            'Đỡ thùy chẩm, ngăn cách khoang trên lều với dưới lều; tại khuyết lều có thể xảy ra thoát vị khuyết lều tiểu não chèn ép não giữa, nguy hiểm đến tính mạng.'),
    'Spinal dura': ('Màng cứng tủy', 'Lớp màng ngoài cùng bao quanh tủy sống, là mô liên kết đặc một lớp.',
                    'Bảo vệ tủy sống; khoang ngoài màng cứng giữa nó với màng xương ống sống là vị trí tiêm thuốc gây tê ngoài màng cứng.'),

    # ================= Tủy sống và Bó dẫn truyền =================
    'Anterior horn of spinal cord': ('Sừng trước tủy sống', 'Phần phình phía bụng của chất xám tủy sống, chứa neuron vận động lớn.',
                                     'Phát sợi qua rễ trước chi phối cơ xương; tổn thương (như bại liệt tủy) gây liệt mềm.'),
    'Posterior horn of spinal cord': ('Sừng sau tủy sống', 'Phần dài mảnh phía lưng của chất xám tủy sống.',
                                      'Nhận thông tin cảm giác từ rễ sau và tích hợp sơ cấp, là vị trí "cổng" điều biến đau.'),
    'Intermediolateral nucleus': ('Nhân gian bên', 'Nhân trong sừng bên đoạn T1–L3 của tủy sống.',
                                  'Vị trí neuron trước hạch giao cảm, điều khiển hoạt động nội tạng, trương lực mạch máu và tiết mồ hôi.'),
    'Intermediomedial nucleus': ('Nhân gian trong', 'Nhân nhỏ nằm phía trong dải trung gian của tủy sống.',
                                 'Nhận cảm giác nội tạng, tham gia tích hợp phản xạ nội tạng.'),
    'Lateral intermediate substance': ('Chất trung gian ngoài', 'Phần ngoài của dải trung gian chất xám tủy sống.',
                                       'Chứa neuron tự chủ và neuron trung gian, liên hệ phản xạ thân thể với nội tạng.'),
    'Nucleus proprius': ('Nhân riêng', 'Nhân lớn lớp trong sừng sau tủy sống.',
                         'Nhận cảm giác đau, nhiệt và xúc thô, phát sợi bắt chéo tạo thành bó tủy-đồi thị.'),
    'Posterolateral tract': ('Bó sau bên', 'Bó sợi nhỏ nằm giữa đỉnh sừng sau và bề mặt tủy sống, còn gọi là bó Lissauer.',
                             'Sợi mảnh rễ sau vào tủy sống lên xuống 1–2 đoạn rồi tận cùng, làm phân bố đoạn của cảm giác đau nhiệt chồng chéo.'),
    'Anterior root of spinal nerve': ('Rễ trước dây thần kinh sống', 'Chuỗi rễ sợi phát ra từ rãnh trước ngoài tủy sống.',
                                      'Hướng ly tâm, chứa sợi vận động chi phối cơ xương và sợi trước hạch tự chủ.'),
    'Posterior root of spinal nerve': ('Rễ sau dây thần kinh sống', 'Rễ sợi đi vào rãnh sau ngoài tủy sống, trên đó có hạch thần kinh sống.',
                                       'Hướng hướng tâm, đưa thông tin cảm giác thân thể và nội tạng vào tủy sống.'),
    'Spinal ganglion': ('Hạch thần kinh sống', 'Phình to nằm trong lỗ gian đốt sống trên rễ sau dây thần kinh sống, chứa neuron giả đơn cực.',
                        'Vị trí thân neuron cảm giác; virus zona nằm ẩn tại đây.'),
    'Cauda equina': ('Đuôi ngựa', 'Cấu trúc dạng bó do rễ thần kinh thắt lưng, cùng, cụt đi xuống trong ống sống dưới nón tủy.',
                     'Chi phối chi dưới và đáy chậu; do không có tủy sống tại đây, khe đốt sống L3–4 trở thành vị trí an toàn cho chọc dò thắt lưng.'),
    'Spinal reticular process': ('Mỏm lưới tủy sống', 'Vùng chất xám-trắng xen kẽ dạng lưới phía ngoài chất xám tủy sống, còn gọi là nhân lưới.',
                                 'Tham gia điều biến đau và điều hòa mức tỉnh thức hướng lên.'),
    'Gracile fasciculus': ('Bó mảnh', 'Bó sợi hướng lên phía trong cột sau tủy sống, cấu tạo bởi sợi hướng tâm từ T5 trở xuống.',
                           'Dẫn truyền cảm giác xúc tinh tế, rung và bản thể nửa dưới thân đến nhân mảnh hành não.'),
    'Cuneate fasciculus': ('Bó chêm', 'Bó sợi hướng lên phía ngoài cột sau tủy sống, chỉ có ở đoạn từ T4 trở lên.',
                           'Dẫn truyền cảm giác xúc tinh tế, rung và bản thể nửa trên thân đến nhân chêm hành não.'),
    'Lateral spinothalamic tract': ('Bó tủy-đồi thị bên', 'Bó hướng lên phần trước cột bên, sợi đã bắt chéo trong tủy sống.',
                                    'Dẫn truyền cảm giác đau và nhiệt của thân đối bên đến đồi thị.'),
    'Anterior spinothalamic tract': ('Bó tủy-đồi thị trước', 'Bó hướng lên ở cột trước.',
                                     'Dẫn truyền cảm giác xúc thô và áp của thân đối bên.'),
    'Anterior spinocerebellar tract': ('Bó tủy-tiểu não trước', 'Bó hướng lên phần trước chu vi cột bên.',
                                       'Đưa cảm giác bản thể chi dưới và thân qua cuống tiểu não trên vào tiểu não, điều khiển vận động toàn chi.'),
    'Posterior spinocerebellar tract': ('Bó tủy-tiểu não sau', 'Bó hướng lên phần sau chu vi cột bên.',
                                        'Đưa cảm giác bản thể tinh tế cơ và khớp chi dưới cùng bên vào tiểu não qua cuống tiểu não dưới.'),
    'Spinotectal tract': ('Bó tủy-nắp', 'Bó hướng lên đi kèm bó tủy-đồi thị, tận cùng ở đồi thị trên não giữa.',
                          'Trung gian phản xạ định hướng quay đầu, quay mắt với kích thích gây tổn thương.'),
    'Lateral corticospinal tract': ('Bó vỏ-tủy bên', 'Bó vận động lớn nhất đi xuống cột bên sau khi bắt chéo tháp hành não.',
                                    'Truyền lệnh vận động tùy ý từ vỏ đại não đến sừng trước tủy sống đối bên, chủ yếu điều khiển động tác tinh tế đầu xa chi.'),
    'Anterior corticospinal tract': ('Bó vỏ-tủy trước', 'Một số sợi không bắt chéo ở tháp, đi xuống cột trước.',
                                     'Bắt chéo ở mức đoạn tủy sống rồi chi phối cơ thân và cơ gần, nên cơ thân được chi phối hai bên.'),
    'Rubrospinal tract': ('Bó đỏ-tủy', 'Bó sợi khởi từ nhân đỏ não giữa, bắt chéo rồi đi xuống cột bên.',
                          'Dễ hóa trương lực cơ gấp, ức chế cơ duỗi, tham gia phối hợp vận động chi trên.'),
    'Tectospinal tract': ('Bó nắp-tủy', 'Bó khởi từ đồi thị trên não giữa, bắt chéo rồi đi xuống cột trước.',
                          'Trung gian phản xạ quay hướng của đầu cổ với kích thích thị-thính đột ngột.'),
    'Lateral reticulospinal tract': ('Bó lưới-tủy bên', 'Bó khởi từ cấu trúc lưới hành não, đi xuống cột bên.',
                                     'Ức chế phản xạ duỗi của tủy sống, giảm trương lực cơ.'),
    'Medial reticulospinal tract': ('Bó lưới-tủy trong', 'Bó khởi từ cấu trúc lưới cầu não, đi xuống cột trước.',
                                    'Dễ hóa hoạt động cơ duỗi, duy trì tư thế chống trọng lực của thân.'),
    'Lateral vestibulospinal tract': ('Bó tiền đình-tủy bên', 'Bó khởi từ nhân tiền đình ngoài, không bắt chéo đi xuống cột trước.',
                                      'Kích thích mạnh cơ duỗi cùng bên, là đường chính duy trì thăng bằng khi đứng.'),
    'Medial vestibulospinal tract': ('Bó tiền đình-tủy trong', 'Bó khởi từ nhân tiền đình trong, đi xuống đoạn cổ-ngực.',
                                     'Điều hòa cơ cổ, ổn định vị trí đầu để phối hợp phản xạ tiền đình-mắt.'),
    'Anterior fasciculus proprius': ('Bó riêng trước', 'Bó sợi ngắn sát bờ chất xám cột trước.',
                                     'Liên hệ các đoạn tủy sống liền kề, hoàn thành phản xạ riêng liên đoạn.'),
    'Lateral fasciculus proprius': ('Bó riêng bên', 'Bó sợi ngắn sát bờ chất xám cột bên.',
                                    'Giao tiếp các đoạn tủy sống khác nhau, phối hợp hoạt động phản xạ nhiều đoạn.'),
    'Posterior fasciculus proprius': ('Bó riêng sau', 'Bó sợi ngắn sát bờ chất xám cột sau.',
                                      'Hoàn thành liên lạc giữa các đoạn tủy sống, tham gia phản xạ phối hợp.'),

    # ================= Nhân dây thần kinh sọ =================
    'Nucleus of oculomotor nerve': ('Nhân dây vận nhãn', 'Nhân vận động nằm ở mức đồi thị trên não giữa, phía bụng ống não thất.',
                                    'Chi phối cơ thẳng trên, dưới, trong, cơ chéo dưới và cơ nâng mi trên, điều khiển vận động nhãn cầu và mở mắt.'),
    'Accessory nucleus of oculomotor nerve': ('Nhân phụ dây vận nhãn', 'Nhân phó giao cảm phía lưng-trong nhân dây vận nhãn, còn gọi là nhân Edinger–Westphal.',
                                              'Phát sợi trước hạch phó giao cảm qua hạch mi chi phối cơ thắt đồng tử và cơ mi, hoàn thành phản xạ co đồng tử và điều tiết.'),
    'Nucleus of trochlear nerve': ('Nhân dây ròng rọc', 'Nhân vận động nhỏ nằm ở mức đồi thị dưới não giữa.',
                                   'Chi phối cơ chéo trên đối bên, làm nhãn cầu xoay trong và quay xuống.'),
    'Motor root of trigeminal nerve': ('Rễ vận động dây tam thoa', 'Sợi vận động phát ra từ phần giữa cầu não, đi cùng dây hàm dưới ra sọ.',
                                       'Chi phối cơ nhai, cơ căng màng nhĩ và cơ hàm-móng, hoàn thành động tác nhai.'),
    'Sensory root of trigeminal nerve': ('Rễ cảm giác dây tam thoa', 'Phần cảm giác to của dây tam thoa, thân neuron nằm ở hạch tam thoa.',
                                         'Dẫn truyền cảm giác đau, nhiệt, xúc của mặt, niêm mạc miệng mũi và màng cứng, là nhánh hướng tâm của phản xạ giác mạc.'),
    'Nucleus of abducens nerve': ('Nhân dây giạng', 'Nhân vận động nằm sâu dưới gò dây mặt phần dưới cầu não.',
                                  'Chi phối cơ thẳng ngoài cùng bên làm nhãn cầu quay ngoài, đồng thời phối hợp vận động cộng hợp ngang hai mắt qua bó dọc trong.'),
    'Motor nucleus of facial nerve': ('Nhân vận động dây mặt', 'Nhân vận động nằm phía bụng-ngoài cấu trúc lưới phần dưới cầu não.',
                                      'Chi phối toàn bộ cơ biểu cảm; phần trên nhận chi phối vỏ hai bên, phần dưới chỉ nhận đối bên, là cơ sở phân biệt liệt mặt trung ương và ngoại biên.'),
    'Superior salivatory nucleus': ('Nhân nước bọt trên', 'Nhân phó giao cảm phần dưới cầu não, thuộc dây mặt.',
                                    'Phát sợi phó giao cảm chi phối tuyến lệ, tuyến dưới hàm và dưới lưỡi, quản lý chảy nước mắt và tiết nước bọt.'),
    'Inferior salivatory nucleus': ('Nhân nước bọt dưới', 'Nhân phó giao cảm phần trên hành não, thuộc dây lưỡi-hầu.',
                                    'Phát sợi phó giao cảm qua hạch tai chi phối tuyến mang tai, thúc đẩy tiết nước bọt.'),
    'Anterior cochlear nucleus': ('Nhân ốc bụng', 'Nhân thính giác nằm phía bụng-ngoài cuống tiểu não dưới.',
                                  'Nhận sợi dây ốc và giữ thông tin thời gian chính xác, tham gia định vị nguồn âm theo chiều ngang.'),
    'Posterior cochlear nucleus': ('Nhân ốc lưng', 'Nhân thính giác nằm phía lưng-ngoài cuống tiểu não dưới.',
                                   'Phân tích đặc điểm phổ âm thanh, tham gia định vị nguồn âm theo chiều dọc.'),
    'Vestibular nuclei': ('Các nhân tiền đình', 'Nhóm nhân nằm phía ngoài đáy não thất bốn, gồm bốn nhân trên, dưới, trong, ngoài.',
                          'Tích hợp cảm giác tiền đình để duy trì thăng bằng và tư thế, đồng thời điều khiển phản xạ tiền đình-mắt ổn định ánh nhìn.'),
    'Nucleus ambiguus': ('Nhân mơ hồ', 'Nhân vận động hình cột trong cấu trúc lưới hành não, thuộc dây lưỡi-hầu, dây lang thang và dây phụ.',
                         'Chi phối cơ hầu họng, hoàn thành nuốt và phát âm; tổn thương gây khàn tiếng và khó nuốt.'),
    'Nucleus of solitary tract': ('Nhân bó đơn độc', 'Nhân hình cột dài bao quanh bó đơn độc trong hành não.',
                                  'Phần trên nhận vị giác, phần dưới nhận cảm giác nội tạng tim mạch, hô hấp và tiêu hóa, là trung gian lõi của phản xạ nội tạng.'),
    'Posterior nucleus of vagus nerve': ('Nhân lưng dây lang thang', 'Nhân phó giao cảm nằm sâu dưới tam giác dây lang thang đáy não thất bốn.',
                                         'Phát sợi trước hạch chi phối nội tạng cổ, ngực, bụng, làm chậm nhịp tim, thúc đẩy tiết tuyến tiêu hóa và nhu động ruột.'),
    'Nucleus of hypoglossal nerve': ('Nhân dây dưới lưỡi', 'Nhân vận động nằm sâu dưới tam giác dây dưới lưỡi đáy não thất bốn.',
                                     'Chi phối toàn bộ cơ lưỡi cùng bên; tổn thương một bên khi thè lưỡi lệch về bên bệnh.'),
    'Nucleus of accessory nerve': ('Nhân dây phụ', 'Nhân vận động nằm phần ngoài sừng trước 5–6 đoạn cổ trên của tủy sống.',
                                   'Phát sợi qua lỗ chẩm lớn vào sọ rồi ra sọ, chi phối cơ ức-đòn-chũm và cơ thang.'),

    # ================= Dây thần kinh sọ =================
    'Olfactory nerve (I)': ('Dây khứu (I)', 'Dây thần kinh sọ số I, do khoảng 20 sợi khứu tập hợp từ sợi trung tâm tế bào khứu vùng khứu khoang mũi xuyên qua sàng vào sọ.',
                            'Dẫn truyền khứu giác; gãy hố sọ trước tổn thương sàng có thể gây mất khứu giác và rò dịch não tủy mũi.'),
    'Optic nerve (II)': ('Dây thị (II)', 'Dây thần kinh sọ số II, do sợi trục tế bào hạch võng mạc tập hợp thành, thực chất là phần kéo dài của não chứ không phải dây thần kinh ngoại biên thực sự.',
                         'Dẫn truyền thông tin thị giác đến thể gối ngoài; được bao bởi ba lớp màng não, tăng áp lực nội sọ có thể gây phù gai thị.'),
    'Oculomotor nerve (III)': ('Dây vận nhãn (III)', 'Dây thần kinh sọ số III, đi ra từ hố giữa cuống não giữa, qua khe ổ mắt trên vào ổ mắt.',
                               'Chi phối bốn cơ ngoài mắt và cơ nâng mi trên, đồng thời chứa sợi phó giao cảm quản lý co đồng tử; liệt gây sụp mi, lé ngoài dưới và giãn đồng tử.'),
    'Trochlear nerve (IV)': ('Dây ròng rọc (IV)', 'Dây thần kinh sọ số IV, là dây duy nhất phát ra từ mặt lưng thân não và bắt chéo hoàn toàn, đồng thời là dây mảnh nhất.',
                             'Chi phối cơ chéo trên; liệt gây khó nhìn xuống và xuống cầu thang, xuất hiện tư thế đầu bù trừ nghiêng.'),
    'Trigeminal nerve (V)': ('Dây tam thoa (V)', 'Dây thần kinh sọ số V, dây to nhất, chia thành dây mắt, dây hàm trên và dây hàm dưới.',
                             'Dẫn truyền cảm giác chung đầu mặt và chi phối cơ nhai; kích thích nhánh có thể gây đau dây tam thoa dữ dội.'),
    'Ophthalmic nerve': ('Dây mắt', 'Nhánh 1 của dây tam thoa, qua khe ổ mắt trên vào ổ mắt rồi chia thành dây lệ, trán và mũi-mi.',
                         'Dẫn truyền cảm giác nhãn cầu, mi trên, sống mũi và da trán, là nhánh hướng tâm của phản xạ giác mạc.'),
    'Maxillary nerve': ('Dây hàm trên', 'Nhánh 2 của dây tam thoa, qua lỗ tròn ra sọ vào hố chân bướm-khẩu cái.',
                        'Dẫn truyền cảm giác da mi dưới, bên mũi, môi trên và răng hàm trên cùng niêm mạc khoang mũi.'),
    'Meningeal branch of maxillary nerve': ('Nhánh màng não của dây hàm trên', 'Nhánh hồi nhỏ phát ra trong sọ từ dây hàm trên.',
                                            'Phân bố màng cứng hố sọ giữa, dẫn truyền cảm giác đau của nó.'),
    'Anterior division of mandibular nerve': ('Thân trước dây hàm dưới', 'Nhánh trước nhỏ hơn sau khi dây hàm dưới ra lỗ bầu dục.',
                                              'Chủ yếu sợi vận động, chi phối cơ nhai, và phát dây má dẫn truyền cảm giác vùng má.'),
    'Posterior division of mandibular nerve': ('Thân sau dây hàm dưới', 'Nhánh sau lớn hơn của dây hàm dưới.',
                                               'Chủ yếu sợi cảm giác, phát dây tai-thái dương, lưỡi và răng dưới, đồng thời chi phối cơ hàm-móng.'),
    'Buccal nerve': ('Dây má', 'Nhánh cảm giác phát ra từ thân trước dây hàm dưới, xuyên cơ má đến niêm mạc má.',
                     'Dẫn truyền cảm giác da và niêm mạc má; lưu ý nó không chi phối cơ má (cơ má do dây mặt chi phối).'),
    'Lingual nerve': ('Dây lưỡi', 'Nhánh của thân sau dây hàm dưới, chạy hình cung ra trước đến lưỡi, giữa đường nhận dây thừng nhĩ gia nhập.',
                      'Dẫn truyền cảm giác chung 2/3 trước lưỡi; qua dây thừng nhĩ mang vị giác và sợi phó giao cảm chi phối tuyến dưới hàm, dưới lưỡi.'),
    'Inferior alveolar nerve': ('Dây răng dưới', 'Nhánh lớn nhất của thân sau dây hàm dưới, qua lỗ hàm dưới vào ống hàm dưới.',
                                'Chi phối toàn bộ răng và nướu hàm dưới; là đích gây tê thần kinh răng dưới trong nha khoa.'),
    'Mental nerve': ('Dây cằm', 'Nhánh tận của dây răng dưới, đi ra từ lỗ cằm.',
                     'Dẫn truyền cảm giác da niêm mạc cằm và môi dưới.'),
    'Nerve to mylohyoid muscle': ('Dây cơ hàm-móng', 'Nhánh mảnh phát ra từ dây răng dưới trước khi vào lỗ hàm dưới.',
                                  'Chi phối cơ hàm-móng và bụng trước cơ hai bụng, tham gia há miệng và nâng sàn miệng.'),
    'Abducens nerve (VI)': ('Dây giạng (VI)', 'Dây thần kinh sọ số VI, đi ra từ rãnh hành-cầu, có đường đi trong sọ dài nhất.',
                            'Chi phối cơ thẳng ngoài; do đường dài dễ bị kéo khi tăng áp lực nội sọ, liệt gây lé trong và song thị.'),
    'Facial nerve (VII)': ('Dây mặt (VII)', 'Dây thần kinh sọ số VII, qua lỗ tai trong vào ống mặt, ra sọ qua lỗ trâm-chũm rồi xuyên tuyến mang tai phân nhánh.',
                           'Chi phối toàn bộ cơ biểu cảm, đồng thời chứa sợi phó giao cảm và vị giác; tổn thương gây liệt mặt ngoại biên (liệt Bell).'),
    'Chorda tympani': ('Dây thừng nhĩ', 'Nhánh phát ra trong ống mặt từ dây mặt, qua hòm nhĩ gia nhập dây lưỡi.',
                       'Dẫn truyền vị giác 2/3 trước lưỡi, đồng thời mang sợi trước hạch phó giao cảm chi phối tuyến dưới hàm và dưới lưỡi.'),
    'Vestibulocochlear nerve (VIII)': ('Dây tiền đình-ốc tai (VIII)', 'Dây thần kinh sọ số VIII, do dây tiền đình và dây ốc hợp thành, qua lỗ tai trong vào sọ.',
                                       'Dẫn truyền thính giác và thăng bằng; u bao dây (u thần kinh thính) biểu hiện giảm thính lực tiến triển và chóng mặt.'),
    'Cochlear nerve': ('Dây ốc', 'Phần dẫn truyền thính giác của dây tiền đình-ốc tai, thân neuron nằm ở hạch ốc trong trục ốc.',
                       'Đưa tín hiệu chuyển cơ-điện của tế bào lông ốc tai vào nhân dây ốc thân não.'),
    'Vestibular nerve': ('Dây tiền đình', 'Phần dẫn truyền thăng bằng của dây tiền đình-ốc tai, thân neuron nằm ở hạch tiền đình.',
                         'Dẫn truyền thông tin vị trí đầu và gia tốc góc từ ống bán khuyên, túi bầu dục và túi cầu.'),
    'Glossopharyngeal nerve (IX)': ('Dây lưỡi-hầu (IX)', 'Dây thần kinh sọ số IX, ra sọ qua lỗ tĩnh mạch cảnh.',
                                    'Dẫn truyền vị giác và cảm giác chung 1/3 sau lưỡi, chi phối cơ trâm-hầu và tuyến mang tai; là nhánh hướng tâm của phản xạ hầu, đồng thời qua nhánh xoang cảnh điều hòa huyết áp.'),
    'Vagus nerve (X)': ('Dây lang thang (X)', 'Dây thần kinh sọ số X, có đường đi dài nhất, phân bố rộng nhất, ra sọ qua lỗ tĩnh mạch cảnh rồi đi xuống ngực bụng.',
                        'Chi phối cơ hầu họng và nội tạng ngực bụng, làm chậm nhịp tim, thúc đẩy tiêu hóa; là thân chính của hệ phó giao cảm.'),
    'Accessory nerve (XI)': ('Dây phụ (XI)', 'Dây thần kinh sọ số XI, do rễ sọ và rễ tủy hợp thành rồi ra sọ qua lỗ tĩnh mạch cảnh.',
                             'Chi phối cơ ức-đòn-chũm và cơ thang; tổn thương trong phẫu thuật cổ có thể gây yếu nhún vai và vai cánh.'),
    'Hypoglossal nerve (XII)': ('Dây dưới lưỡi (XII)', 'Dây thần kinh sọ số XII, ra sọ qua ống dưới lưỡi.',
                                'Chi phối toàn bộ cơ trong lưỡi và hầu hết cơ ngoài lưỡi, điều khiển thè thụt lưỡi và động tác nói, nuốt.'),

    # ================= Đám rối cánh tay và thần kinh chi trên =================
    'Roots of brachial plexus': ('Rễ đám rối cánh tay', 'Phần khởi đầu đám rối cánh tay do nhánh trước dây thần kinh C5–8 và T1 tạo thành.',
                                 'Tập hợp toàn bộ sợi thần kinh chi phối chi trên, là điểm khởi đầu của đám rối cánh tay.'),
    'Superior trunk of brachial plexus': ('Thân trên đám rối cánh tay', 'Do nhánh trước C5 và C6 hợp thành, nằm trong khe cơ bậc thang.',
                                          'Chứa sợi chính của dạng vai, gấp khuỷu; kéo do chấn thương sản khoa có thể gây liệt Erb ("bàn tay bồi bàn").'),
    'Middle trunk of brachial plexus': ('Thân giữa đám rối cánh tay', 'Sự kéo dài đơn độc của nhánh trước C7.',
                                        'Chủ yếu tham gia tạo thành dây quay và rễ ngoài của dây giữa.'),
    'Inferior trunk of brachial plexus': ('Thân dưới đám rối cánh tay', 'Do nhánh trước C8 và T1 hợp thành, sát mặt trên xương sườn 1.',
                                          'Chứa sợi chi phối cơ nội tại bàn tay; tổn thương gây liệt Klumpke và bàn tay móng vuốt.'),
    'Anterior division of superior trunk of brachial plexus': ('Nhánh trước thân trên đám rối cánh tay', 'Bó sợi phía trước phân ra từ thân trên phía sau xương đòn.',
                                                              'Nhánh trước hợp thành bó ngoài, phân phối sợi cho nhóm cơ gấp chi trên.'),
    'Posterior division of superior trunk of brachial plexus': ('Nhánh sau thân trên đám rối cánh tay', 'Bó sợi phía sau phân ra từ thân trên.',
                                                               'Cùng các nhánh sau khác hợp thành bó sau, phân phối sợi cho nhóm cơ duỗi chi trên.'),
    'Anterior division of middle trunk of brachial plexus': ('Nhánh trước thân giữa đám rối cánh tay', 'Bó sợi phía trước phân ra từ thân giữa.',
                                                            'Tham gia tạo thành bó ngoài, cung cấp cho cơ gấp cẳng tay và dây giữa.'),
    'Posterior division of middle trunk of brachial plexus': ('Nhánh sau thân giữa đám rối cánh tay', 'Bó sợi phía sau phân ra từ thân giữa.',
                                                             'Tham gia tạo thành bó sau, cung cấp cho cơ duỗi chi trên.'),
    'Anterior division of inferior trunk of brachial plexus': ('Nhánh trước thân dưới đám rối cánh tay', 'Bó sợi phía trước phân ra từ thân dưới.',
                                                              'Kéo dài đơn độc thành bó trong, cung cấp cho cơ nội tại bàn tay và cơ gấp phía trụ cẳng tay.'),
    'Posterior division of inferior trunk of brachial plexus': ('Nhánh sau thân dưới đám rối cánh tay', 'Bó sợi phía sau phân ra từ thân dưới.',
                                                               'Tham gia tạo thành bó sau.'),
    'Posterior cord of brachial plexus': ('Bó sau đám rối cánh tay', 'Do ba nhánh sau của các thân hợp thành, nằm phía sau động mạch nách.',
                                          'Phát dây nách và dây quay, cùng dây dưới vai, dây lưng ngực, chi phối toàn bộ cơ duỗi chi trên.'),
    'Dorsal scapular nerve': ('Dây lưng vai', 'Khởi từ rễ C5, xuyên cơ bậc thang giữa đi ra sau.',
                              'Chi phối cơ thoi và cơ nâng vai, làm xương vai khép và nâng.'),
    'Long thoracic nerve': ('Dây ngực dài', 'Khởi từ rễ C5–C7, đi xuống thành bên lồng ngực.',
                            'Chi phối cơ răng trước; tổn thương gây "vai cánh", là dây cần bảo vệ trong nạo hạch nách ung thư vú.'),
    'Subclavian nerve': ('Dây dưới đòn', 'Nhánh nhỏ khởi từ thân trên đám rối cánh tay.',
                         'Chi phối cơ dưới đòn.'),
    'Suprascapular nerve': ('Dây trên vai', 'Khởi từ thân trên đám rối cánh tay, qua khuyết vai vào hố trên gai.',
                            'Chi phối cơ trên gai và dưới gai, hoàn thành khởi động dạng vai và xoay ngoài; dễ bị chèn ép tại khuyết vai.'),
    'Lateral pectoral nerve': ('Dây ngực ngoài', 'Khởi từ bó ngoài đám rối cánh tay, xuyên mạc đòn-ngực ra trước.',
                               'Chi phối cơ ngực lớn, tham gia khép và gấp trước cánh tay.'),
    'Medial pectoral nerve': ('Dây ngực trong', 'Khởi từ bó trong đám rối cánh tay.',
                              'Chi phối cơ ngực nhỏ và phần dưới cơ ngực lớn.'),
    'Superior subscapular nerve': ('Dây dưới vai trên', 'Nhánh ngắn khởi từ bó sau đám rối cánh tay.',
                                   'Chi phối phần trên cơ dưới vai, xoay trong cánh tay.'),
    'Inferior subscapular nerve': ('Dây dưới vai dưới', 'Khởi từ bó sau đám rối cánh tay, đi xuống phần dưới cơ dưới vai và cơ tròn lớn.',
                                   'Chi phối phần dưới cơ dưới vai và cơ tròn lớn, hoàn thành xoay trong và khép cánh tay.'),
    'Thoracodorsal nerve': ('Dây lưng ngực', 'Khởi từ bó sau đám rối cánh tay, đi xuống dọc bờ ngoài xương vai.',
                            'Chi phối cơ lưng rộng; cần bảo vệ cùng dây ngực dài trong phẫu thuật nách.'),
    'Musculocutaneous nerve': ('Dây cơ-da', 'Khởi từ bó ngoài đám rối cánh tay, xuyên cơ mỏm quạ-cánh tay rồi đi giữa cơ nhị đầu và cơ cánh tay.',
                               'Chi phối nhóm cơ gấp trước cánh tay, nhánh tận là dây da ngoài cẳng tay.'),
    'Axillary nerve': ('Dây nách', 'Khởi từ bó sau đám rối cánh tay, cùng mạch máu quay sau cánh tay xuyên lỗ tứ giác vòng quanh cổ phẫu thuật xương cánh tay.',
                       'Chi phối cơ delta và cơ tròn nhỏ; gãy cổ phẫu thuật xương cánh tay hoặc trật khớp vai dễ tổn thương gây "vai vuông" và yếu dạng.'),
    'Muscular branches of axillary nerve': ('Nhánh cơ của dây nách', 'Nhánh vận động phát ra sau khi dây nách vòng quanh cổ phẫu thuật xương cánh tay.',
                                            'Chi phối cơ delta và cơ tròn nhỏ, hoàn thành dạng và xoay ngoài cánh tay.'),
    'Superior lateral brachial cutaneous nerve': ('Dây da ngoài trên cánh tay', 'Nhánh da của dây nách, nông hóa quanh bờ sau cơ delta.',
                                                  'Dẫn truyền cảm giác da ngoài vai ("vùng huy chương"), là vùng định vị kiểm tra dây nách.'),
    'Inferior lateral brachial cutaneous nerve': ('Dây da ngoài dưới cánh tay', 'Nhánh da phát ra từ dây quay ở đoạn giữa cánh tay.',
                                                  'Dẫn truyền cảm giác da ngoài dưới cánh tay.'),
    'Medial brachial cutaneous nerve': ('Dây da trong cánh tay', 'Dây da mảnh khởi từ bó trong đám rối cánh tay.',
                                        'Dẫn truyền cảm giác da trong cánh tay.'),
    'Medial antebrachial cutaneous nerve': ('Dây da trong cẳng tay', 'Khởi từ bó trong đám rối cánh tay, đi xuống cùng động mạch cánh tay.',
                                            'Dẫn truyền cảm giác da trong cẳng tay.'),
    'Anterior branch of medial antebrachial cutaneous nerve': ('Nhánh trước dây da trong cẳng tay',
                                                              'Nhánh lòng bàn tay phân ra từ dây da trong cẳng tay ở khuỷu.',
                                                              'Dẫn truyền cảm giác da mặt trước trong cẳng tay.'),
    'Posterior branch of medial antebrachial cutaneous nerve': ('Nhánh sau dây da trong cẳng tay',
                                                               'Nhánh lưng phân ra từ dây da trong cẳng tay.',
                                                               'Dẫn truyền cảm giác da mặt sau trong cẳng tay.'),
    'Lateral antebrachial cutaneous nerve': ('Dây da ngoài cẳng tay', 'Nhánh tận của dây cơ-da sau khi xuyên ra ngoài gân cơ nhị đầu.',
                                             'Dẫn truyền cảm giác da ngoài (phía quay) cẳng tay.'),
    'Posterior antebrachial cutaneous nerve': ('Dây da sau cẳng tay', 'Nhánh da phát ra từ dây quay ở vùng sau cánh tay.',
                                               'Dẫn truyền cảm giác da mặt sau cẳng tay.'),
    'Median nerve': ('Dây giữa', 'Do một rễ từ bó trong và một rễ từ bó ngoài hợp thành, đi xuống theo rãnh trong cơ nhị đầu qua ống cổ tay vào lòng bàn tay.',
                     'Chi phối hầu hết cơ gấp cẳng tay và cơ ô mô cái, cảm giác phân bố ba ngón rưỡi phía quay lòng bàn tay; tổn thương gây "bàn tay khỉ" và hội chứng ống cổ tay.'),
    'Muscular branches of median nerve': ('Nhánh cơ của dây giữa', 'Nhánh vận động phát ra từ dây giữa ở cẳng tay.',
                                          'Chi phối hầu hết cơ nhóm trước cẳng tay như cơ sấp tròn, cơ gấp cổ tay quay, cơ gấp ngón nông.'),
    'Anterior interosseous nerve of forearm': ('Dây gian cốt trước cẳng tay', 'Nhánh sâu phát ra từ dây giữa phần trên cẳng tay, đi sát màng gian cốt xuống.',
                                               'Chi phối cơ gấp dài ngón cái, nửa quay cơ gấp ngón sâu và cơ sấp vuông; tổn thương không thể làm cử chỉ "OK" bằng ngón cái và trỏ.'),
    'Palmar branch of median nerve': ('Nhánh lòng bàn tay của dây giữa', 'Nhánh da phát ra gần ống cổ tay từ dây giữa, không đi qua ống cổ tay.',
                                      'Dẫn truyền cảm giác da phía quay lòng bàn tay; do không xuyên ống cổ tay nên cảm giác vùng này thường không bị ảnh hưởng trong hội chứng ống cổ tay.'),
    'Common palmar digital branches of median nerve': ('Các dây ngón lòng bàn tay chung của dây giữa', 'Ba nhánh chung phân ra sau khi dây giữa ra ống cổ tay.',
                                                       'Gần đầu xương bàn tay lại chia thành dây ngón lòng bàn tay riêng, đồng thời chi phối hai cơ giun phía quay.'),
    'Proper palmar digital branches of median nerve': ('Các dây ngón lòng bàn tay riêng của dây giữa', 'Nhánh tận chạy dọc hai bên ngón tay.',
                                                       'Dẫn truyền cảm giác da mặt lòng và mặt lưng đốt giữa, xa của ba ngón rưỡi phía quay.'),
    '(Communicating branch of median nerve with ulnar nerve)': ('Nhánh thông thương dây giữa với dây trụ',
                                                                'Nhánh thông thương biến đổi giữa dây giữa và dây trụ trong lòng bàn tay (nối Riche–Cannieu).',
                                                                'Làm biến đổi chi phối thần kinh của cơ nội tại bàn tay, có thể giải thích một số trường hợp tổn thương dây trụ triệu chứng nhẹ.'),
    'Ulnar nerve': ('Dây trụ', 'Khởi từ bó trong đám rối cánh tay, đi xuống qua rãnh dây trụ phía sau mỏm trên trong xương cánh tay (ống khuỷu) đến bàn tay.',
                    'Chi phối cơ gấp phía trụ cẳng tay và hầu hết cơ nội tại bàn tay, cảm giác phân bố một ngón rưỡi phía trụ; tổn thương gây "bàn tay móng vuốt", va vào rãnh dây trụ gây "tê nhức".'),
    'Muscular branches of ulnar nerve': ('Nhánh cơ của dây trụ', 'Nhánh vận động phát ra từ dây trụ phần trên cẳng tay.',
                                         'Chi phối cơ gấp cổ tay trụ và nửa trụ cơ gấp ngón sâu.'),
    'Dorsal branch of ulnar nerve': ('Nhánh lưng bàn tay của dây trụ', 'Nhánh da quay ra lưng từ dây trụ phần dưới cẳng tay.',
                                     'Dẫn truyền cảm giác da nửa trụ mặt lưng bàn tay và mặt lưng đốt gần một ngón rưỡi phía trụ.'),
    'Palmar branch of ulnar nerve': ('Nhánh lòng bàn tay của dây trụ', 'Nhánh da mảnh phát ra phía trên cổ tay từ dây trụ.',
                                     'Dẫn truyền cảm giác da vùng ô mô út phía trụ lòng bàn tay.'),
    'Superficial branch of ulnar nerve': ('Nhánh nông của dây trụ', 'Nhánh cảm giác phân ra sau khi dây trụ qua ống trụ cổ tay.',
                                          'Chi phối cơ gan tay ngắn và dẫn truyền cảm giác mặt lòng một ngón rưỡi phía trụ.'),
    'Deep branch of ulnar nerve': ('Nhánh sâu của dây trụ', 'Nhánh vận động quay vào sâu lòng bàn tay sau khi dây trụ qua ống trụ cổ tay.',
                                   'Chi phối toàn bộ cơ gian cốt, hai cơ giun phía trụ, cơ ô mô út và cơ khép ngón cái, là then chốt của động tác tinh tế bàn tay.'),
    'Common palmar digital branches of ulnar nerve': ('Các dây ngón lòng bàn tay chung của dây trụ', 'Nhánh chung phân ra từ nhánh nông dây trụ ở lòng bàn tay.',
                                                      'Lại chia thành dây ngón lòng bàn tay riêng phân bố ngón tay phía trụ.'),
    'Proper palmar digital branches of ulnar nerve': ('Các dây ngón lòng bàn tay riêng của dây trụ', 'Nhánh tận chạy dọc bờ trụ ngón út và ngón nhẫn.',
                                                      'Dẫn truyền cảm giác da mặt lòng một ngón rưỡi phía trụ.'),
    'Dorsal digital branches of ulnar nerve': ('Các dây ngón lưng của dây trụ', 'Nhánh tận của nhánh lưng bàn tay dây trụ.',
                                               'Dẫn truyền cảm giác da mặt lưng đốt gần ngón tay phía trụ bàn tay.'),
    'Radial nerve': ('Dây quay', 'Nhánh lớn nhất của bó sau đám rối cánh tay, đi vòng theo rãnh dây quay xương cánh tay ra ngoài cánh tay.',
                     'Chi phối toàn bộ cơ duỗi chi trên; gãy đoạn giữa xương cánh tay dễ tổn thương, biểu hiện điển hình "cổ tay rủ".'),
    'Muscular branches of radial nerve': ('Nhánh cơ của dây quay', 'Nhánh vận động phát ra dọc đường đi của dây quay.',
                                          'Chi phối cơ tam đầu cánh tay, cơ khuỷu, cơ cánh tay-quay và cơ duỗi cổ tay quay dài.'),
    'Deep branch of radial nerve': ('Nhánh sâu của dây quay', 'Nhánh vận động phân ra ở khuỷu từ dây quay, xuyên cơ sấp sau đến vùng sau cẳng tay.',
                                    'Chi phối nhóm cơ duỗi sau cẳng tay; có thể bị chèn ép tại cung gân cơ sấp sau.'),
    'Posterior interosseous nerve of forearm': ('Dây gian cốt sau cẳng tay', 'Sự kéo dài của nhánh sâu dây quay sau khi xuyên ra khỏi cơ sấp sau, đi sát màng gian cốt xuống.',
                                                'Chi phối nhóm cơ sâu sau cẳng tay; tổn thương biểu hiện yếu duỗi ngón trong khi duỗi cổ tay còn, không có rối loạn cảm giác.'),
    'Superficial branch of radial nerve': ('Nhánh nông của dây quay', 'Nhánh cảm giác phân ra ở khuỷu từ dây quay, đi xuống cùng động mạch quay.',
                                           'Dẫn truyền cảm giác da nửa quay mặt lưng bàn tay và mặt lưng đốt gần hai ngón rưỡi phía quay.'),
    'Dorsal digital branches of radial nerve': ('Các dây ngón lưng của dây quay', 'Nhánh tận của nhánh nông dây quay.',
                                                'Dẫn truyền cảm giác da mặt lưng đốt gần ngón tay phía quay bàn tay.'),

    # ================= Thần kinh thân và chi dưới =================
    'Intercostal nerves': ('Các dây gian sườn', 'Nhánh trước dây thần kinh ngực 1–11, đi trong rãnh sườn của khe gian sườn tương ứng.',
                           'Chi phối cơ gian sườn và cơ thành bụng, đồng thời phân bố cảm giác da thành ngực bụng rõ ràng theo đoạn.'),
    'Iliohypogastric nerve': ('Dây chậu-hạ vị', 'Khởi từ đám rối thắt lưng (T12, L1), chạy chéo giữa các cơ thành bụng.',
                              'Chi phối cơ thành bụng và dẫn truyền cảm giác da hạ vị cùng ngoài mông; dễ bị tổn thương trong phẫu thuật thoát vị bẹn.'),
    'Ilio-inguinal nerve': ('Dây chậu-bẹn', 'Khởi từ đám rối thắt lưng (L1), đi dưới dây chậu-hạ vị và xuyên ống bẹn.',
                            'Chi phối phần dưới cơ thành bụng, dẫn truyền cảm giác da vùng bẹn và phần trên cơ quan sinh dục ngoài.'),
    'Genitofemoral nerve': ('Dây sinh dục-đùi', 'Khởi từ đám rối thắt lưng (L1, L2), xuyên mặt trước cơ thắt lưng lớn đi xuống.',
                            'Chia nhánh sinh dục và nhánh đùi, lần lượt chi phối cơ nâng tinh và dẫn truyền cảm giác da vùng tam giác đùi.'),
    'Genital branch of genitofemoral nerve': ('Nhánh sinh dục của dây sinh dục-đùi', 'Nhánh tận trong của dây sinh dục-đùi, qua vòng sâu ống bẹn vào ống.',
                                              'Chi phối cơ nâng tinh, là nhánh ly tâm của phản xạ nâng tinh.'),
    'Femoral branch of genitofemoral nerve': ('Nhánh đùi của dây sinh dục-đùi', 'Nhánh tận ngoài của dây sinh dục-đùi, qua khe mạch máu đến đùi.',
                                              'Dẫn truyền cảm giác da phần trên tam giác đùi, là nhánh hướng tâm của phản xạ nâng tinh.'),
    'Lateral femoral cutaneous nerve': ('Dây da ngoài đùi', 'Khởi từ đám rối thắt lưng (L2, L3), qua phía trong gai chậu trước trên xuyên mặt sâu dây chằng bẹn.',
                                        'Dẫn truyền cảm giác da ngoài đùi; bị ép tại dây chằng bẹn gây chứng đau đùi dị cảm.'),
    'Femoral nerve': ('Dây đùi', 'Nhánh lớn nhất của đám rối thắt lưng (L2–L4), qua khe cơ vào tam giác đùi.',
                      'Chi phối cơ thắt lưng chậu và nhóm cơ duỗi trước đùi (cơ tứ đầu đùi), dẫn truyền cảm giác da mặt trước đùi và trong cẳng chân; tổn thương không thể duỗi gối.'),
    'Anterior cutaneous branches of femoral nerve': ('Các nhánh da trước của dây đùi', 'Chuỗi nhánh da phát ra từ dây đùi trong tam giác đùi.',
                                                     'Dẫn truyền cảm giác da mặt trước và trong đùi.'),
    'Saphenous nerve': ('Dây hiển', 'Nhánh da dài nhất của dây đùi, xuyên ống cơ khép rồi đi cùng tĩnh mạch hiển lớn đến mặt trong bàn chân.',
                        'Dẫn truyền cảm giác da trong gối, trong cẳng chân và bờ trong bàn chân, là nhánh cảm giác tận xa nhất của dây đùi.'),
    'Infrapatellar branch of saphenous nerve': ('Nhánh dưới bánh chè của dây hiển', 'Nhánh da ngang phát ra từ dây hiển ở gối.',
                                                'Dẫn truyền cảm giác da dưới bánh chè; vết mổ khớp gối thường tổn thương nhánh này gây tê cục bộ.'),
    'Medial crural cutaneous branches of saphenous nerve': ('Các nhánh da trong cẳng chân của dây hiển', 'Các nhánh phát ra dọc mặt trong cẳng chân từ dây hiển.',
                                                           'Dẫn truyền cảm giác da mặt trong cẳng chân.'),
    'Obturator nerve': ('Dây bịt', 'Khởi từ đám rối thắt lưng (L2–L4), qua ống bịt ra khỏi khung chậu đến mặt trong đùi.',
                        'Chi phối nhóm cơ khép đùi, dẫn truyền cảm giác da trong đùi; đau bệnh khớp háng có thể lan đến trong gối qua dây này.'),
    'Anterior branch of obturator nerve': ('Nhánh trước của dây bịt', 'Nhánh đi mặt trước cơ khép ngắn sau khi dây bịt ra ống bịt.',
                                           'Chi phối cơ khép dài, khép ngắn và cơ thon, đồng thời phát nhánh da đến mặt trong đùi.'),
    'Posterior branch of obturator nerve': ('Nhánh sau của dây bịt', 'Nhánh đi mặt sau cơ khép ngắn của dây bịt.',
                                            'Chi phối cơ bịt ngoài và cơ khép lớn, đồng thời phát nhánh khớp đến khớp gối.'),
    'Superior gluteal nerve': ('Dây mông trên', 'Khởi từ đám rối cùng, ra khung chậu qua lỗ trên cơ hình lê.',
                               'Chi phối cơ mông giữa, mông nhỏ và cơ căng mạc đùi; tổn thương khi đứng một chân khung chậu nghiêng về bên đối diện.'),
    'Nerve to piriformis muscle': ('Dây cơ hình lê', 'Nhánh cơ ngắn phát ra từ đám rối cùng.',
                                   'Chi phối cơ hình lê, tham gia xoay ngoài đùi.'),
    'Nerve to quadratus femoris muscle': ('Dây cơ vuông đùi', 'Nhánh cơ phát ra từ đám rối cùng, đi xuống mặt sâu dây thần kinh ngồi.',
                                          'Chi phối cơ vuông đùi và cơ sinh đôi dưới, làm xoay ngoài đùi.'),
    'Posterior femoral cutaneous nerve': ('Dây da sau đùi', 'Khởi từ đám rối cùng, ra khung chậu qua lỗ dưới cơ hình lê đi mặt sâu cơ mông lớn.',
                                          'Dẫn truyền cảm giác da phần dưới mông, đáy chậu và mặt sau đùi.'),
    'Anterior root of posterior femoral cutaneous nerve': ('Rễ trước của dây da sau đùi', 'Sợi khởi nguồn phía bụng của dây da sau đùi (S2, S3).',
                                                           'Tham gia tạo thành dây da sau đùi, dẫn truyền cảm giác mặt sau đùi.'),
    'Posterior root of posterior femoral cutaneous nerve': ('Rễ sau của dây da sau đùi', 'Sợi khởi nguồn phía lưng của dây da sau đùi (S1, S2).',
                                                            'Tham gia tạo thành dây da sau đùi, dẫn truyền cảm giác da phần dưới mông.'),
    'Pudendal nerve': ('Dây thẹn', 'Khởi từ đám rối cùng (S2–S4), ra khung chậu qua lỗ dưới cơ hình lê rồi vòng quanh gai ngồi qua lỗ ngồi nhỏ vào đáy chậu.',
                       'Chi phối cơ đáy chậu và cơ thắt ngoài hậu môn, niệu đạo, dẫn truyền cảm giác cơ quan sinh dục ngoài; là đích gây tê dây thẹn khi đẻ.'),
    'Sciatic nerve': ('Dây thần kinh ngồi', 'Dây to và dài nhất cơ thể, khởi từ đám rối cùng, ra khung chậu qua lỗ dưới cơ hình lê đi xuống mặt sau đùi.',
                      'Chi phối nhóm sau đùi cùng toàn bộ cơ và hầu hết cảm giác da cẳng chân, bàn chân; bị ép gây đau thần kinh ngồi lan dọc mặt sau chi dưới.'),
    'Tibial nerve': ('Dây chày', 'Sự kéo dài trực tiếp của dây thần kinh ngồi, đi xuống giữa hố khoeo xuyên cung gân cơ dép đến vùng sau cẳng chân.',
                     'Chi phối nhóm sau cẳng chân và cơ lòng bàn chân; tổn thương không thể gấp bàn chân, gây "bàn chân móc".'),
    'Medial sural cutaneous nerve': ('Dây da trong bắp chân', 'Nhánh da phát ra từ dây chày ở hố khoeo, đi xuống mặt sau cẳng chân.',
                                     'Cùng nhánh thông thương của dây mác chung hợp thành dây bắp chân, dẫn truyền cảm giác mặt sau cẳng chân.'),
    'Sural nerve': ('Dây bắp chân', 'Do dây da trong bắp chân và nhánh thông thương dây mác chung hợp thành, đi cùng tĩnh mạch hiển nhỏ qua sau mắt cá ngoài đến mặt ngoài bàn chân.',
                    'Dẫn truyền cảm giác da mặt sau ngoài cẳng chân và bờ ngoài bàn chân; do vị trí nông và mất chức năng ít sau lấy, là nguồn ghép và sinh thiết thần kinh dùng nhiều nhất.'),
    'Medial plantar nerve': ('Dây lòng bàn chân trong', 'Nhánh tận lớn hơn phân ra từ dây chày trong ống cổ chân.',
                             'Chi phối cơ dạng ngón cái, cơ gấp ngắn ngón và dẫn truyền cảm giác lòng bàn chân trong cùng ba ngón rưỡi trong, tương đương dây giữa bàn tay.'),
    'Lateral plantar nerve': ('Dây lòng bàn chân ngoài', 'Nhánh tận nhỏ hơn phân ra từ dây chày trong ống cổ chân.',
                              'Chi phối hầu hết cơ nội tại lòng bàn chân, dẫn truyền cảm giác lòng bàn chân ngoài và một ngón rưỡi ngoài, tương đương dây trụ bàn tay.'),
    'Common plantar digital branches of medial plantar nerve': ('Các dây ngón lòng bàn chân chung của dây lòng bàn chân trong',
                                                               'Ba nhánh chung phân ra từ dây lòng bàn chân trong.',
                                                               'Lại chia thành dây ngón lòng bàn chân riêng phân bố các ngón lòng bàn chân trong.'),
    'Proper plantar digital branches of medial plantar nerve': ('Các dây ngón lòng bàn chân riêng của dây lòng bàn chân trong',
                                                               'Nhánh tận chạy dọc bờ đối diện các ngón.',
                                                               'Dẫn truyền cảm giác da mặt lòng ba ngón rưỡi trong.'),
    'Common plantar digital branches of lateral plantar nerve': ('Các dây ngón lòng bàn chân chung của dây lòng bàn chân ngoài',
                                                                'Nhánh chung phân ra từ nhánh nông dây lòng bàn chân ngoài.',
                                                                'Lại chia thành nhánh riêng phân bố các ngón lòng bàn chân ngoài; bị ép tại kẽ ngón 3 gây u thần kinh Morton.'),
    'Proper plantar digital branches of lateral plantar nerve': ('Các dây ngón lòng bàn chân riêng của dây lòng bàn chân ngoài',
                                                                'Nhánh tận của dây lòng bàn chân ngoài.',
                                                                'Dẫn truyền cảm giác da mặt lòng một ngón rưỡi ngoài.'),
    'Common fibular nerve': ('Dây mác chung', 'Nhánh tận khác của dây thần kinh ngồi, đi xuống dọc trong gân cơ nhị đầu đùi vòng quanh cổ xương mác.',
                             'Chia thành dây mác nông và dây mác sâu; tại cổ xương mác vị trí nông nhất, là dây dễ tổn thương nhất toàn thân, tổn thương gây bàn chân rủ và dáng đi bước cao.'),
    'Superficial fibular nerve': ('Dây mác nông', 'Nhánh của dây mác chung, đi giữa các cơ mác mặt ngoài cẳng chân.',
                                  'Chi phối cơ mác dài, ngắn làm lật ngoài bàn chân, nhánh da dẫn truyền cảm giác da dưới ngoài cẳng chân và hầu hết mặt lưng bàn chân.'),
    'Deep fibular nerve': ('Dây mác sâu', 'Nhánh của dây mác chung, xuyên cơ mác dài đến vùng trước cẳng chân đi cùng mạch máu chày trước xuống.',
                           'Chi phối nhóm cơ trước cẳng chân hoàn thành duỗi mu chân và duỗi ngón; cảm giác chỉ phân bố mảnh da nhỏ giữa ngón 1 và 2.'),
    'Muscular branches of deep fibular nerve': ('Nhánh cơ của dây mác sâu', 'Nhánh vận động phát ra từ dây mác sâu ở vùng trước cẳng chân.',
                                                'Chi phối cơ chày trước, cơ duỗi dài ngón, cơ duỗi dài ngón cái và cơ mác ba.'),
    'Sural communicating branch of common fibular nerve': ('Nhánh thông thương của dây mác chung', 'Nhánh da phát ra từ dây mác chung ở hố khoeo.',
                                                          'Hợp với dây da trong bắp chân tạo thành dây bắp chân.'),
    'Medial dorsal cutaneous nerve of foot': ('Dây da lưng trong bàn chân', 'Nhánh tận trong của dây mác nông.',
                                              'Dẫn truyền cảm giác da mặt lưng trong bàn chân và bờ trong ngón cái.'),
    'Intermediate dorsal cutaneous nerve of foot': ('Dây da lưng giữa bàn chân', 'Nhánh tận ngoài của dây mác nông.',
                                                    'Dẫn truyền cảm giác da phần giữa mặt lưng bàn chân và mặt lưng ngón 3–5.'),
    'Dorsal digital branches of superficial fibular nerve': ('Các dây ngón lưng của dây mác nông', 'Nhánh tận của các dây da lưng bàn chân.',
                                                            'Dẫn truyền cảm giác da mặt lưng đốt gần các ngón.'),
    'Dorsal digital branches of deep fibular nerve': ('Các dây ngón lưng của dây mác sâu', 'Nhánh da tận của dây mác sâu ở mặt lưng bàn chân.',
                                                     'Dẫn truyền cảm giác da bờ đối diện ngón 1 và 2, là vùng cảm giác duy nhất của dây mác sâu.'),

    # ================= Thần kinh tự chủ =================
    'Sympathetic trunk': ('Thân giao cảm', 'Chuỗi dọc hai bên cột sống do các hạch cạnh cột sống và nhánh gian hạch nối thành, từ nền sọ đến xương cụt.',
                          'Là đường đổi neuron và phân phối lại sợi trước hạch giao cảm, chi phối toàn bộ mạch máu, tuyến mồ hôi, cơ dựng lông và nội tạng.'),
    'Ganglia of sympathetic trunk': ('Các hạch thân giao cảm', 'Các hạch cạnh cột sống xếp thành chuỗi trên thân giao cảm, cổ 3, ngực 10–12.',
                                     'Sợi trước hạch giao cảm đổi neuron tại đây; phong bế hạch sao lấy hạch cổ dưới làm đích.'),
    'Sympathetic nerves': ('Thần kinh giao cảm', 'Phần của hệ thần kinh tự chủ thúc đẩy phản ứng stress huy động cơ thể.',
                           'Tăng nhịp tim, huyết áp, giãn đồng tử và phế quản, ức chế tiêu hóa, tức phản ứng "chiến hay chạy".'),

    # ================= Cơ quan thị giác =================
    'Cornea': ('Giác mạc', 'Phần trong suốt 1/6 trước nhãn cầu, không mạch máu nhưng rất giàu đầu mút thần kinh.',
               'Cấu trúc khúc xạ chính của mắt (khoảng 2/3 tổng lực khúc xạ), đồng thời do nhạy cảm cao kích hoạt phản xạ giác mạc bảo vệ.'),
    'Sclera': ('Củng mạc', 'Lớp sợi đặc màu trắng sữa 5/6 sau màng ngoài nhãn cầu, tức "lòng trắng mắt".',
               'Duy trì hình dạng nhãn cầu và áp lực nội nhãn, bảo vệ nội nhãn, đồng thời cung cấp điểm bám cho cơ ngoài mắt.'),
    'Iris': ('Mống mắt', 'Màng mỏng hình đĩa nằm sau giác mạc, trung tâm là đồng tử, chứa sắc tố quyết định màu mắt.',
             'Điều chỉnh kích thước đồng tử qua cơ thắt và cơ mở đồng tử, kiểm soát lượng ánh sáng vào mắt.'),
    'Lens': ('Thủy tinh thể', 'Thể trong suốt hai mặt lồi nằm sau mống mắt, giàu đàn hồi và không mạch máu thần kinh.',
             'Thay đổi độ cong nhờ cơ mi để điều tiết, làm vật ở xa gần đều tạo ảnh rõ; đục thủy tinh thể gây đục thủy tinh thể.'),
    'Zonular fibres': ('Sợi thể mi', 'Các sợi mảnh nối thể mi với xích đạo thủy tinh thể, còn gọi là dây chằng treo.',
                       'Treo cố định thủy tinh thể và truyền sự co của cơ mi đến thủy tinh thể để hoàn thành điều tiết.'),
    'Suspensory ligament of eyeball': ('Dây chằng treo nhãn cầu', 'Dây treo dạng mạc bao quanh phía dưới nhãn cầu trong ổ mắt, còn gọi là dây chằng Lockwood.',
                                       'Đỡ nhãn cầu từ dưới, ngay cả khi cắt bỏ xương hàm trên nhãn cầu vẫn không bị tụt xuống.'),
    'Retina': ('Võng mạc', 'Màng thần kinh lớp trong cùng thành nhãn cầu, chứa tế bào que và nón.',
               'Chuyển tín hiệu ánh sáng thành xung thần kinh (chuyển quang-điện), là điểm khởi đầu hình thành thị giác; hố trung tâm hoàng điểm có thị lực sắc bén nhất.'),
    'Vitreous body': ('Thủy tinh dịch', 'Chất keo trong suốt không màu chiếm 4/5 thể tích nhãn cầu, lấp đầy khoang sau thủy tinh thể.',
                      'Đỡ võng mạc dính vào hắc mạc và làm môi trường khúc xạ truyền ánh sáng; hóa lỏng kéo có thể gây bong võng mạc.'),
    'Anterior chamber of eyeball': ('Tiền phòng nhãn cầu', 'Khoang chứa thủy dịch giữa giác mạc và mống mắt.',
                                    'Thủy dịch tại đây nuôi dưỡng giác mạc và thủy tinh thể, đồng thời thoát qua mạng trabéculum góc tiền phòng để duy trì áp lực nội nhãn; tắc thoát gây glôcôm.'),
    'Anterior segment of eyeball': ('Đoạn trước nhãn cầu', 'Toàn bộ cấu trúc phía trước và gồm thủy tinh thể, chứa giác mạc, tiền hậu phòng và mống mắt.',
                                    'Hoàn thành khúc xạ chính của ánh sáng và điều chỉnh lượng ánh sáng vào.'),
    'Posterior segment of eyeball': ('Đoạn sau nhãn cầu', 'Toàn bộ cấu trúc phía sau thủy tinh thể, chứa thủy tinh dịch, võng mạc và hắc mạc.',
                                     'Chịu trách nhiệm cảm nhận và chuyển đổi ánh sáng, là nơi sản sinh tín hiệu thị giác.'),
    'Optic chiasm': ('Giao thị', 'Cấu trúc dẹt do hai dây thị bắt chéo một phần phía trên yên bướm.',
                     'Sợi từ võng mạc phía mũi hai mắt bắt chéo tại đây, làm mỗi bên não nhận thị trường đối bên; u tuyến yên chèn ép gây bán manh thái dương hai bên.'),
    'Optic tract': ('Dải thị', 'Bó sợi kéo dài ra sau từ giao thị đến thể gối ngoài.',
                    'Dẫn truyền toàn bộ thông tin thị giác của thị trường đối bên, tổn thương gây bán manh cùng tên.'),
    'Lacrimal gland': ('Tuyến lệ', 'Tuyến thanh dịch nằm trong hố tuyến lệ góc ngoài trên ổ mắt.',
                       'Bài tiết nước mắt bôi trơn và nuôi dưỡng giác mạc, rửa dị vật, lysozyme trong nước mắt có tác dụng diệt khuẩn.'),
    'Lacrimal canaliculus': ('Ống lệ', 'Ống nhỏ khởi từ điểm lệ bờ mi trên dưới, thông đến túi lệ.',
                             'Dẫn nước mắt bề mặt mắt vào túi lệ.'),
    'Ampulla of lacrimal canaliculus': ('Bóng ống lệ', 'Đoạn phình phần khởi đầu ống lệ.',
                                        'Tạo tác dụng bơm hút khi chớp mắt, hút nước mắt vào đường lệ.'),
    'Lacrimal sac': ('Túi lệ', 'Túi màng nằm trong hố túi lệ thành trong ổ mắt, đầu trên bịt.',
                     'Tạm chứa nước mắt từ ống lệ chảy vào rồi thải xuống ống mũi-lệ.'),
    'Nasolacrimal duct': ('Ống mũi-lệ', 'Ống kéo dài xuống từ túi lệ, mở vào ngách mũi dưới.',
                          'Dẫn nước mắt vào khoang mũi; khóc chảy nước mũi, tắc ống gây chảy nước mắt đều bắt nguồn từ đường này.'),

    # ================= Cơ quan tiền đình-ốc tai =================
    'Tympanic membrane': ('Màng nhĩ', 'Màng mỏng hình bầu dục bán trong suốt nằm đáy ống tai ngoài, ngăn cách tai ngoài với tai giữa.',
                          'Nhận sóng âm tạo rung động truyền cho chuỗi xương con, là mắt xích đầu tiên âm thanh từ không khí vào tai giữa.'),
    'Auditory tube': ('Vòi nhĩ', 'Ống nối hòm nhĩ với hầu mũi, người lớn dài khoảng 3,5cm.',
                      'Cân bằng áp suất hòm nhĩ với bên ngoài để màng nhĩ rung động bình thường; trẻ em ống ngắn thẳng nên nhiễm trùng đường hô hấp trên dễ biến chứng viêm tai giữa.'),
    'Cochlea': ('Ốc tai', 'Ống xương xoắn ốc hình vỏ ốc trong tai trong, quanh trục ốc khoảng 2,5 vòng.',
                'Vị trí của thụ thể thính giác; màng nền sắp xếp theo gradient tần số, thực hiện phân tích tần số âm thanh (học thuyết sóng chạy).'),
    'Vestibule': ('Tiền đình', 'Khoang hình bầu dục phần giữa mê đạo xương tai trong, nối ốc tai với ống bán khuyên.',
                  'Chứa túi bầu dục và túi cầu, cảm nhận vị trí tĩnh của đầu và gia tốc thẳng.'),

    # ================= Tổng thể =================
    'Nervous system & Sense organs': ('Hệ thần kinh và cơ quan cảm giác', 'Hệ thống xử lý thông tin cấu tạo bởi thần kinh trung ương, thần kinh ngoại biên cùng các thụ thể thị, thính, khứu, vị.',
                                      'Cảm nhận thay đổi môi trường trong ngoài, tích hợp thông tin và phát lệnh, thống nhất phối hợp hoạt động các hệ thống toàn thân, là cơ sở vật chất của ý thức, tư duy và cảm xúc.'),
}