# -*- coding: utf-8 -*-
"""Các mục từ hệ xương. Định dạng: Tên tiếng Anh: (Tên tiếng Việt, Giới thiệu, Chức năng)

Tên tiếng Việt dựa trên thuật ngữ giải phẫu học tiêu chuẩn.
"""

TERMS = {
    # ---------- Xương sọ ----------
    'Frontal bone': ('Xương trán', 'Xương dẹt tạo thành trán, thành trên ổ mắt và đáy hố sọ trước, bên trong chứa xoang trán.',
                     'Bảo vệ thùy trán, tạo thành trần ổ mắt và nâng đỡ phần trên khuôn mặt.'),
    'Parietal bone': ('Xương đỉnh', 'Xương dẹt hình tứ giác ở hai bên vòm sọ, mỗi bên một xương, tiếp nối nhau ở đường khớp dọc.',
                      'Tạo thành thành đỉnh và thành bên ổ sọ, bảo vệ bán cầu đại não.'),
    'Occipital bone': ('Xương chẩm', 'Xương dẹt phần sau dưới sọ, giữa có lỗ chẩm lớn.',
                       'Bảo vệ thùy chẩm và tiểu não; lỗ chẩm lớn là đường đi của hành não và tủy sống, lồi cầu chẩm tạo khớp chẩm-đốt đội với đốt đội.'),
    'Temporal bone': ('Xương thái dương', 'Xương phức hợp ở thành bên sọ, gồm phần vảy, phần nhĩ và phần đá, chứa cơ quan thính giác và thăng bằng.',
                      'Bảo vệ tai giữa và tai trong, tạo thành ổ khớp của khớp thái dương-hàm dưới, là trụ xương quan trọng của nền sọ.'),
    'Sphenoid bone': ('Xương bướm', 'Xương hình cánh bướm dang rộng nằm ở trung tâm nền sọ, phần giữa có yên bướm chứa tuyến yên.',
                      'Nối hố sọ trước, giữa và sau, cung cấp các lỗ cho nhiều dây thần kinh sọ và mạch máu ra vào ổ sọ.'),
    'Ethmoid bone': ('Xương sàng', 'Xương mỏng nhẹ nằm giữa hai ổ mắt, gồm bản sàng, bản đứng và mê đạo xương sàng.',
                     'Tạo thành trần khoang mũi và thành trong ổ mắt; các lỗ sàng trên bản sàng cho dây thần kinh khứu đi qua.'),
    'Maxilla': ('Xương hàm trên', 'Xương thành đôi tạo thành phần chính giữa mặt, bên trong chứa xoang hàm trên.',
                'Chứa cung răng trên, tạo thành thành dưới ổ mắt, thành ngoài khoang mũi và phần trước vòm miệng cứng.'),
    'Mandible': ('Xương hàm dưới', 'Xương duy nhất có thể cử động trong xương mặt, gồm thân và hai cành hàm dưới.',
                 'Chứa cung răng dưới, thực hiện động tác nhai, nói và nuốt qua khớp thái dương-hàm dưới.'),
    'Zygomatic bone': ('Xương gò má', 'Xương ở chỗ nhô má, nối xương hàm trên với xương thái dương.',
                       'Tạo thành cung gò má và thành ngoài ổ mắt, cung cấp điểm khởi đầu cho cơ nhai, quyết định đường nét bề rộng khuôn mặt.'),
    'Nasal bone': ('Xương mũi', 'Xương nhỏ hình chữ nhật thành đôi, tạo thành phần trên sống mũi.',
                   'Nâng đỡ hình dạng sống mũi, bảo vệ phần trên khoang mũi.'),
    'Lacrimal bone': ('Xương lệ', 'Xương nhỏ nhất, mỏng nhất ở phần trước thành trong ổ mắt.',
                      'Cùng xương hàm trên tạo thành hố túi lệ, chứa túi lệ và thông với ống mũi-lệ.'),
    'Palatine bone': ('Xương khẩu cái', 'Xương hình chữ L nằm phía sau xương hàm trên.',
                      'Tạo thành phần sau vòm miệng cứng, phần sau thành ngoài khoang mũi và phần sau đáy ổ mắt.'),
    'Vomer': ('Xương lá mía', 'Xương mỏng hình đầu lưỡi cày nằm ở đường giữa khoang mũi.',
              'Tạo thành phần sau dưới vách ngăn xương mũi, ngăn cách khoang mũi trái và phải.'),
    'Inferior nasal concha bone': ('Xương cuốn mũi dưới', 'Xương mỏng cuộn độc lập ở phần dưới thành ngoài khoang mũi.',
                                   'Mở rộng diện tích niêm mạc khoang mũi, sưởi ấm, làm ẩm và lọc bụi không khí hít vào.'),
    'Hyoid bone': ('Xương móng', 'Xương hình chữ U ở phần trước cổ, không khớp trực tiếp với xương khác, được treo bởi cơ và dây chằng.',
                   'Cung cấp điểm bám cho cơ lưỡi và nhóm cơ trên, dưới xương móng, là điểm tựa nâng thanh quản khi nuốt và phát âm.'),
    'Anterior cells of ethmoid bone': ('Các tế bào trước xương sàng', 'Nhóm tế bào chứa khí phần trước trong mê đạo xương sàng, tức xoang sàng trước.',
                                       'Làm nhẹ trọng lượng xương sọ, tham gia cộng hưởng phát âm, mở vào ngách mũi giữa.'),
    'Middle cells of ethmoid bone': ('Các tế bào giữa xương sàng', 'Nhóm tế bào chứa khí phần giữa trong mê đạo xương sàng, tức xoang sàng giữa.',
                                     'Tham gia hệ thống xoang cạnh mũi, mở vào ngách mũi giữa.'),
    'Posterior cells of ethmoid bone': ('Các tế bào sau xương sàng', 'Nhóm tế bào chứa khí phần sau trong mê đạo xương sàng, tức xoang sàng sau.',
                                        'Tham gia hệ thống xoang cạnh mũi, mở vào ngách mũi trên, kề cận ống thần kinh thị.'),
    'Sinus of frontal bone': ('Xoang trán', 'Khoang chứa khí thành đôi trong xương trán, mở vào ngách mũi giữa.',
                              'Làm nhẹ trọng lượng xương sọ, sưởi ấm không khí hít vào và tham gia cộng hưởng phát âm.'),
    'Sinus of sphenoid bone': ('Xoang bướm', 'Khoang chứa khí trong thân xương bướm, mở vào ngách bướm-sàng.',
                               'Làm nhẹ trọng lượng xương sọ và tham gia cộng hưởng; là đường phẫu thuật qua mũi cắt bỏ u tuyến yên.'),

    # ---------- Sụn thanh quản và mũi ----------
    'Thyroid cartilage': ('Sụn giáp', 'Sụn lớn nhất của thanh quản, do hai bản hình vuông hợp nhất ở đường giữa trước tạo thành yết hầu.',
                          'Tạo thành thành trước ngoài thanh quản, bảo vệ dây thanh và cung cấp điểm bám cho đầu trước dây thanh.'),
    'Cricoid cartilage': ('Sụn nhẫn', 'Sụn duy nhất tạo vòng hoàn chỉnh của thanh quản, nằm dưới sụn giáp.',
                          'Nâng đỡ khoang thanh quản, duy trì thông thoáng đường thở, là mốc quan trọng cho mở khí quản và chọc màng nhẫn-giáp.'),
    'Arytenoid cartilage': ('Sụn phễu', 'Sụn hình nón thành đôi nằm trên bản sụn nhẫn.',
                            'Mỏm thanh của nó là điểm bám đầu sau dây thanh, khi xoay thay đổi kích thước khe thanh môn để điều hòa phát âm.'),
    'Corniculate cartilage': ('Sụn sừng nhỏ', 'Một cặp sụn đàn hồi hình nón nhỏ nằm trên đỉnh sụn phễu.',
                              'Nằm trong nếp phễu-nắp thanh môn, tăng cường nâng đỡ đỉnh sụn phễu.'),
    'Nasal septal cartilage': ('Sụn vách ngăn mũi', 'Sụn trong suốt hình tứ giác tạo thành phần trước vách ngăn mũi.',
                               'Duy trì hình dạng đầu mũi và sống mũi, ngăn cách phần trước khoang mũi.'),
    'Lateral process of nasal septal cartilage': ('Mỏm ngoài của sụn vách ngăn mũi',
                                                  'Mỏm dạng bản kéo dài sang hai bên từ sụn vách ngăn mũi, tức sụn ngoài mũi.',
                                                  'Nâng đỡ hai bên sống mũi, duy trì sự mở của lỗ mũi trong (van mũi).'),
    'Major alar cartilage': ('Sụn cánh mũi lớn', 'Sụn hình chữ U bao quanh lỗ mũi, chia chân trong và chân ngoài.',
                             'Tạo hình đầu mũi và cánh mũi, duy trì sự mở của lỗ mũi.'),

    # ---------- Xương con tai ----------
    'Malleus': ('Xương búa', 'Xương ngoài cùng trong ba xương con tai giữa, cán dính vào mặt trong màng nhĩ.',
                'Truyền rung động của màng nhĩ đến xương đe, là mắt xích đầu tiên của chuỗi xương con dẫn truyền.'),
    'Incus': ('Xương đe', 'Xương con tai giữa nằm giữa xương búa và xương bàn đạp, hình giống đe thợ rèn.',
              'Tiếp nhận rung động từ xương búa, khuếch đại rồi truyền đến xương bàn đạp.'),
    'Stapes': ('Xương bàn đạp', 'Xương nhỏ nhất cơ thể, hình giống bàn đạp ngựa, đế gắn vào cửa sổ tiền đình.',
               'Truyền rung động vào ngoại dịch tai trong, hoàn thành sự khớp trở kháng âm thanh từ không khí sang chất lỏng.'),

    # ---------- Thân ----------
    'Manubrium of sternum': ('Chuôi xương ức', 'Đoạn trên cùng xương ức, bờ trên giữa là khuyết tĩnh mạch cảnh.',
                             'Tiếp nối với xương đòn và sụn sườn 1 tạo thành bờ trước lỗ trên lồng ngực; góc ức chỗ tiếp nối với thân xương ức là mốc đếm xương sườn.'),
    'Body of sternum': ('Thân xương ức', 'Phần thân chính đoạn giữa xương ức, hai bên tiếp nối sụn sườn 2–7.',
                        'Tạo thành phần chính thành trước lồng ngực, bảo vệ tim và mạch máu lớn, đồng thời là điểm lực của ấn ngực ngoài.'),
    'Xiphoid process': ('Mỏm kiếm', 'Mỏm nhỏ tận cùng dưới xương ức, thời thanh niên là sụn, về già dần hóa xương.',
                        'Cung cấp điểm bám cho cơ thẳng bụng, đường trắng bụng và cơ hoành, là mốc xương xác định vị trí ấn trong hồi sức tim phổi.'),
    'Sacrum': ('Xương cùng', 'Xương hình tam giác do 5 đốt sống cùng hợp nhất tạo thành, nằm giữa đốt sống thắt lưng và xương cụt.',
               'Nối cột sống với khung chậu, truyền trọng lượng thân trên qua khớp cùng-chậu xuống chi dưới; trong ống cùng là đường đi của đuôi ngựa.'),
    'Coccyx': ('Xương cụt', 'Xương nhỏ hình tam giác tận cùng cột sống do 3–4 đốt sống cụt thoái hóa hợp nhất tạo thành.',
               'Cung cấp điểm bám cho cơ sàn chậu, cơ thắt ngoài hậu môn và dây chằng củ-cùng, tham gia chịu lực khi ngồi.'),
    'Atlas (C1)': ('Đốt đội (C1)', 'Đốt sống cổ 1, hình vòng, không có thân đốt sống và mỏm gai.',
                   'Phía trên tạo khớp chẩm-đốt đội với lồi cầu chẩm, chịu trách nhiệm động tác gật đầu; như cái khay đỡ xương sọ.'),
    'Axis (C2)': ('Đốt trục (C2)', 'Đốt sống cổ 2, thân đốt sống hướng lên tạo thành mỏm răng.',
                  'Mỏm răng là trục dọc cho sự xoay của đốt đội, chịu trách nhiệm động tác lắc đầu, then chốt xoay cổ.'),
    'Hip bone': ('Xương hông', 'Xương không đều do xương chậu, xương ngồi và xương mu hợp nhất tại ổ cối tạo thành.',
                 'Cùng xương cùng và xương cụt tạo thành khung chậu, đỡ tạng bụng-chậu và truyền trọng lượng cơ thể xuống xương đùi.'),

    # ---------- Chi trên ----------
    'Clavicle': ('Xương đòn', 'Xương dài hình chữ S nằm ngang phía trước trên lồng ngực, toàn bộ có thể sờ dưới da.',
                 'Nâng đỡ chi trên ở phía ngoài thân, truyền lực từ chi trên đến xương trục, đồng thời bảo vệ đám rối cánh tay và mạch máu dưới đòn phía dưới.'),
    'Scapula': ('Xương vai', 'Xương dẹt hình tam giác dính vào mặt sau ngoài lồng ngực.',
                'Tạo khớp vai với chỏm xương cánh tay bằng ổ chảo, cung cấp điểm bám cho hơn mười cơ như nhóm cơ chóp xoay; sự trượt của nó trên thành ngực mở rộng đáng kể phạm vi vận động chi trên.'),
    'Humerus': ('Xương cánh tay', 'Xương dài duy nhất của cánh tay, phía trên tiếp xương vai, phía dưới tiếp xương trụ và xương quay.',
                'Tham gia tạo khớp vai và khớp khuỷu, cung cấp đòn bẩy cho nhóm cơ cánh tay; trong rãnh dây quay có dây thần kinh quay đi sát mặt xương.'),
    'Radius': ('Xương quay', 'Xương dài phía ngoài (phía ngón cái) cẳng tay, đầu trên nhỏ, đầu dưới lớn.',
               'Tạo khớp quay-trụ với xương trụ thực hiện sấp, ngửa cẳng tay; đầu dưới là thành phần chính của khớp cổ tay, đồng thời là vị trí gãy xương thường gặp nhất.'),
    'Ulna': ('Xương trụ', 'Xương dài phía trong (phía ngón út) cẳng tay, đầu trên to có mỏm khuỷu.',
             'Tạo khớp khuỷu với ròng rọc xương cánh tay, là trục chính ổn định cẳng tay; mỏm khuỷu là điểm bám tận của cơ tam đầu cánh tay.'),
    'Scaphoid bone': ('Xương thuyền', 'Xương ngoài cùng hàng gần xương cổ tay, hình giống thuyền nhỏ.',
                      'Nối cẳng tay với bàn tay, tham gia khớp quay-cổ tay; do nguồn máu vào từ đầu xa, sau gãy đầu gần dễ bị hoại tử thiếu máu.'),
    'Lunate bone': ('Xương nguyệt', 'Xương giữa hàng gần xương cổ tay, hình giống nửa mặt trăng.',
                    'Tạo thành trung tâm khớp quay-cổ tay, là xương cổ tay dễ bị trật nhất.'),
    'Triquetrum bone': ('Xương tháp', 'Xương hình nón trong cùng hàng gần xương cổ tay.',
                        'Tiếp nối với xương đậu và xương móc, tham gia ổn định phía trụ khớp cổ tay.'),
    'Pisiform bone': ('Xương đậu', 'Xương nhỏ nhất trong xương cổ tay, nằm mặt lòng xương tháp, thuộc xương vừng.',
                      'Nằm trong gân cơ gấp cổ tay trụ để tăng cánh tay đòn của cơ này, đồng thời tạo thành bờ trong ống trụ cổ tay.'),
    'Trapezium bone': ('Xương thang lớn', 'Xương ngoài cùng hàng xa xương cổ tay, tiếp nối với xương bàn tay 1.',
                       'Tạo khớp yên ngựa cổ tay-bàn ngón cái với xương bàn tay 1, là cơ sở giải phẫu của động tác đối ngón cái.'),
    'Trapezoid bone': ('Xương thang nhỏ', 'Xương hình nêm nhỏ nhất hàng xa xương cổ tay, tiếp nối với xương bàn tay 2.',
                       'Ổn định đáy xương bàn tay 2, tạo thành trục dọc vững chắc của lòng bàn tay.'),
    'Capitate bone': ('Xương cả', 'Xương lớn nhất trong xương cổ tay, nằm ở trung tâm cổ tay.',
                      'Làm trục trung tâm vận động khớp cổ tay, truyền lực từ cột ngón giữa lên cẳng tay.'),
    'Hamate bone': ('Xương móc', 'Xương trong cùng hàng xa xương cổ tay, mặt lòng có mỏm móc.',
                    'Móc của nó tạo thành bờ trong ống cổ tay và bờ ngoài ống trụ cổ tay, đồng thời cung cấp điểm bám cho dây chằng ngang cổ tay.'),

    # ---------- Chi dưới ----------
    'Femur': ('Xương đùi', 'Xương dài trong đùi, là xương dài nhất, khỏe nhất cơ thể người.',
              'Chỏm trên tạo khớp háng, đầu dưới tạo khớp gối, nâng đỡ và truyền toàn bộ tải trọng chi dưới.'),
    'Patella': ('Xương bánh chè', 'Xương vừng hình tam giác phía trước khớp gối, nằm trong gân cơ tứ đầu đùi.',
                'Tăng cánh tay đòn duỗi gối, nâng cao hiệu quả cơ tứ đầu đùi, đồng thời bảo vệ mặt trước khớp gối.'),
    'Tibia': ('Xương chày', 'Xương dài to phía trong cẳng chân, bờ trước sắc có thể sờ dưới da, thường gọi là xương mặt.',
              'Là xương chịu lực duy nhất của cẳng chân, truyền trọng lượng từ khớp gối đến khớp cổ chân.'),
    'Fibula': ('Xương mác', 'Xương dài mảnh phía ngoài cẳng chân, hầu như không chịu lực trực tiếp.',
               'Ổn định phía ngoài khớp cổ chân (mắt cá ngoài), cung cấp điểm bám cho nhóm cơ ngoài cẳng chân, trên lâm sàng thường dùng làm vùng cho xương ghép.'),
    'Talus': ('Xương sên', 'Xương cổ chân nằm giữa xương chày-mác và xương gót, bề mặt phần lớn là sụn khớp, không có cơ bám.',
              'Tạo khớp cổ chân, phân tán trọng lượng từ cẳng chân truyền ra trước sau bàn chân.'),
    'Calcaneus': ('Xương gót', 'Xương cổ chân lớn nhất phần sau bàn chân, tạo thành gót chân.',
                  'Khi đứng chịu trọng lượng cơ thể; củ xương gót phía sau là điểm bám tận của gân gót, là điểm lực đẩy đất.'),
    'Navicular bone': ('Xương thuyền bàn chân', 'Xương hình thuyền mặt trong bàn chân, nằm giữa xương sên và ba xương chêm.',
                       'Tạo thành đỉnh vòm dọc trong bàn chân, củ xương thuyền là điểm bám tận chính của gân cơ chày sau.'),
    'Cuboid bone': ('Xương lập phương', 'Xương hình khối nằm mặt ngoài bàn chân, giữa xương gót và xương bàn chân 4, 5.',
                    'Tạo thành vòm dọc ngoài bàn chân; rãnh mặt dưới chứa gân cơ mác dài.'),
    'Medial cuneiform bone': ('Xương chêm trong', 'Xương lớn nhất trong ba xương chêm, phía trước tiếp xương bàn chân 1.',
                              'Nâng đỡ vòm dọc trong bàn chân, là điểm bám tận của cơ chày trước và gân cơ mác dài.'),
    'Intermediate cuneiform bone': ('Xương chêm giữa', 'Xương nhỏ nhất trong ba xương chêm, phía trước tiếp xương bàn chân 2.',
                                    'Do vị trí thụt sau làm xương bàn chân 2 khảm vào mộng, tạo thành nền tảng ổn định của vòm ngang bàn chân.'),
    'Lateral cuneiform bone': ('Xương chêm ngoài', 'Nằm giữa xương chêm giữa và xương lập phương, phía trước tiếp xương bàn chân 3.',
                               'Tham gia tạo thành vòm ngang bàn chân, ổn định khớp cổ chân-bàn chân.'),
    'Sesamoid bones of foot': ('Xương vừng bàn chân', 'Xương nhỏ nằm trong gân, thường gặp nhất dưới chỏm xương bàn chân 1, xuất hiện thành đôi.',
                               'Giảm ma sát giữa gân và mặt xương, thay đổi hướng lực cơ, đồng thời chia sẻ áp lực dưới ngón cái trong giai đoạn đẩy bước đi.'),

    # ---------- Tổng thể ----------
    'Skeletal system': ('Hệ xương', 'Khung của cơ thể người do 206 xương và các liên kết của chúng tạo thành.',
                        'Nâng đỡ cơ thể, bảo vệ nội tạng, làm đòn bẩy cho vận động cơ, đồng thời dự trữ canxi, phospho và tạo máu trong tủy xương.'),
}