# -*- coding: utf-8 -*-
"""Các mục từ hệ nội tạng (tiêu hóa, hô hấp, tiết niệu, sinh dục, nội tiết). Định dạng: Tên tiếng Anh: (Tên tiếng Việt, Giới thiệu, Chức năng)"""

TERMS = {
    # ---------- Ống tiêu hóa ----------
    'Tongue': ('Lưỡi', 'Cơ quan dạng cơ nằm ở sàn miệng, bề mặt phủ các nhú lưỡi chứa nụ vị giác.',
               'Khuấy trộn thức ăn, hỗ trợ nuốt, là nơi chứa thụ thể vị giác, đồng thời là cấu trúc then chốt cho phát âm.'),
    'Gingiva': ('Nướu', 'Niêm mạc mô liên kết dày đặc bao quanh cổ răng và phủ mào xương ổ răng.',
                'Bít kín khe giữa răng và xương ổ răng, chống vi khuẩn xâm nhập và đệm lực nhai.'),
    'Soft palate': ('Vòm miệng mềm', 'Van cơ nằm sau vòm miệng cứng, bờ sau tự do và thõng xuống lưỡi gà.',
                    'Khi nuốt nâng lên bịt kín hầu mũi, ngăn thức ăn trào ngược vào khoang mũi; tham gia cộng hưởng âm thanh.'),
    'Uvula of palate': ('Lưỡi gà', 'Mấu nhỏ hình nón thõng xuống giữa bờ sau vòm miệng mềm, thường gọi là lưỡi gà.',
                        'Hỗ trợ vòm miệng mềm bịt kín hầu mũi, tham gia phát âm và kích hoạt phản xạ hầu.'),
    'Pharynx': ('Hầu', 'Ống cơ từ nền sọ xuống nối tiếp thực quản, là đường chung của tiêu hóa và hô hấp.',
                'Đưa thức ăn vào thực quản, không khí vào thanh quản, và nhờ vòng bạch huyết hầu tham gia phòng vệ miễn dịch.'),
    'Nasopharynx': ('Hầu mũi', 'Đoạn trên cùng của hầu, nằm sau khoang mũi, phía trên mặt phẳng vòm miệng mềm.',
                    'Chỉ thông khí, không chứa thức ăn; lỗ hầu của vòi nhĩ ở thành bên giúp cân bằng áp suất tai giữa với bên ngoài.'),
    'Oropharynx': ('Hầu miệng', 'Đoạn giữa của hầu, nằm giữa vòm miệng mềm và bờ trên nắp thanh môn.',
                   'Đường chung của thức ăn và không khí, amidan khẩu cái nằm ở thành bên tham gia miễn dịch.'),
    'Laryngopharynx': ('Hầu thanh quản', 'Đoạn dưới cùng của hầu, từ bờ trên nắp thanh môn đến bờ dưới sụn nhẫn nối tiếp thực quản.',
                       'Đưa viên thức ăn qua hố lê đưa vào thực quản, đồng thời đảm bảo lỗ thanh môn đóng khi nuốt.'),
    'Oesophagus': ('Thực quản', 'Ống cơ nối hầu với dạ dày, dài khoảng 25 cm, có ba chỗ hẹp sinh lý.',
                   'Nhu động đưa viên thức ăn vào dạ dày, chức năng cơ thắt đầu dưới ngăn trào ngược dịch dạ dày.'),
    'Stomach': ('Dạ dày', 'Phần phình to nhất của ống tiêu hóa, nằm ở vùng thượng vị trái, gồm tâm vị, đáy vị, thân vị, môn vị.',
                'Lưu trữ thức ăn, tiết acid hydrochloric và pepsinogen tiêu hóa sơ bộ protein, rồi đưa nhũ trấp từng đợt vào tá tràng.'),
    'Mucosa of stomach': ('Niêm mạc dạ dày', 'Lớp trong cùng của thành dạ dày, có nhiều hố vị và tuyến vị, tạo các nếp gấp dọc.',
                          'Tiết acid hydrochloric, pepsinogen, yếu tố nội và chất nhầy; hàng rào nhầy–bicarbonat bảo vệ thành dạ dày khỏi tự tiêu hóa.'),
    'Duodenum': ('Tá tràng', 'Đoạn đầu hình chữ C của ruột non, dài khoảng 25 cm, bao quanh đầu tụy.',
                 'Nhận mật và dịch tụy trung hòa acid dạ dày, là nơi khởi đầu tiêu hóa lipid và protein, cũng là đoạn hấp thu chính của sắt và canxi.'),
    'Jejunum': ('Hỗng tràng', 'Đoạn giữa ruột non, chiếm khoảng 2/5 chiều dài hỗng–hồi tràng, đường kính lớn hơn, nếp vòng niêm mạc cao và dày.',
                'Hầu hết carbohydrate, protein và lipid được tiêu hóa và hấp thu tại đây.'),
    'Vermiform appendix': ('Ruột thừa', 'Ống mù dài mảnh nhô ra từ thành sau trong manh tràng, gốc nằm ở chỗ hội tụ ba dải đại tràng.',
                           'Giàu mô bạch huyết tham gia miễn dịch niêm mạc ruột, cũng được xem là “kho dự trữ” hệ vi khuẩn đường ruột.'),
    'Ascending colon': ('Đại tràng lên', 'Đoạn đầu đại tràng, từ hố chậu phải đi lên dọc thành sau bụng phải đến dưới thùy phải gan.',
                        'Hấp thu nước và điện giải, đẩy nội dung ruột về phía góc đại tràng phải.'),
    'Transverse colon': ('Đại tràng ngang', 'Đoạn ngang ở thượng vị, từ góc đại tràng phải đến góc đại tràng trái, có mạc treo nên độ di động lớn.',
                         'Tiếp tục hấp thu nước và điện giải, hệ vi khuẩn tại đây tổng hợp vitamin K và một số vitamin nhóm B.'),
    'Descending colon': ('Đại tràng xuống', 'Đoạn từ góc đại tràng trái đi xuống dọc thành sau bụng trái đến mào chậu trái.',
                         'Lưu trữ và vận chuyển phân đã dần định hình đến đại tràng sigma.'),
    'Sigmoid colon': ('Đại tràng sigma', 'Đoạn cuối đại tràng cong hình chữ S, có mạc treo, độ di động lớn, nối tiếp trực tràng.',
                      'Tạm chứa phân, nhu động mạnh đẩy phân vào trực tràng gây cảm giác muốn đại tiện.'),
    'Free taenia': ('Dải tự do', 'Một trong ba dải dọc của đại tràng, nằm ở mặt tự do của đại tràng.',
                    'Dải đại tràng ngắn hơn ống ruột, kéo thành ruột tạo túi đại tràng, là mốc nhận biết đại tràng và tìm gốc ruột thừa.'),
    'Mesocolic taenia': ('Dải mạc treo', 'Một dải đại tràng nằm ở chỗ bám mạc treo.',
                         'Cùng các dải khác rút ngắn ống ruột tạo túi đại tràng, đánh dấu đường bám của mạc treo.'),
    'Omental taenia': ('Dải mạc nối', 'Một dải đại tràng nằm ở chỗ bám mạc nối lớn.',
                       'Cùng các dải khác tạo túi đại tràng, đánh dấu đường bám của mạc nối lớn trên đại tràng ngang.'),

    # ---------- Tuyến tiêu hóa ----------
    'Liver': ('Gan', 'Cơ quan đặc và tuyến tiêu hóa lớn nhất cơ thể, nằm ở vùng thượng vị phải, nặng khoảng 1,5 kg.',
              'Tổng hợp protein huyết tương và mật, chuyển hóa đường–lipid–thuốc, giải độc, dự trữ glycogen và vitamin; là nội tạng duy nhất có khả năng tái sinh mạnh.'),
    'Gallbladder': ('Túi mật', 'Túi hình quả lê nằm trong hố túi mật mặt dưới gan, dung tích khoảng 40–60 ml.',
                    'Lưu trữ và cô đặc mật, khi ăn co bóp đẩy mật qua ống mật chủ vào tá tràng để nhũ hóa lipid.'),
    'Bile duct': ('Ống mật chủ', 'Được tạo bởi sự hợp nhất của ống gan chung và ống túi mật, đầu dưới thường hợp với ống tụy đổ vào nhú tá tràng lớn.',
                  'Vận chuyển mật do gan tiết và túi mật lưu trữ đến tá tràng.'),
    'Pancreas': ('Tụy', 'Tuyến dài hẹp nằm sau phúc mạc vùng thượng vị, chia thành đầu, cổ, thân, đuôi.',
                 'Phần ngoại tiết tiết dịch tụy chứa nhiều enzyme tiêu hóa; phần nội tiết (đảo tụy) tiết insulin và glucagon điều hòa đường huyết.'),
    'Pancreatic duct': ('Ống tụy', 'Ống chính chạy dọc suốt nhu mô tụy, đầu tận hợp với ống mật chủ.',
                        'Thu thập dịch tụy từ các tiểu thùy và đổ vào tá tràng.'),
    'Accessory pancreatic duct': ('Ống tụy phụ', 'Ống nhỏ xuất phát từ phần trên đầu tụy, đổ vào nhú tá tràng nhỏ.',
                                  'Là đường dẫn lưu phụ của dịch tụy; khi ống tụy chính bị tắc có thể dẫn lưu bù.'),
    'Parotid gland': ('Tuyến mang tai', 'Tuyến nước bọt lớn nhất trong ba tuyến chính, nằm trước dưới tai, mặt nông cơ cắn.',
                      'Tiết nước bọt chủ yếu thanh dịch, chứa amylase khởi đầu tiêu hóa carbohydrate; dây thần kinh mặt đi xuyên qua nhu mô tuyến.'),
    '(Accessory parotid gland)': ('Tuyến mang tai phụ', 'Khối tuyến nhỏ độc lập thường gặp phía trên ống tuyến mang tai, xuất hiện ở khoảng 20% người.',
                                  'Chức năng giống tuyến mang tai, tiết nước bọt thanh dịch đổ vào ống tuyến mang tai.'),
    'Parotid duct': ('Ống tuyến mang tai', 'Ống xuất phát từ bờ trước tuyến, chạy ngang mặt cơ cắn, đổ vào niêm mạc má đối diện răng hàm trên thứ hai.',
                     'Vận chuyển nước bọt do tuyến mang tai tiết đến khoang miệng.'),
    'Submandibular gland': ('Tuyến dưới hàm', 'Tuyến nước bọt hỗn hợp nằm trong tam giác dưới hàm, mặt trong thân xương hàm dưới.',
                            'Tiết nước bọt hỗn hợp chủ yếu thanh dịch, là nguồn chính của nước bọt khi nghỉ (chiếm khoảng 70%).'),
    'Submandibular duct': ('Ống tuyến dưới hàm', 'Ống xuất phát từ phần sâu tuyến dưới hàm, chạy về phía trước sàn miệng, đổ vào nụ lưỡi dưới.',
                           'Vận chuyển nước bọt tuyến dưới hàm đến sàn miệng.'),
    'Sublingual gland': ('Tuyến dưới lưỡi', 'Tuyến nước bọt nhỏ nhất trong ba tuyến chính, nằm sâu dưới nếp dưới lưỡi ở sàn miệng.',
                         'Tiết nước bọt chủ yếu nhầy, bôi trơn niêm mạc miệng và viên thức ăn.'),

    # ---------- Phúc mạc ----------
    'Greater omentum': ('Mạc nối lớn', 'Cấu trúc phúc mạc bốn lớp từ bờ cong lớn dạ dày thõng xuống, phủ phía trước các quai ruột.',
                        'Dự trữ mỡ, giữ nhiệt; có thể di chuyển đến ổ viêm bao bọc và hạn chế lan truyền nhiễm khuẩn, nên được gọi là “cảnh sát ổ bụng”.'),
    'Lesser omentum': ('Mạc nối nhỏ', 'Phúc mạc hai lớp nối cửa gan với bờ cong nhỏ dạ dày và phần trên tá tràng.',
                       'Bờ phải tự do tạo thành dây chằng gan–tá tràng, chứa động mạch gan riêng, tĩnh mạch cửa và ống mật chủ.'),
    'Mesocolon': ('Mạc treo đại tràng', 'Phúc mạc hai lớp treo đại tràng ngang và đại tràng sigma vào thành sau bụng.',
                  'Cố định vị trí ruột đồng thời giữ độ di động, là đường đi của mạch máu, thần kinh và bạch huyết vào thành ruột.'),
    'Meso-appendix': ('Mạc treo ruột thừa', 'Phúc mạc hai lớp hình tam giác nối giữa đoạn cuối hồi tràng và ruột thừa.',
                      'Bao bọc và dẫn truyền động mạch ruột thừa; khi cắt ruột thừa cần thắt mạch máu trong đó trước.'),
    'Pleura': ('Màng phổi', 'Màng thanh dịch phủ bề mặt phổi và thành trong lồng ngực, chia lá tạng và lá thành.',
               'Khoang màng phổi giữa hai lá chứa ít dịch và áp lực âm, giúp phổi giãn theo lồng ngực và giảm ma sát khi hô hấp.'),

    # ---------- Đường hô hấp ----------
    'Epiglottis': ('Nắp thanh môn', 'Sụn đàn hồi hình lá nằm phía trước trên lỗ thanh môn cùng niêm mạc phủ.',
                   'Khi nuốt gập ra sau che lỗ thanh môn, ngăn thức ăn lọt vào đường thở.'),
    'Trachea': ('Khí quản', 'Ống từ bờ dưới sụn nhẫn đến chỗ chia hai phế quản chính, được nâng đỡ bởi 16–20 vòng sụn hình chữ C.',
                'Vận chuyển không khí vào–ra phổi; lông chuyển và chất nhầy đẩy bụi, vi khuẩn lên trên (thanh thải nhầy–lông chuyển).'),
    'Mucosa of nasal cavity': ('Niêm mạc khoang mũi', 'Niêm mạc lót mặt trong khoang mũi, chia vùng khứu giác và vùng hô hấp.',
                               'Vùng hô hấp làm ấm, ẩm và lọc không khí; vùng khứu giác chứa tế bào khứu giác cảm nhận mùi.'),
    'Right main bronchus': ('Phế quản chính phải', 'Phế quản bên phải tách từ chỗ chia khí quản, to hơn, ngắn hơn và dốc hơn bên trái.',
                            'Đưa không khí vào phổi phải; do đường đi dốc, dị vật hít phải dễ rơi vào bên phải hơn.'),
    'Left main bronchus': ('Phế quản chính trái', 'Phế quản bên trái tách từ chỗ chia khí quản, nhỏ hơn, dài hơn và đi ngang hơn.',
                           'Đưa không khí vào phổi trái, phía trước đi dưới cung động mạch chủ.'),
    'Right superior lobar bronchus': ('Phế quản thùy trên phổi phải', 'Phế quản thùy đầu tiên tách từ phế quản chính phải.',
                                      'Thông khí cho thùy trên phổi phải, rồi chia thành ba phế quản phân thùy: đỉnh, sau, trước.'),
    'Intermediate bronchus': ('Phế quản trung gian', 'Đoạn còn lại của phế quản chính phải sau khi tách phế quản thùy trên.',
                              'Tiếp tục chia thành phế quản thùy giữa và thùy dưới, là đường thông khí trung gian của phổi phải.'),
    'Middle lobar bronchus': ('Phế quản thùy giữa phổi phải', 'Phế quản thùy tách về phía trước từ phế quản trung gian.',
                              'Thông khí cho thùy giữa phổi phải, chia thành hai nhánh: phân thùy ngoài và trong.'),
    'Right inferior lobar bronchus': ('Phế quản thùy dưới phổi phải', 'Sự tiếp nối trực tiếp của phế quản trung gian.',
                                      'Thông khí cho thùy dưới phổi phải, chia thành phân thùy trên và bốn phân thùy đáy.'),
    'Left superior lobar bronchus': ('Phế quản thùy trên phổi trái', 'Phế quản thùy tách về phía trước trên từ phế quản chính trái.',
                                     'Thông khí cho thùy trên phổi trái, gồm phân thùy đỉnh–sau, trước và lưỡi trên–dưới.'),
    'Left inferior lobar bronchus': ('Phế quản thùy dưới phổi trái', 'Đoạn tiếp nối của phế quản chính trái.',
                                     'Thông khí cho thùy dưới phổi trái, chia thành phân thùy trên và các phân thùy đáy.'),
    'Superior lobe of right lung': ('Thùy trên phổi phải', 'Thùy trên cùng của phổi phải được phân bởi khe ngang và khe chéo, gồm 3 phân thùy.',
                                    'Thực hiện trao đổi khí; do vị trí cao, là nơi thường gặp tổn thương vùng đỉnh phổi.'),
    'Middle lobe of right lung': ('Thùy giữa phổi phải', 'Thùy đặc trưng của phổi phải, nằm giữa khe ngang và khe chéo, gồm 2 phân thùy.',
                                  'Thực hiện trao đổi khí; phế quản nhỏ dài và dẫn lưu kém nên dễ bị hội chứng thùy giữa.'),
    'Inferior lobe of right lung': ('Thùy dưới phổi phải', 'Thùy nằm dưới sau khe chéo, gồm 5 phân thùy, thể tích lớn nhất.',
                                    'Đảm nhận phần lớn trao đổi khí của phổi phải; tư thế nằm ngửa là nơi dễ bị viêm phổi ứ đọng.'),
    'Superior lobe of left lung': ('Thùy trên phổi trái', 'Thùy nằm trên trước khe chéo, gồm phân thùy đỉnh–sau và 4 phân thùy kèm thùy lưỡi.',
                                   'Thực hiện trao đổi khí; phần dưới (thùy lưỡi) tương đương thùy giữa phổi phải.'),
    'Inferior lobe of left lung': ('Thùy dưới phổi trái', 'Thùy nằm dưới sau khe chéo, gồm 4–5 phân thùy.',
                                   'Đảm nhận phần lớn trao đổi khí của phổi trái.'),

    # ---------- Tiết niệu ----------
    'Kidney': ('Thận', 'Cơ quan hình hạt đậu nằm sau phúc mạc hai bên cột sống, mỗi bên chứa khoảng 1 triệu đơn vị thận.',
               'Lọc máu tạo nước tiểu, điều hòa nước–muối và thăng bằng acid–base, tiết renin điều hòa huyết áp, erythropoietin kích thích tạo máu.'),
    'Renal pelvis': ('Bể thận', 'Cấu trúc hình phễu do 2–3 đài thận lớn hợp thành, nằm trong xoang thận.',
                     'Thu thập nước tiểu từ các đài thận và nhu động đưa vào niệu quản.'),
    'Ureter': ('Niệu quản', 'Ống cơ dài mảnh nối bể thận với bàng quang, dài khoảng 25–30 cm, có ba chỗ hẹp sinh lý.',
               'Nhu động đưa nước tiểu một chiều vào bàng quang; ba chỗ hẹp là nơi sỏi dễ kẹt nhất.'),
    'Urinary bladder': ('Bàng quang', 'Cơ quan dạng túi cơ nằm ở phần trước khoang chậu, khi rỗng có hình nón.',
                        'Lưu trữ nước tiểu (dung tích bình thường khoảng 350–500 ml); khi đi tiểu cơ đẩy co, cơ thắt giãn đẩy nước tiểu ra ngoài.'),
    'Urethra': ('Niệu đạo', 'Ống từ cổ bàng quang ra ngoài cơ thể, nam dài khoảng 16–22 cm, nữ khoảng 3–5 cm.',
                'Đưa nước tiểu ra ngoài; ở nam đồng thời là đường xuất tinh, ở nữ ngắn và thẳng nên dễ nhiễm khuẩn đường tiết niệu ngược dòng.'),

    # ---------- Sinh dục nam ----------
    'Testis': ('Tinh hoàn', 'Tuyến sinh dục hình bầu dục nằm trong bìu.',
               'Sản sinh tinh trùng và tiết testosterone; nhiệt độ trong bìu thấp hơn thân nhiệt khoảng 2 °C, là điều kiện cần cho sự tạo tinh.'),
    'Epididymis': ('Mào tinh', 'Cơ quan hình lưỡi liềm sát bờ sau trên tinh hoàn, cấu tạo bởi ống mào tinh cuộn chặt.',
                   'Lưu trữ tinh trùng và giúp tinh trùng trưởng thành khả năng vận động và thụ tinh trong quá trình di chuyển.'),
    'Ductus deferens': ('Ống dẫn tinh', 'Sự tiếp nối của ống mào tinh, dài khoảng 40 cm, thành dày, lớp cơ phát triển, có thể sờ thấy trong bìu.',
                        'Khi xuất tinh nhu động mạnh đưa tinh trùng từ mào tinh đến ống phóng tinh; là vị trí thắt ống dẫn tinh.'),
    'Seminal gland': ('Túi tinh', 'Tuyến dạng túi nằm sau đáy bàng quang, phía ngoài bóng ống dẫn tinh.',
                      'Tiết dịch kiềm giàu fructose, chiếm khoảng 60% tinh dịch, cung cấp năng lượng cho tinh trùng và trung hòa môi trường acid âm đạo.'),
    'Ejaculatory duct': ('Ống phóng tinh', 'Do đoạn tận ống dẫn tinh hợp với ống bài xuất túi tinh tạo thành, xuyên tuyến tiền liệt đổ vào phần tiền liệt của niệu đạo.',
                         'Đưa tinh trùng cùng dịch túi tinh vào niệu đạo.'),
    'Prostate': ('Tuyến tiền liệt', 'Tuyến hình hạt dẻ nằm dưới bàng quang, bao quanh đoạn đầu niệu đạo.',
                 'Tiết dịch tiền liệt màu trắng đục tham gia tạo tinh dịch và làm loãng tinh dịch; khi phì đại ở người già chèn ép niệu đạo gây khó tiểu.'),
    'Corpus cavernosum of penis': ('Thể hang dương vật', 'Hai trụ hình trụ nằm ở mặt lưng dương vật, được bao bởi màng trắng.',
                                   'Các xoang hang sung huyết và bị màng trắng hạn chế hồi lưu là cơ sở cấu trúc chính của sự cương dương vật.'),
    'Corpus spongiosum of penis': ('Thể xốp dương vật', 'Một thể hang nằm ở mặt bụng dương vật, bên trong có niệu đạo xuyên qua.',
                                   'Bảo vệ niệu đạo không bị ép chặt khi cương, đầu trước phình to tạo thành quy đầu.'),
    'Glans penis': ('Quy đầu', 'Phần phình to ở đầu trước thể xốp, bề mặt phủ bao quy đầu.',
                    'Chứa nhiều đầu mút thần kinh cảm giác, là vùng nhạy cảm tình dục nhất; đầu nhọn là lỗ niệu đạo ngoài.'),

    # ---------- Nội tiết ----------
    'Thyroid gland': ('Tuyến giáp', 'Tuyến hình chữ H nằm hai bên trước thanh quản và khí quản, là tuyến nội tiết lớn nhất cơ thể.',
                      'Tiết hormone tuyến giáp điều hòa tốc độ chuyển hóa và phát triển toàn thân, tiết calcitonin tham gia điều hòa canxi máu.'),
    'Superior parathyroid gland': ('Tuyến cận giáp trên', 'Thể nhỏ màu vàng nâu dính mặt sau phần trên thùy bên tuyến giáp, thường mỗi bên một cái.',
                                   'Tiết hormone cận giáp làm tăng canxi máu; cắt nhầm trong phẫu thuật tuyến giáp có thể gây co giật do hạ canxi.'),
    'Inferior parathyroid gland': ('Tuyến cận giáp dưới', 'Nằm ở mặt sau phần dưới thùy bên tuyến giáp, vị trí biến đổi nhiều hơn tuyến trên.',
                                   'Tiết hormone cận giáp, huy động canxi xương, tăng tái hấp thu canxi ở thận để duy trì ổn định canxi máu.'),
    'Suprarenal gland': ('Tuyến thượng thận', 'Tuyến đôi nằm ở đầu trên hai thận, gồm vỏ và tủy.',
                         'Vỏ tiết glucocorticoid, mineralocorticoid và hormone sinh dục; tủy tiết adrenaline ứng phó stress.'),
    'Adenohypophysis': ('Thùy trước tuyến yên', 'Thùy trước tuyến yên, chiếm 75% thể tích tuyến yên, thuộc mô tuyến.',
                        'Tiết hormone tăng trưởng, TSH, ACTH, gonadotropin… điều khiển nhiều tuyến nội tiết khác.'),
    'Neurohypophysis': ('Thùy sau tuyến yên', 'Thùy sau tuyến yên, cấu tạo bởi mô thần kinh kéo dài từ hạ đồi.',
                        'Lưu trữ và giải phóng hormone kháng bài niệu và oxytocin do hạ đồi tổng hợp.'),
    'Pineal gland': ('Tuyến tùng', 'Tuyến nhỏ hình quả thông nằm ở mặt lưng gian não, giữa hai gò trên.',
                     'Tiết melatonin điều hòa nhịp ngày–đêm và giấc ngủ; người trưởng thành thường bị vôi hóa trở thành mốc định vị trên hình ảnh.'),

    # ---------- Tổng thể ----------
    'Visceral systems': ('Hệ nội tạng', 'Tên gọi chung của các cơ quan khoang ngực–bụng–chậu thuộc tiêu hóa, hô hấp, tiết niệu, sinh dục…',
                         'Thực hiện hấp thu dinh dưỡng và thải chất chuyển hóa, trao đổi khí cũng như sinh sản.'),
}


# ---------- Phế quản phân thùy (tên kèm mã phân thùy quốc tế) ----------
_BRONCHI = {
    'Apical segmental bronchus of right lung (BI)': ('Phế quản phân thùy đỉnh phổi phải', 'B I', 'phân thùy đỉnh thùy trên phổi phải'),
    'Posterior segmental bronchus of right lung (BII)': ('Phế quản phân thùy sau phổi phải', 'B II', 'phân thùy sau thùy trên phổi phải'),
    'Anterior segmental bronchus of right lung (BIII)': ('Phế quản phân thùy trước phổi phải', 'B III', 'phân thùy trước thùy trên phổi phải'),
    'Lateral segmental bronchus of right lung (BIV)': ('Phế quản phân thùy ngoài phổi phải', 'B IV', 'phân thùy ngoài thùy giữa phổi phải'),
    'Medial segmental bronchus of right lung (BV)': ('Phế quản phân thùy trong phổi phải', 'B V', 'phân thùy trong thùy giữa phổi phải'),
    'Superior segmental bronchus of right lung (BVI)': ('Phế quản phân thùy trên thùy dưới phổi phải', 'B VI', 'phân thùy trên thùy dưới phổi phải'),
    'Medial basal segmental bronchus of right lung (BVII)': ('Phế quản phân thùy đáy trong phổi phải', 'B VII', 'phân thùy đáy trong thùy dưới phổi phải'),
    'Anterior basal segmental bronchus of right lung (BVIII)': ('Phế quản phân thùy đáy trước phổi phải', 'B VIII', 'phân thùy đáy trước thùy dưới phổi phải'),
    'Lateral basal segmental bronchus of right lung (BIX)': ('Phế quản phân thùy đáy ngoài phổi phải', 'B IX', 'phân thùy đáy ngoài thùy dưới phổi phải'),
    'Posterior basal segmental bronchus of right lung (BX)': ('Phế quản phân thùy đáy sau phổi phải', 'B X', 'phân thùy đáy sau thùy dưới phổi phải'),
    'Apicoposterior segmental bronchus of left lung (BI+BII)': ('Phế quản phân thùy đỉnh–sau phổi trái', 'B I+II', 'phân thùy đỉnh–sau thùy trên phổi trái'),
    'Anterior segmental bronchus of left lung (BIII)': ('Phế quản phân thùy trước phổi trái', 'B III', 'phân thùy trước thùy trên phổi trái'),
    'Superior lingular segmental bronchus of left lung (BIV)': ('Phế quản phân thùy lưỡi trên phổi trái', 'B IV', 'phân thùy lưỡi trên thùy trên phổi trái'),
    'Inferior lingular segmental bronchus of left lung (BV)': ('Phế quản phân thùy lưỡi dưới phổi trái', 'B V', 'phân thùy lưỡi dưới thùy trên phổi trái'),
    'Superior segmental bronchus of left lung (BVI)': ('Phế quản phân thùy trên thùy dưới phổi trái', 'B VI', 'phân thùy trên thùy dưới phổi trái'),
    'Medial basal segmental bronchus of left lung (BVII)': ('Phế quản phân thùy đáy trong phổi trái', 'B VII', 'phân thùy đáy trong thùy dưới phổi trái'),
    '(Anteromedial basal segmental bronchus of left lung)': ('Phế quản phân thùy đáy trước–trong phổi trái', 'B VII+VIII', 'phân thùy đáy trước–trong thùy dưới phổi trái'),
    'Anterior basal segmental bronchus of left lung (BVIII)': ('Phế quản phân thùy đáy trước phổi trái', 'B VIII', 'phân thùy đáy trước thùy dưới phổi trái'),
    'Lateral basal segmental bronchus of left lung (BIX)': ('Phế quản phân thùy đáy ngoài phổi trái', 'B IX', 'phân thùy đáy ngoài thùy dưới phổi trái'),
    'Posterior basal segmental bronchus of left lung (BX)': ('Phế quản phân thùy đáy sau phổi trái', 'B X', 'phân thùy đáy sau thùy dưới phổi trái'),
}
for _en, (_zh, _code, _seg) in _BRONCHI.items():
    TERMS[_en] = (
        _zh,
        f'Phế quản phân thùy đi đến {_seg}, mã quốc tế {_code}.',
        'Thông khí độc lập cho phân thùy này, là mốc giải phẫu quan trọng khi cắt phân thùy phổi và định vị nội soi phế quản.')


# ---------- Phân đoạn gan (phân đoạn Couinaud) ----------
_LIVER = {
    'Posterior segment of liver (I)': ('Thùy đuôi gan', 'Ⅰ', 'nằm ở mặt dưới gan, giữa tĩnh mạch chủ dưới và dây chằng tĩnh mạch'),
    'Left posterior lateral segment of liver (II)': ('Phân đoạn ngoài trên thùy trái gan', 'Ⅱ', 'phần trên thùy ngoài trái gan'),
    'Left anterior lateral segment of liver (III)': ('Phân đoạn ngoài dưới thùy trái gan', 'Ⅲ', 'phần dưới thùy ngoài trái gan'),
    'Left medial segment of liver (IV)': ('Thùy trong trái gan', 'Ⅳ', 'nằm giữa dây chằng liềm và hố túi mật'),
    'Anterior medial segment of liver (V)': ('Phân đoạn trước dưới thùy phải gan', 'Ⅴ', 'phần dưới thùy trước phải gan'),
    'Anterior lateral segment of liver (VI)': ('Phân đoạn sau dưới thùy phải gan', 'Ⅵ', 'phần dưới thùy sau phải gan'),
    'Posterior lateral segment of liver (VII)': ('Phân đoạn sau trên thùy phải gan', 'Ⅶ', 'phần trên thùy sau phải gan'),
    'Posterior medial segment of liver (VIII)': ('Phân đoạn trước trên thùy phải gan', 'Ⅷ', 'phần trên thùy trước phải gan'),
}
for _en, (_zh, _num, _pos) in _LIVER.items():
    TERMS[_en] = (
        _zh,
        f'Phân đoạn thứ {_num} theo Couinaud, {_pos}.',
        'Có nhánh tĩnh mạch cửa, động mạch gan và ống mật dẫn lưu độc lập, là đơn vị cơ bản trong phẫu thuật cắt phân đoạn gan.')